import { COLORS, Fonts, SF, SH, SW } from '@/theme';
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.inputBorder,
  },
  searchMainView: {
    backgroundColor: COLORS.white,
    borderRadius: 5,
    paddingVertical: 3,
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 15,
    paddingHorizontal: 5,
  },
  searchIconStyle: {
    width: SW(32),
    height: SW(32),
    resizeMode: 'contain',
  },
  searchTextInputStyle: {
    borderWidth: 2,
    height: SH(48),
    borderColor: COLORS.transparent,
    width: SW(235),
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    fontFamily: Fonts.Italic,
  },
  scannerViewStyle: {
    borderRadius: 7,
    backgroundColor: COLORS.darkBlue,
    alignItems: 'center',
    justifyContent: 'center',
    width: SW(72),
    height: SW(56),
  },
  headingText: {
    fontFamily: Fonts.MaisonMonoBold,
    fontSize: SF(18),
    color: COLORS.dark_gray,
    paddingLeft: 20,
    paddingTop: 20,
    paddingBottom: 10,
  },
  categoryImageStyle: {
    width: SW(24),
    height: SW(24),
    resizeMode: 'contain',
  },
  categoryTitleText: {
    fontFamily: Fonts.SemiBold,
    fontSize: SF(13),
    color: COLORS.text,
  },
  categoryMainView: {
    borderWidth: 1,
    height: SH(52),
    width: SW(160),
    borderRadius: 30,
    // position: 'absolute',
    alignItems: 'center',
    flexDirection: 'row',
    marginHorizontal: 3,
    marginBottom: 10,
    borderColor: COLORS.light_border,
    backgroundColor: COLORS.white,
  },
  subCategoryView: {
    marginHorizontal: 10,
    backgroundColor: COLORS.white,
    borderRadius: 10,
    marginTop: 15,
  },
  subCategoryInnerView: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingVertical: 20,
  },
  clothImageStyle: {
    width: SW(120),
    height: SW(120),
    resizeMode: 'contain',
  },
  titleTextStyle: {
    fontFamily: Fonts.MaisonMonoBold,
    fontSize: SF(18),
    color: COLORS.black,
  },
  brandsTextStyle: {
    fontFamily: Fonts.SemiBold,
    fontSize: SF(14),
    color: COLORS.text,
    paddingTop: 6,
  },
  productTextStyle: {
    fontFamily: Fonts.Regular,
    fontSize: SF(14),
    color: COLORS.text,
    paddingTop: 6,
  },
  productViewStyle: {
    flexDirection: 'row',
    marginBottom: 15,
    marginLeft: 10,
  },
  productImages: {
    width: SW(49),
    height: SW(49),
    resizeMode: 'contain',
  },
  viewAllViewStyle: {
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 0,
    width: SW(52),
    height: SW(52),
    borderRadius: 5,
    borderColor: COLORS.light_border,
    left: 2,
  },
  viewAllTextStyle: {
    fontFamily: Fonts.Regular,
    fontSize: SF(9),
    color: COLORS.text,
  },
  viewAllImage: {
    width: SW(16),
    height: SW(16),
    resizeMode: 'contain',
  },
  backIconView: {
    borderRadius: 30,
    height: SH(49),
    width: SW(55),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.text,
  },
  backIconstyle: {
    width: SW(14),
    height: SH(14),
    resizeMode: 'contain',
    tintColor: COLORS.skyBlue,
  },
  singleProductStyle: {
    marginHorizontal: 2,
    borderWidth: 1,
    borderColor: COLORS.light_border,
    borderRadius: 5,
  },
  contentContainerStyle: {
    marginHorizontal: 10,
    marginTop: 10,
    paddingBottom: 30,
    paddingRight: 20,
  },
});

export default styles;
