import { StyleSheet, Dimensions, Platform } from 'react-native';
import { SW, SH, SF, ShadowStyles } from '@/theme';
import { COLORS } from '@/theme';
import { Fonts } from '@/assets';
import { verticalScale, moderateScale, ms } from 'react-native-size-matters';

const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
    borderRadius: 30,
    marginRight: SW(5),
    marginVertical: SH(5),
  },
  displayFlex: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  flexAlign: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  checkoutText1: {
    color: COLORS.navy_blue,
    fontSize: SF(16),
    fontFamily: Fonts.Regular,
  },
  displayRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  lockLight: {
    width: SW(6),
    height: SW(6),
    resizeMode: 'contain',
    paddingHorizontal: moderateScale(10),
  },
  cross: {
    width: SW(10),
    height: SH(10),
    resizeMode: 'contain',
    paddingHorizontal: moderateScale(10),
  },
  headerMainView: {
    width: windowWidth - 75,
    paddingHorizontal: SW(16),
    alignSelf: 'center',
    justifyContent: 'space-between',
    paddingVertical: SH(18),
    flexDirection: 'row',
  },
  searchView: {
    borderWidth: 1,
    width: SW(120),
    height: SH(38),
    borderRadius: 30,
    borderColor: COLORS.row_grey,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 10,
  },
  searchImage: {
    width: SH(20),
    height: SH(20),
    resizeMode: 'contain',
  },
  crossImage: {
    width: SH(25),
    height: SH(25),
    resizeMode: 'contain',
    marginLeft: 10,
  },
  textInputStyle: {
    width: SW(100),
    // marginLeft: 10,
    fontFamily: Fonts.Italic,
    // borderWidth: 3,
    fontSize: SF(15),
    paddingLeft: 10,
    padding: 0,
    margin: 0,
  },
  truckStyle: {
    width: SH(32),
    height: SH(32),
    resizeMode: 'contain',
  },
  deliveryView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  deliveryText: {
    fontFamily: Fonts.MaisonBold,
    color: COLORS.navy_blue,
    fontSize: SF(20),
    paddingLeft: SW(4),
  },
  cashDrawerView: {
    width: windowWidth - 180,
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: SH(15),
    paddingVertical: SH(10),
    backgroundColor: COLORS.sky_grey,
    borderRadius: 10,
    borderRadius: 100,
  },
  cashDrawerText: {
    fontFamily: Fonts.SemiBold,
    color: COLORS.navy_blue,
    fontSize: SF(19),
  },
  cashDrawerTextNew: {
    fontFamily: Fonts.SemiBold,
    color: COLORS.navy_blue,
    fontSize: SF(19),
  },
  cashDrawerNew: {
    fontFamily: Fonts.SemiBold,
    color: COLORS.navy_blue,
    fontSize: SF(19),
  },
  drawerIdPurple: {
    fontFamily: Fonts.Regular,
    color: COLORS.purple,
    fontSize: SF(14),
    marginHorizontal: SH(10),
    width: '60%',
  },
  drawerIdText: {
    fontFamily: Fonts.Regular,
    color: COLORS.solid_grey,
    fontSize: SF(14),
  },
  loggedInAsText: {
    fontFamily: Fonts.SemiBold,
    color: COLORS.navy_blue,
    fontSize: SF(16),
  },
  cashierName: {
    color: COLORS.solid_grey,
    fontSize: SF(16),
    fontFamily: Fonts.SemiBold,
  },
  posCashier: {
    color: COLORS.dark_grey,
    fontSize: SF(14),
    fontFamily: Fonts.SemiBold,
  },
  cashProfilecon: {
    // borderWidth: 4,
    // borderRadius: 100,
    // borderColor: COLORS.solidGrey,
    // alignItems: 'center',
  },
  cashLabel: {
    color: COLORS.solid_grey,
    fontSize: SF(14),
    fontFamily: Fonts.Regular,
  },
  cashProfile: {
    width: SW(30),
    height: SW(30),
    resizeMode: 'contain',
    borderRadius: 100,
  },
  trackingButtonView: {
    width: SW(70),
    height: SH(55),
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.navy_blue,
  },
  trackingButtonText: {
    fontFamily: Fonts.Medium,
    color: COLORS.white,
    fontSize: SF(12),
    textAlign: 'left',
  },
  calculatorView: {
    width: SW(110),
    alignSelf: 'center',
    height: windowHeight * 0.22,
    justifyContent: 'center',
    marginTop: SW(5),
  },
  viewSessionButtonView: {
    width: SW(50),
    height: SH(50),
    borderRadius: 100,
    justifyContent: 'center',
    // borderWidth: 1,
    // borderColor: COLORS.primary,
    alignItems: 'center',
    backgroundColor: COLORS.white,
  },
  closeBatchButtonView: {
    width: SW(50),
    height: SH(45),
    borderRadius: 5,
    justifyContent: 'center',
    // borderWidth: 1,
    // borderColor: COLORS.primary,
    alignItems: 'center',
    backgroundColor: COLORS.alert_red,
    borderRadius: 100,
  },
  lockScreenButton: {
    // flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.navy_blue,
    width: windowWidth * 0.14,
    marginHorizontal: SH(10),

    height: SW(14),
    alignSelf: 'center',
    borderRadius: 100,

    // paddingVertical: verticalScale(9),
  },
  viewSessionButtonText: {
    fontFamily: Fonts.Bold,
    color: COLORS.navy_blue,
    fontSize: SF(12),
  },
  closeBatchButtonText: {
    fontFamily: Fonts.Bold,
    color: COLORS.white,
    fontSize: SF(12),
  },
  sessionHistoryView: {
    width: windowWidth - 180,
    alignSelf: 'center',
    borderWidth: 2,
    borderColor: COLORS.light_purple,
    borderRadius: 10,
    paddingVertical: SH(20),
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: SH(25),
    borderRadius: 100,
  },
  sessionHistoryText: {
    fontFamily: Fonts.SemiBold,
    color: COLORS.faded_purple,
    fontSize: SF(15),
  },

  sessionHistoryTextNew: {
    fontFamily: Fonts.SemiBold,
    color: COLORS.white,
    fontSize: SF(20),
  },
  rightIconStyle: {
    width: SH(24),
    height: SH(24),
    resizeMode: 'contain',
  },
  modalMainView: {
    backgroundColor: COLORS.white,
    width: SW(142),
    borderRadius: 30,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',

    minHeight: windowHeight - 280,
    // borderWidth:10
  },
  headerView: {
    // backgroundColor: COLORS.primary,
    width: SW(160),
    height: SH(60),
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    // borderBottomWidth: 0.3,
    // borderBottomColor: COLORS.gerySkies,
  },
  crossIconStyle: {
    width: SH(24),
    height: SH(24),
    resizeMode: 'contain',
    tintColor: COLORS.black,
    alignSelf: 'center',
    right: SW(15),
  },
  addMoneyStyle: {
    width: SW(90),
    height: SH(90),
    resizeMode: 'contain',
    tintColor: COLORS.green,
    alignSelf: 'center',
  },
  calculatorStyle: {
    width: SW(100),
    height: SH(100),
    resizeMode: 'contain',
  },
  infoStyle: {
    width: SW(80),
    height: SH(80),
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  countCashView: {
    width: SW(130),
    alignSelf: 'center',
    height: '70%',
  },
  countCashText: {
    fontFamily: Fonts.MaisonBold,
    color: COLORS.navy_blue,
    fontSize: SF(22),
    textAlign: 'center',
  },
  amountCountedText: {
    fontFamily: Fonts.Medium,
    color: COLORS.navy_blue,
    fontSize: SF(15),
  },
  inputStyle: {
    marginTop: 4,
    height: SH(60),
    borderRadius: 5,
    fontFamily: Fonts.Regular,
    fontSize: SF(24),
    color: COLORS.navy_blue,
    paddingLeft: SW(5),
    paddingVertical: SH(5),
    // backgroundColor: COLORS.sky_grey,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: COLORS.lavender,
  },
  noteInputStyle: {
    marginTop: 4,
    width: SW(130),
    height: SH(60),
    borderRadius: 5,
    fontFamily: Fonts.Italic,
    fontSize: SF(13),
    color: COLORS.navy_blue,
    paddingLeft: SW(5),
    paddingVertical: SH(5),
    // backgroundColor: COLORS.textInputBackground,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: COLORS.navy_blue,
  },
  noteInputStyleNew: {
    marginTop: 4,
    width: SW(130),
    height: SH(60),
    borderRadius: 5,
    fontFamily: Fonts.Italic,
    fontSize: SF(13),
    color: COLORS.navy_blue,
    paddingLeft: SW(5),
    paddingVertical: SH(5),
    // backgroundColor: COLORS.textInputBackground,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.lavender,
  },
  buttonText: {
    fontSize: SF(16),
    color: COLORS.white,
    textAlign: 'center',
    fontFamily: Fonts.Medium,
  },
  saveButton: {
    alignSelf: 'center',
    width: windowWidth * 0.28,
    height: SH(60),
    zIndex: -999,
    backgroundColor: COLORS.gerySkies,
  },
  sessionMainView: {
    width: windowWidth - 220,
    alignSelf: 'center',
    borderRadius: 20,
    paddingTop: SH(10),
    backgroundColor: COLORS.sky_grey,
    marginTop: SH(12),
  },
  sessionView: {
    width: windowWidth - 250,
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: COLORS.textInputBackground,
  },
  usdText: {
    fontSize: SF(38),
    color: COLORS.primary,
    textAlign: 'center',
    fontFamily: Fonts.SemiBold,
  },
  usdTextNew: {
    fontSize: SF(38),
    color: COLORS.navy_blue,
    textAlign: 'center',
    fontFamily: Fonts.SemiBold,
  },
  buttonView: {
    justifyContent: 'space-between',
    width: windowWidth - 220,
    alignSelf: 'center',
  },
  addCashView: {
    width: SW(144),
    height: SH(90),
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.blue_shade,
  },
  addCashViewNew: {
    width: SW(75),
    height: SH(65),
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.navy_blue,
    borderRadius: 100,
    flexDirection: 'row',
  },
  closeBatchButton: {
    width: SW(75),
    height: SH(65),
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.navy_blue,
    borderRadius: 100,
    flexDirection: 'row',
    alignSelf: 'flex-end',
    right: 20,
    flexDirection: 'row',
  },
  nextButtonEnd: {
    width: '100%',
    height: SH(65),
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.navy_blue,
    borderRadius: 100,
    flexDirection: 'row',
    alignSelf: 'flex-end',
    flexDirection: 'row',
  },
  cancelBatch: {
    width: '100%',
    height: SH(65),
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.alert_red,
    borderRadius: 100,
    flexDirection: 'row',
    alignSelf: 'flex-end',
    flexDirection: 'row',
  },
  removeCashView: {
    width: SW(144),
    height: SH(90),
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.silver_solid,
  },
  removeCashViewNew: {
    width: SW(75),
    height: SH(65),
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',

    borderColor: COLORS.navy_blue,
    borderWidth: 1,
    borderRadius: 100,
    marginRight: SH(40),
  },
  cashPaymentsText: {
    fontFamily: Fonts.SemiBold,
    fontSize: SF(24),
    color: COLORS.black,
  },
  cashPaymentsNew: {
    fontFamily: Fonts.SemiBold,
    fontSize: SF(24),
    color: COLORS.navy_blue,
  },
  paymentOptionsView: {
    // borderBottomWidth: 1,
    // borderBottomColor: COLORS.solidGrey,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: SH(20),
    paddingBottom: SH(15),
  },
  paymentBodyCon: {
    // borderBottomWidth: 1,
    // borderBottomColor: COLORS.solidGrey,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: verticalScale(7),
    // paddingHorizontal: moderateScale(12),
  },
  buttonStyle: {
    width: windowWidth - 110,
    height: SH(90),
    alignSelf: 'center',
  },

  // summary history css start
  summaryHeaderCon: {
    height: SH(100),
    justifyContent: 'center',
    paddingHorizontal: moderateScale(10),
  },
  backButtonCon: {
    backgroundColor: COLORS.sky_grey,
    borderRadius: 3,
    width: windowWidth * 0.08,
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: 100,
  },
  backButtonArrow: {
    width: SW(12),
    height: SW(8),
    resizeMode: 'contain',
    tintColor: COLORS.dark_grey,
  },
  backTextStyle: {
    color: COLORS.dark_grey,
    fontFamily: Fonts.SemiBold,
    fontSize: SF(16),
    paddingVertical: verticalScale(5),
  },
  summaryText: {
    color: COLORS.black,
    fontFamily: Fonts.MaisonBold,
    fontSize: SF(18),
  },
  bodyContainer: {
    width: windowWidth * 0.88,
    height: windowHeight * 0.68,
    alignSelf: 'center',
    paddingHorizontal: SW(10),
  },
  bodyContainer2: {
    width: windowWidth * 0.88,
    height: windowHeight * 0.84,
    alignSelf: 'center',
    paddingHorizontal: SW(10),
  },
  allCashText: {
    color: COLORS.navy_blue,
    fontFamily: Fonts.SemiBold,
    fontSize: SF(20),
  },
  totalCashHeader: {
    borderBottomWidth: 1,
    borderColor: COLORS.solidGrey,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: verticalScale(6),
    marginTop: 15,
  },
  totalCashData: {
    borderBottomWidth: 1,
    borderColor: COLORS.solidGrey,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: verticalScale(5),
  },
  sectionListHeader: {
    color: COLORS.black,
    fontFamily: Fonts.SemiBold,
    fontSize: SF(17),
  },
  sectionListData: {
    color: COLORS.dark_grey,
    fontFamily: Fonts.Regular,
    fontSize: SF(12),
  },
  netPaymentHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: verticalScale(6),
    marginTop: 15,
  },
  cashActivity: {
    color: COLORS.darkGray,
    fontFamily: Fonts.SemiBold,
    fontSize: SF(20),
  },
  cashActivityCon: {
    borderBottomWidth: 1,
    borderColor: COLORS.solidGrey,
    paddingVertical: verticalScale(3),
    marginTop: 5,
  },
  cashActivityDarkText: {
    color: COLORS.solid_grey,
    fontFamily: Fonts.SemiBold,
    fontSize: SF(16),
  },
  cashActivityLightText: {
    color: COLORS.solid_grey,
    fontFamily: Fonts.Regular,
    fontSize: SF(12),
  },
  cashActivityRedText: {
    color: COLORS.orange,
    fontFamily: Fonts.Regular,
    fontSize: SF(12),
  },
  tableHeaderStyle: {
    color: COLORS.faded_purple,
    fontFamily: Fonts.Bold,
    fontSize: SF(12),
  },
  tableRowStyle: {
    borderBottomColor: COLORS.sky_grey,
    borderTopColor: COLORS.sky_grey,
    borderRadius: 100,
    borderBottomWidth: 2,
    borderTopWidth: 2,
    borderEndWidth: 2,
    borderStartWidth: 2,
    borderStartColor: COLORS.sky_grey,
    borderEndColor: COLORS.sky_grey,
    marginVertical: 3,
    flex: 1,
  },
  senEmailButton: {
    alignSelf: 'center',
    width: windowWidth * 0.88,
    height: SH(70),
  },
  // summary history css end
  // summary history css start
  sessionHistory: {
    color: COLORS.navy_blue,
    fontFamily: Fonts.MaisonBold,
    fontSize: SF(20),
    paddingHorizontal: moderateScale(12),
  },
  datePickerContainer: {
    height: SH(63),
    justifyContent: 'center',
    paddingHorizontal: moderateScale(12),
    borderBottomWidth: 1,
    borderTopWidth: 1,
    borderColor: COLORS.solidGrey,
  },
  datePickerContainerNew: {
    height: SH(63),
    justifyContent: 'space-between',
    paddingHorizontal: moderateScale(12),
    // borderBottomWidth: 1,
    // borderTopWidth: 1,
    // borderColor: COLORS.solidGrey,
    alignItems: 'center',
    flexDirection: 'row',
    marginRight: SW(-10),
  },
  datepickerConatiner: {
    borderWidth: 1,
    height: SH(35),
    width: SW(45),
    borderRadius: 3,
    borderColor: COLORS.solidGrey,
    paddingHorizontal: moderateScale(7),
    justifyContent: 'center',
  },
  calendarStyle: {
    width: SW(5),
    height: SW(5),
    resizeMode: 'contain',
    tintColor: COLORS.darkGray,
  },
  calendarStyleNew: {
    width: SW(6),
    height: SW(6),
    resizeMode: 'contain',
    // tintColor: COLORS.darkGray,
  },
  arrowLeftUp: {
    width: SW(8),
    height: SW(8),
    resizeMode: 'contain',
    // tintColor: COLORS.darkGray,
  },
  dropIcon: {
    width: SW(5),
    height: SW(5),
    resizeMode: 'contain',
    // tintColor: COLORS.darkGray,
  },
  datePlaceholder: {
    fontFamily: Fonts.Regular,
    color: COLORS.solid_grey,
    fontSize: SF(12),
    paddingHorizontal: moderateScale(5),
  },
  dropDownIcon: {
    width: SW(4),
    height: SW(4),
    resizeMode: 'contain',
  },
  dropdown: {
    alignSelf: 'center',
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    zIndex: Platform.OS === 'ios' ? 100 : 0,
  },
  containerStyle: {
    flexGrow: 1,
    justifyContent: 'center',
    borderRadius: 7,
    borderColor: COLORS.solidGrey,
    backgroundColor: COLORS.textInputBackground,
    height: SH(60),
    borderRadius: 5,
    fontFamily: Fonts.Regular,
    fontSize: SF(24),
    color: COLORS.solid_grey,
  },
  dropDownContainerStyle: {
    borderColor: COLORS.solidGrey,
    borderRadius: 7,
    ...ShadowStyles.shadow2,
    backgroundColor: COLORS.white,
    // top: Platform.OS === 'android' ? 50 : 15,
    zIndex: Platform.OS === 'ios' ? 999 : 1,
  },
  listItemLabelStyle: {
    fontSize: SF(12),
    fontFamily: Fonts.Regular,
  },
  labelStyle: {
    fontSize: SF(12),
    fontFamily: Fonts.Regular,
  },
  selectedItemLabelStyle: {
    fontSize: SF(12),
    fontFamily: Fonts.Regular,
  },
  placeholderStyle: {
    fontSize: SF(12),
    fontFamily: Fonts.Regular,
    color: COLORS.solid_grey,
  },
  userTableHead: {
    height: SH(50),
    backgroundColor: '#E1E3E4',
    textAlign: 'center',
    borderWidth: 0,
    borderColor: 'transparent',
  },
  text: {
    fontFamily: Fonts.MaisonBold,
    color: COLORS.solid_grey,
    fontSize: SF(14),
    textAlign: 'center',
  },
  historyHeaderText: {
    width: windowWidth * 0.112,
    justifyContent: 'center',
    fontFamily: Fonts.MaisonBold,
    color: COLORS.solid_grey,
    fontSize: SF(14),
    textAlign: 'left',
  },
  historydataText: {
    fontFamily: Fonts.Regular,
    color: COLORS.solid_grey,
    fontSize: SF(12),
    textAlign: 'left',
    width: windowWidth * 0.112,
    justifyContent: 'center',
  },
  usertableRowStyle: {
    borderBottomWidth: 1,
    borderBottomColor: COLORS.solidGrey,
    paddingVertical: SH(18),
  },
  usertableRowText: {
    fontFamily: Fonts.Regular,
    color: COLORS.solid_grey,
    fontSize: SF(12),
    // textAlign: 'center',
  },
  tableMainView: {
    zIndex: -10,
  },
  tableDataHeaderCon: {
    height: SH(50),
    backgroundColor: '#E1E3E4',
    textAlign: 'center',
    borderWidth: 0,
    borderColor: 'transparent',
    paddingHorizontal: moderateScale(20),
    justifyContent: 'center',
  },
  tableDataCon: {
    height: SH(55),
    borderBottomWidth: 1,
    borderColor: COLORS.solidGrey,
    justifyContent: 'center',
    paddingHorizontal: moderateScale(20),
    marginHorizontal: ms(15),
  },
  allienpic: {
    width: SW(6),
    height: SW(6),
    borderRadius: 50,
    resizeMode: 'contain',
  },

  // summary history css end

  trackingBodyCon: {
    width: SW(110),
    alignSelf: 'center',
    minHeight: windowHeight * 0.6,
  },
  absoluteZero: {
    // position: 'absolute',
  },
  centerSw: {
    width: SW(145),
    paddingHorizontal: SW(5),
    // alignItems: 'center',
  },
  amountExpect: {
    fontFamily: Fonts.Regular,
    color: COLORS.navy_blue,
    fontSize: SF(18),
  },
  removerDarkText: {
    textAlign: 'center',
    fontFamily: Fonts.Bold,
    fontSize: SF(25),
    color: COLORS.navy_blue,
  },
  removerDarkTextRegular: {
    textAlign: 'center',
    fontFamily: Fonts.Regular,
    fontSize: SF(14),
    color: COLORS.navy_blue,
  },
  dateTimeAlign: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: windowWidth * 0.65,
  },
  dateHeadAlign: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: windowWidth * 0.65,
  },
  paymentBodyText: {
    fontFamily: Fonts.Regular,
    fontSize: SF(10),
    color: COLORS.navy_blue,
  },
  scrolCon: {
    // borderWidth:1,
    height: windowHeight * 0.28,
    paddingHorizontal: SH(10),
  },
  loader: {
    position: 'absolute',
    alignSelf: 'center',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
  },
  datePickerCon: {
    borderWidth: 1,
    height: SH(38),
    width: SW(45),
    borderRadius: 7,
    borderColor: COLORS.solidGrey,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: moderateScale(7),
  },
  datePickerConNew: {
    borderWidth: 1,
    height: SH(38),
    width: SW(60),
    borderRadius: 12,
    borderColor: COLORS.blue2,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: moderateScale(7),
    alignContent: 'center',
  },
  calendarStyle: {
    width: SW(5),
    height: SW(5),
    resizeMode: 'contain',
  },
  txtInput: {
    flex: 1,
    justifyContent: 'center',
    fontSize: SF(13),
    top: 0,
    left: 5,
    color: COLORS.solid_grey,
  },
  selectAmountCon: {
    alignItems: 'center',
    justifyContent: 'center',
    width: SW(45),
    height: SH(50),
    borderWidth: 1,
    borderColor: COLORS.solidGrey,
    borderRadius: 5,
    marginRight: moderateScale(8),
  },
  selectAmountText: {
    fontFamily: Fonts.SemiBold,
    color: COLORS.solid_grey,
    fontSize: SF(15),
    color: COLORS.solid_grey,
  },
  selectAmountText2: {
    fontFamily: Fonts.SemiBold,
    color: COLORS.primary,
    fontSize: SF(15),
  },
  selectAmountCon2: {
    alignItems: 'center',
    justifyContent: 'center',
    width: SW(45),
    height: SH(50),
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 5,
    marginRight: moderateScale(8),
  },
  userNotFound: {
    color: COLORS.primary,
    fontFamily: Fonts.MaisonRegular,
    fontSize: SF(20),
    alignSelf: 'center',
  },
  addCashDrop: {
    flex: Platform.OS === 'android' ? 1 : 0,
  },
  dropDownPayment: {
    height: ms(4),
    width: ms(4),
    marginLeft: ms(5),
  },
  activeDropDownPayment: {
    height: ms(4),
    width: ms(4),
    marginLeft: ms(5),
    transform: [{ rotate: '180deg' }],
  },

  //New table style

  tableDataHeaderConNew: {
    height: SH(50),
    backgroundColor: COLORS.textInputBackground,
    textAlign: 'center',
    borderColor: COLORS.solidGrey,
    paddingHorizontal: moderateScale(10),
    justifyContent: 'center',
  },
  profileheaderUnderView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileheaderUnderData: {
    flexDirection: 'row',
    // marginLeft: ms(-10),
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileheaderChildView: {
    width: Platform.OS === 'android' ? SW(38) : ms(65),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: ms(3),
    // borderWidth: 1,
  },
  tableTextHeader: {
    color: COLORS.dark_grey,
    fontFamily: Fonts.MaisonBold,
    fontSize: SF(14),
  },
  tableTextDataFirst: {
    color: COLORS.solid_grey,
    fontFamily: Fonts.Regular,
    fontSize: SF(14),
    letterSpacing: -1,
    width: windowWidth * 0.02,
  },
  tableTextData: {
    color: COLORS.solid_grey,
    fontFamily: Fonts.Regular,
    fontSize: SF(14),
    marginStart: ms(10),
    alignSelf: 'center',
  },

  //Calendar

  calendarModalView: {
    backgroundColor: COLORS.white,
    width: windowWidth * 0.6,
    height: windowHeight - SW(30),
    alignSelf: 'center',
    paddingVertical: SH(10),
    paddingHorizontal: SW(5),
    borderRadius: SW(5),
  },
  loader: {
    position: 'absolute',
    alignSelf: 'center',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
  },

  // pagination table ui css
  jbrTypeCon: {
    backgroundColor: COLORS.textInputBackground,
    height: SH(55),
    justifyContent: 'center',
    paddingHorizontal: moderateScale(8),
  },
  jbrTypeConNew: {
    backgroundColor: COLORS.white,
    height: SH(55),
    justifyContent: 'center',
    paddingHorizontal: moderateScale(8),
  },
  paginationEnd: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  paginationCount: {
    fontSize: SF(14),
    fontFamily: Fonts.Regular,
    color: COLORS.black,
    paddingHorizontal: moderateScale(12),
  },
  dropDownIconPagination: {
    width: SW(4),
    height: SW(4),
    resizeMode: 'contain',
    tintColor: COLORS.darkGreen,
  },
  dropdown: {
    alignSelf: 'center',
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    zIndex: Platform.OS === 'ios' ? 100 : 0,
  },
  containerStylePagination: {
    width: SW(25),
    height: SH(35),
    justifyContent: 'center',
    borderWidth: 1,
    borderRadius: 3,
    borderColor: COLORS.solidGrey,
    backgroundColor: COLORS.white,
    color: COLORS.solidGrey,
  },
  dropDownContainerStyle: {
    borderWidth: 1,
    borderColor: COLORS.solidGrey,
    borderRadius: 7,
    ...ShadowStyles.shadow,
    backgroundColor: COLORS.white,
    top: Platform.OS === 'android' ? 30 : 35,
    zIndex: Platform.OS === 'ios' ? 100 : 1,
  },
  listItemLabelStyle: {
    fontSize: SF(12),
    fontFamily: Fonts.Regular,
  },
  labelStyle: {
    fontSize: SF(12),
    fontFamily: Fonts.Regular,
  },
  selectedItemLabelStyle: {
    fontSize: SF(12),
    fontFamily: Fonts.Regular,
  },
  placeholderStylePagination: {
    fontSize: SF(12),
    fontFamily: Fonts.Regular,
    color: COLORS.black,
  },

  unionCon: {
    backgroundColor: COLORS.washGrey,
    height: SH(40),
    justifyContent: 'center',
    borderRadius: 4,
    marginRight: 7,
  },
  unionStyle: {
    width: SW(5),
    height: SW(5),
    resizeMode: 'contain',
    paddingHorizontal: moderateScale(12),
  },
  paginationCount: {
    fontSize: SF(14),
    fontFamily: Fonts.Regular,
    color: COLORS.black,
    paddingHorizontal: moderateScale(12),
  },
  scnStyle: {
    width: SW(13),
    height: SW(14),
    resizeMode: 'contain',
  },
  invoiceContainer: {
    flex: 0.48,
    backgroundColor: COLORS.white,
    marginBottom: ms(10),
    right: SW(5),
    height: SH(700),
  },
});
