import { StyleSheet, Dimensions, Platform } from 'react-native';
import { SW, SH, SF, ShadowStyles } from '@/theme';
import { COLORS } from '@/theme';
import { Fonts } from '@/assets';
import { verticalScale, moderateScale, ms } from 'react-native-size-matters';

const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
    borderRadius: ms(15),
  },
  displayFlex: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  flexAlign: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  calenderContainer: {
    backgroundColor: COLORS.sky_grey,
    borderRadius: ms(15),
    flex: 1,
  },
  headerMainView: {
    width: windowWidth,
    paddingHorizontal: SW(16),
    alignSelf: 'center',
    justifyContent: 'space-between',
    paddingTop: SH(13),
    flexDirection: 'row',
  },
  textInputStyle: {
    height: SH(40),
    width: '100%',
    fontFamily: Fonts.Italic,
    fontSize: SF(12),
    paddingLeft: 5,
    margin: 0,
    padding: 0,
  },
  truckStyle: {
    width: SH(24),
    height: SH(24),
    resizeMode: 'contain',
  },
  deliveryView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  deliveryText: {
    fontFamily: Fonts.MaisonRegular,
    color: COLORS.solid_grey,
    fontSize: SF(18),
    paddingLeft: SW(4),
  },
  searchView: {
    borderWidth: 1,
    height: SH(40),
    borderRadius: 30,
    borderColor: COLORS.row_grey,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 10,
  },
  searchImage: {
    width: SH(20),
    height: SH(20),
    resizeMode: 'contain',
  },
  calenderCon: {
    flex: 1,
    borderRadius: ms(15),
    backgroundColor: COLORS.white,
    overflow: 'hidden',
  },
  notificationCon: {
    width: windowWidth * 0.34,
    height: '90%',
    position: 'absolute',
    top: ms(30),
    right: Platform.OS == 'ios' ? SW(40) : SW(30),
    borderRadius: ms(15),
    backgroundColor: COLORS.white,
    ...ShadowStyles.shadow4,
  },
  approveButtonCon: {
    backgroundColor: COLORS.primary,
    borderRadius: 3,
    height: SH(32),
    width: SH(110),
    justifyContent: 'center',
    alignItems: 'center',
  },
  noButtonCon: {
    backgroundColor: COLORS.dark_grey,
    borderRadius: 3,
    height: SH(32),
    justifyContent: 'center',
    alignItems: 'center',
    width: SH(110),
    marginLeft: moderateScale(10),
  },

  requestFor: {
    fontFamily: Fonts.Regular,
    color: COLORS.dark_grey,
    fontSize: SF(15),
    width: windowWidth * 0.25,
    overflow: 'hidden',
  },
  timeLabel: {
    fontFamily: Fonts.Regular,
    color: COLORS.dark_grey,
    fontSize: SF(15),
    paddingHorizontal: moderateScale(5),
  },
  notificationchildCon: {
    borderBottomWidth: 1,
    borderColor: '#F3F3F3',
    paddingHorizontal: moderateScale(8),
    paddingVertical: verticalScale(8),
  },
  roundCalender: {
    width: SH(22),
    height: SH(22),
    resizeMode: 'contain',
    tintColor: COLORS.bluish_green,
  },
  watch: {
    width: SH(18),
    height: SH(18),
    resizeMode: 'contain',
    tintColor: COLORS.bluish_green,
  },
  modalMainView: {
    backgroundColor: COLORS.white,
    width: SW(180),
    borderRadius: 12,
    alignSelf: 'center',
    justifyContent: 'center',
  },
  headerView: {
    backgroundColor: COLORS.primary,
    width: SW(180),
    height: SH(60),
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  crossIconStyle: {
    width: SH(24),
    height: SH(24),
    resizeMode: 'contain',
    tintColor: COLORS.white,
  },
  trackingButtonText: {
    fontFamily: Fonts.Medium,
    color: COLORS.white,
    fontSize: SF(12),
  },
  charlene: {
    width: SH(100),
    height: SH(100),
    resizeMode: 'contain',
    borderRadius: 100,
  },
  address: {
    fontFamily: Fonts.Regular,
    color: COLORS.darkGray,
    fontSize: SF(14),
    paddingHorizontal: moderateScale(5),
  },
  charleneName: {
    fontFamily: Fonts.Regular,
    color: COLORS.solid_grey,
    fontSize: SF(20),
  },
  location: {
    width: SH(16),
    height: SH(16),
    resizeMode: 'contain',
  },
  appointment: {
    fontFamily: Fonts.MaisonRegular,
    color: COLORS.primary,
    fontSize: SF(18),
  },
  service: {
    fontFamily: Fonts.SemiBold,
    color: COLORS.dark_grey,
    fontSize: SF(16),
  },
  serviceType: {
    fontFamily: Fonts.Regular,
    color: COLORS.dark_grey,
    fontSize: SF(14),
    marginRight: moderateScale(10),
  },
  upcomingCon: {
    borderRadius: 3,
    backgroundColor: COLORS.bluish_green,
    height: SH(35),
    width: SH(116),
    justifyContent: 'center',
    alignItems: 'center',
  },
  upcomingText: {
    fontFamily: Fonts.SemiBold,
    color: COLORS.white,
    fontSize: SF(16),
  },
  calenderHeader: {
    height: SH(60),
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    paddingHorizontal: ms(10),
    borderTopLeftRadius: ms(10),
    borderTopRightRadius: ms(10),
  },
  unChecked: {
    fontFamily: Fonts.Regular,
    color: COLORS.dark_grey,
    fontSize: SF(12),
    // paddingHorizontal:moderateScale(18)
  },
  clickedButtonCon: {
    backgroundColor: '#263682',
    height: SH(32),
    borderRadius: SH(16),
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    paddingHorizontal: ms(10),
  },
  unClickedButtonCon: {
    backgroundColor: COLORS.textInputBackground,
    height: SH(32),
    borderRadius: SH(16),
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    paddingHorizontal: ms(10),
  },
  checkedText: {
    fontFamily: Fonts.Regular,
    color: COLORS.white,
    fontSize: SF(12),
  },
  unCheckedText: {
    fontFamily: Fonts.Regular,
    color: COLORS.navy_blue,
    fontSize: SF(12),
  },
  schdule: {
    height: SH(670),
    width: windowWidth * 0.68,
    resizeMode: 'contain',
  },
  monthlySchduel: {
    height: SH(36),
    // width: SH(240),
    backgroundColor: COLORS.white,
    borderRadius: 3,
    paddingHorizontal: moderateScale(5),
    justifyContent: 'center',
    alignItems: 'center',
  },
  monthlySchduelNew: {
    backgroundColor: COLORS.white,
    borderRadius: 3,
    paddingHorizontal: moderateScale(5),
    justifyContent: 'center',
    alignItems: 'center',
  },
  leftLight: {
    width: SH(20),
    height: SH(20),
    resizeMode: 'contain',
  },
  monthlySchduleDate: {
    fontFamily: Fonts.Medium,
    color: '#263682',
    fontSize: SF(12),
    paddingHorizontal: moderateScale(5),
  },
  title1: {
    fontFamily: Fonts.SemiBold,
    color: '#263682',
    fontSize: SF(14),
    paddingHorizontal: moderateScale(5),
  },
  headerBody: {
    width: SW(170),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: moderateScale(10),
  },
  startEndDate: {
    color: COLORS.solid_grey,
    fontFamily: Fonts.SemiBold,
    fontSize: SH(10),
    // marginTop: ms(3),
  },
  eventContainer: {
    backgroundColor: 'white',
    elevation: 0,
    // borderLeftColor: COLORS.dark_grey,
    borderWidth: ms(0.5),
    borderStyle: 'solid',
    borderRadius: ms(4),
    padding: ms(2),
    // justifyContent: 'center',
  },
  eventTitle: {
    color: COLORS.dark_grey,
    fontFamily: Fonts.Regular,
    fontSize: ms(6),
  },
  iImageCon: {
    backgroundColor: COLORS.dark_grey,
    borderRadius: 100,
    height: SW(8),
    justifyContent: 'center',
    alignItems: 'center',
    width: SW(8),
  },
  iImage: {
    width: SW(5),
    height: SW(5),
    resizeMode: 'contain',
    tintColor: COLORS.white,
  },
  serviceTextCon: {
    flexDirection: 'row',
    width: windowWidth * 0.45,
  },
  requestTextName: {
    fontFamily: Fonts.SemiBold,
    color: COLORS.black,
    width: windowWidth * 0.5,
  },
  lockLight: {
    width: SW(5),
    height: SW(5),
    resizeMode: 'contain',
    paddingLeft: moderateScale(5),
  },
  requestNotFound: {
    fontFamily: Fonts.Regular,
    color: COLORS.primary,
    alignSelf: 'center',
    marginTop: 50,
    fontSize: SF(20),
  },
  arrowButtonStl: {
    // backgroundColor: COLORS.textInputBackground,
    borderRadius: ms(2),
    paddingHorizontal: ms(3),
    paddingVertical: ms(2),
  },
  rightTabContainer: {
    backgroundColor: COLORS.white,
    borderRadius: ms(20),
    width: ms(50),
    margin: ms(7),
    paddingVertical: ms(10),
    marginVertical: 0,
    marginLeft: ms(10),
    alignItems: 'center',
  },
  RequestEventBadgeText: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(7),
    color: COLORS.white,
  },
  requestEventBadgeContainer: {
    height: ms(12),
    width: ms(12),
    borderRadius: ms(6),
    backgroundColor: COLORS.alert_red,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    right: ms(-5),
    bottom: ms(-5),
  },
  requestCalendarIcon: {
    height: ms(20),
    width: ms(20),
    resizeMode: 'contain',
    tintColor: COLORS.navy_blue,
  },
  requestCalendarIconSmall: {
    height: ms(18),
    width: ms(18),
    resizeMode: 'contain',
    tintColor: COLORS.navy_blue,
  },
  requestCountView: {
    height: ms(15),
    width: ms(15),
    backgroundColor: COLORS.alert_red,
    borderRadius: ms(7.5),
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: ms(5),
  },
  requestCalendarContainer: {
    height: ms(36),
    width: ms(36),
    marginTop: ms(5),
    borderRadius: ms(12),
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeTextEmployee: {
    fontFamily: Fonts.Medium,
    fontSize: ms(6),
    color: COLORS.white,
  },
  circularBadgeEmployee: {
    position: 'absolute',
    right: ms(-3),
    bottom: ms(-4),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.success_green,
    borderWidth: 3,
    borderColor: 'teal',
    height: ms(15),
    width: ms(15),
    borderRadius: ms(7.5),
    borderColor: COLORS.white,
  },
  employeeImages: {
    height: ms(24),
    width: ms(24),
    borderRadius: ms(24),
    resizeMode: 'cover',
  },
  staticEmployeeImages: {
    height: ms(21),
    width: ms(21),
    borderRadius: ms(21),
    resizeMode: 'cover',
  },
  renderItemContainer: {
    height: ms(28),
    width: ms(28),
    borderRadius: ms(2),
    alignItems: 'center',
    justifyContent: 'center',
    margin: ms(2),
  },
  asigneesBadgeText: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(6),
    color: COLORS.dark_grey,
    alignItems: 'center',
  },
  circularBadgeContainer: {
    height: ms(10),
    width: ms(10),
    borderRadius: ms(5),
    backgroundColor: COLORS.white,
    borderWidth: 1.5,
    borderColor: COLORS.dark_grey,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    right: ms(5),
    bottom: ms(5),
  },
  asignessCalendarImage: {
    height: ms(14),
    width: ms(14),
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  alignmentCalendarContainer: {
    alignSelf: 'center',
    justifyContent: 'center',
    marginVertical: ms(10),
    borderRadius: ms(3),
    height: ms(35),
    width: ms(35),
  },
  calendarIconSettings: {
    height: ms(20),
    width: ms(20),
    resizeMode: 'contain',
  },
  CalendarSettingsContainer: {
    // position: 'absolute',
    height: ms(40),
    width: '95%',
    alignSelf: 'center',
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  _calendarContainer: {
    flex: 1,
    borderRightColor: COLORS.white,
  },
  _eventTitle: {
    fontFamily: Fonts.Medium,
    fontSize: ms(8.5),
    color: COLORS.navy_blue,
  },
  _eventHeading: {
    fontFamily: Fonts.Medium,
    fontSize: ms(8.5),
    color: COLORS.faded_purple,
  },
  _eventTitleBold: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(8.5),
    color: COLORS.navy_blue,
  },
  _eventHeadingBold: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(8.5),
    color: COLORS.faded_purple,
  },
  invoiceText: {
    fontFamily: Fonts.Medium,
    fontSize: ms(7),
    color: COLORS.dark_skyblue,
    marginTop: ms(2),
  },
  lineStl: {
    height: ms(8),
    width: 1,
    backgroundColor: COLORS.gerySkies,
    marginHorizontal: ms(10),
  },
  eventItemContainer: {
    borderRadius: ms(16),
    marginHorizontal: ms(8),
    marginTop: ms(5),
    borderWidth: 1,
    overflow: 'hidden',
    paddingHorizontal: ms(10),
  },
  approveText: {
    fontFamily: Fonts.Regular,
    fontSize: ms(8),
    color: COLORS.white,
  },
  acceptbtnContainer: {
    height: ms(25),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.primary,
    flex: 1,
    borderRadius: ms(3),
    marginLeft: ms(8),
  },

  declineBtnContainer: {
    height: ms(25),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.textInputBackground,
    flex: 1,
    borderRadius: ms(3),
  },
  _btnContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: ms(10),
  },
  paidText: {
    fontFamily: Fonts.Regular,
    color: COLORS.navy_blue,
    fontSize: ms(8),
  },
  paidContainer: {
    backgroundColor: COLORS.white,
    paddingHorizontal: ms(10),
    borderRadius: ms(30),
    marginTop: ms(3),
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    height: ms(20),
  },
  totalTile: {
    fontFamily: Fonts.Medium,
    fontSize: ms(8),
    color: COLORS.navy_blue,
  },
  serviceChargeSub: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '20%',
    marginTop: ms(5),
  },
  duractiontxt: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(7),
    marginLeft: ms(4),
    color: COLORS.black,
  },
  duractionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: ms(10),
  },
  eventDate: {
    fontFamily: Fonts.Regular,
    fontSize: ms(6),
    color: COLORS.solid_grey,
  },
  eventDay: {
    fontFamily: Fonts.Regular,
    fontSize: ms(6),
    color: COLORS.solid_grey,
    marginLeft: ms(8),
  },
  evenclockIcon: { height: ms(10), width: ms(10), resizeMode: 'contain' },
  serviceTimeContainer: {
    borderWidth: 1,
    padding: ms(3),
    borderRadius: ms(3),
    borderColor: COLORS.textInputBackground,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: ms(5),
  },
  subContainer1: {
    marginHorizontal: ms(10),
    marginTop: ms(10),
    marginBottom: 20,
  },
  hairCutTitle: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(9),
    color: COLORS.black,
  },
  eventAddress: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(6),
    color: COLORS.purple,
    marginTop: ms(2),
  },
  eventAddressIcon: {
    height: ms(10),
    width: ms(10),
    resizeMode: 'contain',
    tintColor: COLORS.purple,
  },
  customerName: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(8),
    color: COLORS.navy_blue,
  },
  customerUserProfile: {
    height: ms(24),
    width: ms(24),
    resizeMode: 'cover',
    borderRadius: ms(12),
  },
  customerDetailContainer: {
    paddingHorizontal: ms(10),
    // borderColor: COLORS.light_purple,
    // borderWidth: 1,
    paddingVertical: ms(5),
    borderRadius: ms(16),
  },
  customerDetailContainerBorder: {
    paddingHorizontal: ms(10),
    borderColor: COLORS.light_purple,
    borderWidth: 1,
    paddingVertical: ms(5),
    borderRadius: ms(16),
  },
  _requestTitle: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(10),
    color: COLORS.dark_grey,
    marginLeft: ms(8),
    marginVertical: ms(8),
  },
  subtotalContainers: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: ms(3),
  },
  invoiceTxt: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(7),
    marginVertical: ms(5),
  },
  amountSliptContainer: {
    marginHorizontal: ms(5),
  },
  assignedContainer: {
    backgroundColor: COLORS.white,
    margin: ms(10),
    marginTop: ms(2),
    borderRadius: ms(5),
    paddingHorizontal: ms(8),
    marginBottom: ms(20),
  },
  chatIconStl: { height: ms(15), width: ms(15), resizeMode: 'contain' },
  eventDetailModalContainer: {
    width: ms(290),
    height: ms(380),
    backgroundColor: 'white',
    paddingHorizontal: ms(10),
    paddingVertical: ms(10),
    alignSelf: 'center',
    borderRadius: ms(10),
  },
  crossStl: { height: ms(18), width: ms(18), tintColor: COLORS.black, alignSelf: 'center' },
  crossEventDetailModal: { position: 'absolute', right: ms(8), top: ms(6) },
  profilePicContainer: {
    height: ms(12),
    width: ms(12),
    borderRadius: ms(6),
    borderWidth: ms(1),
    borderColor: `#A179F2`,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  eventProfilePic: { height: ms(12), width: ms(12), resizeMode: 'cover' },
  headerEmployeeDesignation: {
    fontFamily: Fonts.Regular,
    fontSize: ms(5),
    color: COLORS.black,
  },
  headerEmployeeName: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(6),
    color: COLORS.black,
  },
  headerEmployeeImage: {
    height: ms(17),
    width: ms(17),
    borderRadius: ms(17),
    borderWidth: 2,
    borderColor: 'teal',
  },
  headerEmployeeCard: {
    padding: ms(5),
    marginHorizontal: ms(1),
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    borderWidth: 1,
    borderRadius: ms(20),
    paddingHorizontal: ms(5),
  },
  headerScrollContainer: {
    backgroundColor: COLORS.white,
    flexGrow: 1,
    paddingLeft: ms(25),
  },
  editOptionIcon: {
    height: ms(14),
    width: ms(14),
    resizeMode: 'contain',
    tintColor: COLORS.navy_blue,
    left: ms(5),
  },
  cancelOptionIcon: { height: ms(12), width: ms(12), resizeMode: 'contain', marginRight: ms(7) },
  EventDetailoptionsContainer: {
    width: ms(40),
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
  },

  //New Reschedule Modal
  addCartCon: {
    backgroundColor: 'white',
    borderRadius: ms(10),
    width: windowWidth * 0.45,
    // paddingBottom: ms(15),
    paddingTop: ms(5),
    alignSelf: 'flex-end',
    height: ms(380),
  },
  addCartConHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: ms(5),
    paddingHorizontal: ms(10),
    // borderBottomWidth: 1,
    // borderColor: COLORS.solidGrey,
    justifyContent: 'space-between',
  },
  crossBg: {
    width: SW(10),
    height: SW(8),
    resizeMode: 'contain',
  },
  continueBtnCon: {
    height: ms(30),
    padding: SH(10),
    width: '45%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 30,
    borderColor: COLORS.red,
    borderWidth: 1,
    backgroundColor: 'transparent',
  },
  addToCartCon: {
    width: '45%',
  },
  detailBtnCon: {
    color: COLORS.red,
    fontSize: ms(8),
    fontFamily: Fonts.Regular,
    fontWeight: '600',
  },
  addTocartText: {
    color: COLORS.white,
    fontSize: ms(8),
    fontFamily: Fonts.Regular,
    fontWeight: '600',
  },
  displayRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  colorRow: {
    height: SH(2),
    width: windowWidth * 0.17,
    backgroundColor: '#D8D8D8',
  },
  serviceRow: {
    flex: 1,
  },
  colorText: {
    marginHorizontal: SH(10),
    fontSize: ms(11),
    fontFamily: Fonts.Regular,
    color: COLORS.gerySkies,
  },
  selected: {
    fontSize: ms(8),
    fontFamily: Fonts.SemiBold,
    color: COLORS.solid_grey,
  },
  calendarIcon: {
    height: ms(15),
    width: ms(15),
    resizeMode: 'contain',
    tintColor: COLORS.navy_blue,
  },
  bookedCalendarIcon: {
    height: ms(10),
    width: ms(10),
    resizeMode: 'contain',
    tintColor: COLORS.sky_blue,
  },

  messageSend: {
    height: ms(25),
    width: ms(25),
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  attachIcon: {
    height: ms(18),
    width: ms(18),
    resizeMode: 'contain',
    alignSelf: 'center',
    marginHorizontal: ms(5),
  },
  messagesContainerStyle: {
    paddingBottom: ms(10),
  },
  checkinContainer: {
    flex: 1,
    borderRadius: ms(3),
    padding: ms(15),
    width: 'auto',
    backgroundColor: COLORS.primary,
    paddingVertical: ms(10),
  },
  checkintitle: { color: COLORS.white, fontFamily: Fonts.Regular },
  editTextBtn: { fontFamily: Fonts.SemiBold, fontSize: ms(8), color: COLORS.navy_blue },
  btmEditBtn: {
    flex: 1,
    borderWidth: 1,
    borderRadius: ms(3),
    padding: ms(15),
    paddingVertical: ms(7),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomBtnContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: ms(14),
    marginTop: ms(10),
    alignSelf: 'center',
  },
  cellRoot: {
    backgroundColor: COLORS.textInputBackground,
    height: moderateScale(30),
    width: moderateScale(30),
    borderRadius: moderateScale(15),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.solidGrey,
    marginHorizontal: moderateScale(6),
  },
  cellText: {
    fontFamily: Fonts.Medium,
    fontSize: ms(15),
    color: COLORS.black,
  },
  staffNameText: {
    fontFamily: Fonts.Medium,
    fontSize: ms(7),
    color: COLORS.navy_blue,
  },
  occupationText: {
    fontFamily: Fonts.Medium,
    fontSize: ms(7),
    color: COLORS.lavender,
  },
  requestText: {
    fontFamily: Fonts.Regular,
    fontSize: ms(8),
    color: COLORS.white,
  },
  alignSelfCenter: {
    alignSelf: 'center',
  },
  confirmCheckinOtpBtn: {
    marginTop: ms(10),
    width: 'auto',
    backgroundColor: COLORS.primary,
    padding: ms(10),
    paddingHorizontal: ms(40),
  },
  verifyOtpContainer: {
    borderWidth: 1,
    borderRadius: ms(5),
    backgroundColor: COLORS.inputBorder,
    width: '35%',
    paddingVertical: ms(20),
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  LheaderText: {
    flex: 0.2,
    fontSize: ms(8),
    fontFamily: Fonts.Medium,
    marginVertical: ms(5),
    textAlign: 'center',
    color: COLORS.lavender,
  },
  LlistViewHeaderContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginLeft: ms(5),
    flex: 1,
  },
  listViewSubContainers: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flex: 0.2,
    marginLeft: ms(2),
    alignItems: 'center',
    justifyContent: 'center',
  },
  deviderList: { height: 1, width: '100%', backgroundColor: COLORS.solidGrey },
  listViewEditIcon: { height: ms(12), width: ms(12), resizeMode: 'contain' },
  listViewEditBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.sky_grey,
    marginLeft: ms(8),
    padding: ms(5),
    borderRadius: ms(12.5),
    height: ms(25),
    width: ms(25),
  },
  listViewCheckinBtn: {
    width: 'auto',
    borderColor: COLORS.primary,
    borderWidth: 1,
    paddingVertical: ms(5),
    paddingHorizontal: ms(8),
    backgroundColor: COLORS.white,
  },
  listCheckinBtnText: {
    color: COLORS.primary,
    fontFamily: Fonts.Regular,
    fontSize: ms(7),
    fontWeight: '500',
  },
  lineViewValues: { fontFamily: Fonts.Medium, fontSize: ms(8.5), color: COLORS.textBlue },
  noAppointmentEmpty: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(11),
    alignSelf: 'center',
    margin: ms(20),
  },
  calendarModalView: {
    backgroundColor: COLORS.white,
    width: windowWidth * 0.3,
    height: Platform.OS == 'ios' ? windowHeight - SW(150) : windowHeight - SW(120),
    alignSelf: 'flex-start',
    // paddingVertical: SH(10),
    paddingHorizontal: SW(5),
    borderRadius: SW(5),
    borderWidth: 1,
    borderColor: COLORS.graySky,
  },
  closeImageSearchBtn: { height: ms(20), width: ms(20) },
  closeSearchBtn: { position: 'absolute', top: ms(5), right: ms(7) },
  searchAppointmentModalContainer: {
    marginHorizontal: ms(40),
    marginVertical: ms(40),
    backgroundColor: 'white',
    borderRadius: ms(5),
    paddingHorizontal: ms(20),
    paddingVertical: ms(20),
    minHeight: '70%',
  },
  cancelSavebtnReschedule: {
    flex: 1,
    flexDirection: 'row',
    marginTop: ms(10),
    marginHorizontal: ms(26),
    alignSelf: 'center',
    marginBottom: ms(10),
  },
  row: {
    flexDirection: 'row',
  },
  rowHorizonCenter: {
    alignItems: 'center',
  },
  buttonCalender: {
    borderWidth: ms(0.8),
    borderColor: '#D7DEFF',
    borderRadius: ms(50),
    paddingVertical: ms(2),
    paddingHorizontal: ms(6),
  },
  arrowDown: {
    width: SH(16),
    height: SH(16),
    resizeMode: 'contain',
  },
  calenderModeIcons: {
    width: SH(16),
    height: SH(16),
    resizeMode: 'contain',
  },
  calenderModeView: {
    backgroundColor: COLORS.textInputBackground,
    height: SH(32),
    borderRadius: SH(16),
    justifyContent: 'center',
    alignItems: 'center',
  },
  _listViewItemContainer2: {
    marginVertical: ms(5),
    borderWidth: 1,
    padding: ms(10),
    borderRadius: ms(22),
    borderColor: COLORS.sky_grey,
    alignItems: 'center',
    marginHorizontal: ms(5),
  },
  _mListViewDate: { fontFamily: Fonts.Medium, fontSize: ms(12), color: COLORS.light_blue2 },
  _mListViewDayName: { fontFamily: Fonts.Medium, fontSize: ms(20), color: COLORS.navy_blue },
  _mListViewDateHeaderContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginVertical: ms(10),
  },
  totalUsersCountContainer: {
    position: 'absolute',
    height: ms(14),
    width: ms(14),
    borderRadius: ms(14),
    borderWidth: 2,
    backgroundColor: COLORS.success_green,
    borderColor: COLORS.white,
    right: ms(-3),
    bottom: ms(-5),
    justifyContent: 'center',
    alignItems: 'center',
  },
  countUsers: {
    color: COLORS.white,
    fontFamily: Fonts.Regular,
    fontSize: ms(7),
  },
  usersIconView: {
    marginBottom: ms(1),
    borderWidth: 1,
    borderRadius: ms(50),
    borderColor: COLORS.light_purple,
    padding: ms(3),
  },
  usersIconStyle: {
    height: ms(18),
    width: ms(18),
  },
  checkInModalContainer: {
    width: ms(300),
    paddingVertical: ms(20),
    backgroundColor: 'white',
    alignItems: 'center',
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.29,
    shadowRadius: 4.65,
    elevation: 7,
    borderRadius: ms(15),
  },
  checkInIcon: {
    height: ms(35),
    width: ms(35),
    resizeMode: 'contain',
    tintColor: COLORS.sky_blue,
  },
  checkInText: {
    fontSize: ms(14),
    color: COLORS.navy_blue,
    fontFamily: Fonts.SemiBold,
    marginTop: ms(10),
  },
  subHeadingText: {
    fontSize: ms(11),
    color: COLORS.faded_purple,
    fontFamily: Fonts.Regular,
    marginTop: ms(10),
  },
  serviceDetailContainer: {
    borderWidth: 0.5,
    borderColor: COLORS.light_purple,
    borderRadius: ms(15),
    padding: ms(10),
    marginVertical: ms(10),
    width: '92%',
  },
  rowJustified: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  customerText: {
    fontSize: ms(10),
    color: COLORS.navy_blue,
    fontFamily: Fonts.Medium,
  },
  unpaidText: {
    fontSize: ms(9),
    color: COLORS.navy_blue,
    fontFamily: Fonts.Medium,
  },
  customerProfileView: {
    marginTop: ms(10),
    flexDirection: 'row',
    alignItems: 'center',
  },
  customerProfileImage: {
    height: ms(35),
    width: ms(35),
  },
  customerNameText: {
    fontSize: ms(11),
    color: COLORS.navy_blue,
    fontFamily: Fonts.Medium,
  },
  rowAligned: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  rowAlignedJustified: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  addressText: {
    fontSize: ms(9),
    color: COLORS.purple,
    fontFamily: Fonts.Medium,
    marginLeft: ms(5),
  },
  requestedServicesView: {
    marginTop: ms(10),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  servicesRequested: {
    fontSize: ms(8),
    color: COLORS.navy_blue,
    fontFamily: Fonts.Medium,
  },
  scrollableServicesView: {
    backgroundColor: COLORS.sky_blue,
    margin: ms(5),
    padding: ms(3),
    borderRadius: ms(15),
  },
  servicesName: {
    fontFamily: Fonts.Medium,
    color: COLORS.white,
    fontSize: ms(7.5),
  },
  closeIcon: {
    height: ms(20),
    width: ms(20),
    tintColor: COLORS.navy_blue,
  },
  closeIconSmall: {
    height: ms(16),
    width: ms(16),
    tintColor: COLORS.navy_blue,
  },
  closeIconView: {
    position: 'absolute',
    top: ms(10),
    right: ms(15),
  },
  serviceTimeView: {
    marginTop: ms(5),
  },
  serviceTimeIcons: {
    height: ms(11),
    width: ms(11),
    tintColor: COLORS.navy_blue,
  },
  serviceTimeText: {
    color: COLORS.navy_blue,
    fontFamily: Fonts.Medium,
    fontSize: ms(7),
    left: ms(3),
  },
  serviceTimeTextSmall: {
    color: COLORS.navy_blue,
    fontFamily: Fonts.Medium,
    fontSize: ms(6),
    left: ms(3),
  },
  dashedLine: {
    width: '100%',
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: COLORS.lavender,
    marginVertical: ms(13),
  },
  totalPrice: {
    color: COLORS.navy_blue,
    fontFamily: Fonts.SemiBold,
    fontSize: ms(9),
  },
  declineButtonStyle: {
    width: '42%',
    height: ms(33),
    backgroundColor: COLORS.white,
    borderColor: COLORS.navy_blue,
    borderRadius: ms(30),
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modifyButtonStyle: {
    width: '42%',
    height: ms(33),
    backgroundColor: COLORS.white,
    borderColor: COLORS.navy_blue,
    borderRadius: ms(30),
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  acceptButtonStyle: {
    width: '42%',
    height: ms(33),
    backgroundColor: COLORS.navy_blue,
    borderRadius: ms(30),
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  declineText: {
    fontFamily: Fonts.Regular,
    fontSize: ms(8),
    color: COLORS.navy_blue,
  },
  acceptText: {
    fontFamily: Fonts.Regular,
    fontSize: ms(9),
    color: COLORS.white,
  },
  modalHeading: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(9),
    color: COLORS.navy_blue,
  },
  rightArrowStyle: {
    tintColor: COLORS.sky_blue,
    height: ms(16),
    width: ms(16),
  },
  checkStyle: {
    height: ms(10),
    width: ms(10),
  },
  appointmentDateContainer: {
    height: ms(20),
    paddingHorizontal: ms(5),
    borderRadius: ms(20),
    backgroundColor: COLORS.light_sky_blue,
    borderColor: COLORS.sky_blue,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookedDate: {
    fontFamily: Fonts.Regular,
    fontSize: ms(7),
    color: COLORS.sky_blue,
  },
  imageSelectedBorder: {
    borderWidth: 2,
    marginHorizontal: ms(5),
    borderRadius: 30,
    borderColor: COLORS.primary,
  },
  staffInfoContainer: {
    borderWidth: 1,
    paddingHorizontal: ms(10),
    borderRadius: ms(20),
    height: ms(33),
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: ms(3),
    backgroundColor: COLORS.white,
    marginBottom: 3,
  },
  staffProfilePic: {
    width: ms(25),
    height: ms(25),
    borderRadius: ms(25),
    borderWidth: 2,
    borderColor: COLORS.input_border,
  },
});
