export const TYPES = {
  GET_ORDER_DATA: "GET_ORDER_DATA",
  GET_ORDER_DATA_REQUEST: "GET_ORDER_DATA_REQUEST",
  GET_ORDER_DATA_SUCCESS: "GET_ORDER_DATA_SUCCESS",
  GET_ORDER_DATA_ERROR: "GET_ORDER_DATA_ERROR",

  GET_ANALYTIC_STATISTICS: "GET_ANALYTIC_STATISTICS",
  GET_ANALYTIC_STATISTICS_REQUEST: "GET_ANALYTIC_STATISTICS_REQUEST",
  GET_ANALYTIC_STATISTICS_SUCCESS: "GET_ANALYTIC_STATISTICS_SUCCESS",
  GET_ANALYTIC_STATISTICS_ERROR: "GET_ANALYTIC_STATISTICS_ERROR",

  GET_ANALYTIC_ORDER_GRAPHS: "GET_ANALYTIC_ORDER_GRAPHS",
  GET_ANALYTIC_ORDER_GRAPHS_REQUEST: "GET_ANALYTIC_ORDER_GRAPHS_REQUEST",
  GET_ANALYTIC_ORDER_GRAPHS_SUCCESS: "GET_ANALYTIC_ORDER_GRAPHS_SUCCESS",
  GET_ANALYTIC_ORDER_GRAPHS_ERROR: "GET_ANALYTIC_ORDER_GRAPHS_ERROR",

  GET_TOTAL_ORDER: "GET_TOTAL_ORDER",
  GET_TOTAL_ORDER_REQUEST: "GET_TOTAL_ORDER_REQUEST",
  GET_TOTAL_ORDER_SUCCESS: "GET_TOTAL_ORDER_SUCCESS",
  GET_TOTAL_ORDER_ERROR: "GET_TOTAL_ORDER_ERROR",

  GET_TOTAL_INVENTORY: "GET_TOTAL_INVENTORY",
  GET_TOTAL_INVENTORY_REQUEST: "GET_TOTAL_INVENTORY_REQUEST",
  GET_TOTAL_INVENTORY_SUCCESS: "GET_TOTAL_INVENTORY_SUCCESS",
  GET_TOTAL_INVENTORY_ERROR: "GET_TOTAL_INVENTORY_ERROR",

  GET_SOLD_PRODUCT: "GET_SOLD_PRODUCT",
  GET_SOLD_PRODUCT_REQUEST: "GET_SOLD_PRODUCT_REQUEST",
  GET_SOLD_PRODUCT_SUCCESS: "GET_SOLD_PRODUCT_SUCCESS",
  GET_SOLD_PRODUCT_ERROR: "GET_SOLD_PRODUCT_ERROR",
};
