export const DELIVERY_TYPES = {
  TODAY_ORDER_STATUS: "TODAY_ORDER_STATUS",
  TODAY_ORDER_STATUS_REQUEST: "TODAY_ORDER_STATUS_REQUEST",
  TODAY_ORDER_STATUS_SUCCESS: "TODAY_ORDER_STATUS_SUCCESS",
  TODAY_ORDER_STATUS_ERROR: "TODAY_ORDER_STATUS_ERROR",
  TODAY_ORDER_STATUS_RESET: "TODAY_ORDER_STATUS_RESET",

  GET_DELIVERY_TYPES_ORDERS: "GET_DELIVERY_TYPES_ORDERS",
  GET_DELIVERY_TYPES_ORDERS_REQUEST: "GET_DELIVERY_TYPES_ORDERS_REQUEST",
  GET_DELIVERY_TYPES_ORDERS_SUCCESS: "GET_DELIVERY_TYPES_ORDERS_SUCCESS",
  GET_DELIVERY_TYPES_ORDERS_ERROR: "GET_DELIVERY_TYPES_ORDERS_ERROR",
  GET_DELIVERY_TYPES_ORDERS_RESET: "GET_DELIVERY_TYPES_ORDERS_RESET",

  GET_ORDERS: "GET_ORDERS",
  GET_ORDERS_REQUEST: "GET_ORDERS_REQUEST",
  GET_ORDERS_SUCCESS: "GET_ORDERS_SUCCESS",
  GET_ORDERS_ERROR: "GET_ORDERS_ERROR",
  GET_ORDERS_RESET: "GET_ORDERS_RESET",

  GET_GRAPH_ORDERS: "GET_GRAPH_ORDERS",
  GET_GRAPH_ORDERS_REQUEST: "GET_GRAPH_ORDERS_REQUEST",
  GET_GRAPH_ORDERS_SUCCESS: "GET_GRAPH_ORDERS_SUCCESS",
  GET_GRAPH_ORDERS_ERROR: "GET_GRAPH_ORDERS_ERROR",

  GET_ORDER_STATISTICS: "GET_ORDER_STATISTICS",
  GET_ORDER_STATISTICS_REQUEST: "GET_ORDER_STATISTICS_REQUEST",
  GET_ORDER_STATISTICS_SUCCESS: "GET_ORDER_STATISTICS_SUCCESS",
  GET_ORDER_STATISTICS_ERROR: "GET_ORDER_STATISTICS_ERROR",

  GET_ORDER_COUNT: "GET_ORDER_COUNT",
  GET_ORDER_COUNT_REQUEST: "GET_ORDER_COUNT_REQUEST",
  GET_ORDER_COUNT_SUCCESS: "GET_ORDER_COUNT_SUCCESS",
  GET_ORDER_COUNT_ERROR: "GET_ORDER_COUNT_ERROR",

  ACCEPT_ORDER_REQUEST: "ACCEPT_ORDER_REQUEST",
  ACCEPT_ORDER_SUCCESS: "ACCEPT_ORDER_SUCCESS",
  ACCEPT_ORDER_ERROR: "ACCEPT_ORDER_ERROR",
  ACCEPT_ORDER: "ACCEPT_ORDER",
};
