export const RETAIL_TYPES = {
  GET_PRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  GET_PRODUCT_ERROR: "GET_PRODUCT_ERROR",
  GET_PRODUCT_RESET: "GET_PRODUCT_RESET",
  GET_PRODUCT: "GET_PRODUCT",

  GET_ONE_PRODUCT_REQUEST: "GET_ONE_PRODUCT_REQUEST",
  GET_ONE_PRODUCT_SUCCESS: "GET_ONE_PRODUCT_SUCCESS",
  GET_ONE_PRODUCT_ERROR: "GET_ONE_PRODUCT_ERROR",
  GET_ONE_PRODUCT_RESET: "GET_ONE_PRODUCT_RESET",
  GET_ONE_PRODUCT: "GET_ONE_PRODUCT",

  ADD_PRODUCT_CART_REQUEST: "ADD_PRODUCT_CART_REQUEST",
  ADD_PRODUCT_CART_SUCCESS: "ADD_PRODUCT_CART_SUCCESS",
  ADD_PRODUCT_CART_ERROR: "ADD_PRODUCT_CART_ERROR",
  ADD_PRODUCT_CART: "ADD_PRODUCT_CART",

  CHECK_SUPPLIES_VARIANT_REQUEST: "CHECK_SUPPLIES_VARIANT_REQUEST",
  CHECK_SUPPLIES_VARIANT_SUCCESS: "CHECK_SUPPLIES_VARIANT_SUCCESS",
  CHECK_SUPPLIES_VARIANT_ERROR: "CHECK_SUPPLIES_VARIANT_ERROR",
  CHECK_SUPPLIES_VARIANT_RESET: "CHECK_SUPPLIES_VARIANT_RESET",
  CHECK_SUPPLIES_VARIANT: "CHECK_SUPPLIES_VARIANT",

  GET_PRODUCT_CART_REQUEST: "GET_PRODUCT_CART_REQUEST",
  GET_PRODUCT_CART_SUCCESS: "GET_PRODUCT_CART_SUCCESS",
  GET_PRODUCT_CART_ERROR: "GET_PRODUCT_CART_ERROR",
  GET_PRODUCT_CART_RESET: "GET_PRODUCT_CART_RESET",
  GET_PRODUCT_CART: "GET_PRODUCT_CART",

  CLEAR_PRODUCT_CART_REQUEST: "CLEAR_PRODUCT_CART_REQUEST",
  CLEAR_PRODUCT_CART_SUCCESS: "CLEAR_PRODUCT_CART_SUCCESS",
  CLEAR_PRODUCT_CART_ERROR: "CLEAR_PRODUCT_CART_ERROR",
  CLEAR_PRODUCT_CART_RESET: "CLEAR_PRODUCT_CART_RESET",
  CLEAR_PRODUCT_CART: "CLEAR_PRODUCT_CART",
};
