export const SHIPPING_TYPES = {
  TODAY_SHIPPING_STATUS: "TODAY_SHIPPING_STATUS",
  TODAY_SHIPPING_STATUS_REQUEST: "TODAY_SHIPPING_STATUS_REQUEST",
  TODAY_SHIPPING_STATUS_SUCCESS: "TODAY_SHIPPING_STATUS_SUCCESS",
  TODAY_SHIPPING_STATUS_ERROR: "TODAY_SHIPPING_STATUS_ERROR",

  TODAY_CURRENT_STATUS: "TODAY_CURRENT_STATUS",
  TODAY_CURRENT_STATUS_REQUEST: "TODAY_CURRENT_STATUS_REQUEST",
  TODAY_CURRENT_STATUS_SUCCESS: "TODAY_CURRENT_STATUS_SUCCESS",
  TODAY_CURRENT_STATUS_ERROR: "TODAY_CURRENT_STATUS_ERROR",

  GET_ORDERS: "GET_ORDERS",
  GET_ORDERS_REQUEST: "GET_ORDERS_REQUEST",
  GET_ORDERS_SUCCESS: "GET_ORDERS_SUCCESS",
  GET_ORDERS_ERROR: "GET_ORDERS_ERROR",
  GET_ORDERS_RESET: "GET_ORDERS_RESET",

  GET_GRAPH_ORDERS: "GET_GRAPH_ORDERS",
  GET_GRAPH_ORDERS_REQUEST: "GET_GRAPH_ORDERS_REQUEST",
  GET_GRAPH_ORDERS_SUCCESS: "GET_GRAPH_ORDERS_SUCCESS",
  GET_GRAPH_ORDERS_ERROR: "GET_GRAPH_ORDERS_ERROR",

  GET_ORDER_STATISTICS: "GET_ORDER_STATISTICS",
  GET_ORDER_STATISTICS_REQUEST: "GET_ORDER_STATISTICS_REQUEST",
  GET_ORDER_STATISTICS_SUCCESS: "GET_ORDER_STATISTICS_SUCCESS",
  GET_ORDER_STATISTICS_ERROR: "GET_ORDER_STATISTICS_ERROR",

  GET_ORDER_COUNT: "GET_ORDER_COUNT",
  GET_ORDER_COUNT_REQUEST: "GET_ORDER_COUNT_REQUEST",
  GET_ORDER_COUNT_SUCCESS: "GET_ORDER_COUNT_SUCCESS",
  GET_ORDER_COUNT_ERROR: "GET_ORDER_COUNT_ERROR",

  ORDER_STATUS_COUNT: "ORDER_STATUS_COUNT",
  ORDER_STATUS_COUNT_REQUEST: "ORDER_STATUS_COUNT_REQUEST",
  ORDER_STATUS_COUNT_SUCCESS: "ORDER_STATUS_COUNT_SUCCESS",
  ORDER_STATUS_COUNT_ERROR: "ORDER_STATUS_COUNT_ERROR",

  GET_ORDER_DETAIL: "GET_ORDER_DETAIL",
  GET_ORDER_DETAIL_REQUEST: "GET_ORDER_DETAIL_REQUEST",
  GET_ORDER_DETAIL_SUCCESS: "GET_ORDER_DETAIL_SUCCESS",
  GET_ORDER_DETAIL_ERROR: "GET_ORDER_DETAIL_ERROR",

  ACCEPT_ORDER_REQUEST: "ACCEPT_ORDER_REQUEST",
  ACCEPT_ORDER_SUCCESS: "ACCEPT_ORDER_SUCCESS",
  ACCEPT_ORDER_ERROR: "ACCEPT_ORDER_ERROR",
  ACCEPT_ORDER: "ACCEPT_ORDER",
};
