export const TYPES = {
  CLEAR_STORE: "CLEAR_STORE",
  MERCHAT_CLEAR_STORE: "MERCHAT_CLEAR_STORE",
  LOGIN_POS: "LOGIN_POS",
  LOGIN_POS_REQUEST: "LOGIN_POS_REQUEST",
  LOGIN_POS_SUCCESS: "LOGIN_POS_SUCCESS",
  LOGIN_POS_ERROR: "LOGIN_POS_ERROR",
  SHOW_SESSION: "SHOW_SESSION",

  SAVE_PHONE: "SAVE_PHONE",
  VERIFY_PHONE: "VERIFY_PHONE",
  VERIFY_PHONE_REQUEST: "VERIFY_PHONE_REQUEST",
  VERIFY_PHONE_ERROR: "VERIFY_PHONE_ERROR",
  VERIFY_PHONE_SUCCESS: "VERIFY_PHONE_SUCCESS",

  MERCHANT_LOGIN: "MERCHANT_LOGIN",
  MERCHANT_LOGIN_REQUEST: "MERCHANT_LOGIN_REQUEST",
  MERCHANT_LOGIN_ERROR: "MERCHANT_LOGIN_ERROR",
  MERCHANT_LOGIN_SUCCESS: "MERCHANT_LOGIN_SUCCESS",

  GET_ALL_POS_USERS: "GET_ALL_POS_USERS",
  GET_ALL_POS_USERS_REQUEST: "GET_ALL_POS_USERS_REQUEST",
  GET_ALL_POS_USERS_SUCCESS: "GET_ALL_POS_USERS_SUCCESS",
  GET_ALL_POS_USERS_ERROR: "GET_ALL_POS_USERS_ERROR",
  GET_ALL_POS_USERS_RESET: "GET_ALL_POS_USERS_RESET",

  TODAY_ORDER_STATUS: "TODAY_ORDER_STATUS",
  TODAY_ORDER_STATUS_REQUEST: "TODAY_ORDER_STATUS_REQUEST",
  TODAY_ORDER_STATUS_SUCCESS: "TODAY_ORDER_STATUS_SUCCESS",
  TODAY_ORDER_STATUS_ERROR: "TODAY_ORDER_STATUS_ERROR",
  TODAY_ORDER_STATUS_RESET: "TODAY_ORDER_STATUS_RESET",
};
