export const WALLET_TYPES = {
  WALLET_ANALYTICS: "WALLET_ANALYTICS",
  WALLET_ANALYTICS_REQUEST: "WALLET_ANALYTICS_REQUEST",
  WALLET_ANALYTICS_SUCCESS: "WALLET_ANALYTICS_SUCCESS",
  WALLET_ANALYTICS_ERROR: "WALLET_ANALYTICS_ERROR",
  WALLET_ANALYTICS_RESET: "WALLET_ANALYTICS_RESET",

  GET_TRANSACTION_LIST: "GET_TRANSACTION_LIST",
  GET_TRANSACTION_LIST_REQUEST: "GET_TRANSACTION_LIST_REQUEST",
  GET_TRANSACTION_LIST_SUCCESS: "GET_TRANSACTION_LIST_SUCCESS",
  GET_TRANSACTION_LIST_ERROR: "GET_TRANSACTION_LIST_ERROR",
  GET_TRANSACTION_LIST_RESET: "GET_TRANSACTION_LIST_RESET",

  GET_TRANSACTION_TYPE: "GET_TRANSACTION_TYPE",
  GET_TRANSACTION_TYPE_REQUEST: "GET_TRANSACTION_TYPE_REQUEST",
  GET_TRANSACTION_TYPE_SUCCESS: "GET_TRANSACTION_TYPE_SUCCESS",
  GET_TRANSACTION_TYPE_ERROR: "GET_TRANSACTION_TYPE_ERROR",
  GET_TRANSACTION_TYPE_RESET: "GET_TRANSACTION_TYPE_RESET",

  GET_ORDERS_BY_INVOICE_ID: "GET_ORDERS_BY_INVOICE_ID",
  GET_ORDERS_BY_INVOICE_ID_REQUEST: "GET_ORDERS_BY_INVOICE_ID_REQUEST",
  GET_ORDERS_BY_INVOICE_ID_SUCCESS: "GET_ORDERS_BY_INVOICE_ID_SUCCESS",
  GET_ORDERS_BY_INVOICE_ID_ERROR: "GET_ORDERS_BY_INVOICE_ID_ERROR",
  GET_ORDERS_BY_INVOICE_ID_RESET: "GET_ORDERS_BY_INVOICE_ID_RESET",
};
