import { COLORS, Fonts, SF, SH, SW } from '@/theme';
import { Dimensions, Platform, StyleSheet } from 'react-native';
import { verticalScale } from 'react-native-size-matters';
import { moderateScale, ms } from 'react-native-size-matters';

const height = Dimensions.get('window').height;
const width = Dimensions.get('window').width;

const styles = StyleSheet.create({
  flexAlign: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  displayFlex: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  tableDataHeaderCon: {
    height: ms(40),
    backgroundColor: COLORS.solidGrey,
    textAlign: 'center',
    borderColor: COLORS.solidGrey,
    marginHorizontal: moderateScale(10),
    justifyContent: 'center',
    width: width * 0.94,
    borderTopRightRadius: ms(5),
    borderTopLeftRadius: ms(5),
    paddingHorizontal: ms(10),
  },
  tableHeaderLeft: {
    flexDirection: 'row',
    width: width * 0.35,
    alignItems: 'center',
  },
  tableTextHeaFirst: {
    color: COLORS.black,
    fontFamily: Fonts.MaisonBold,
    fontSize: SF(12),
    letterSpacing: -1,
    width: width * 0.02,
  },
  tableTextHea: {
    color: COLORS.dark_grey,
    fontFamily: Fonts.MaisonBold,
    fontSize: ms(10),
    letterSpacing: -1,
    width: width * 0.15,
  },
  tableHeaderRight: {
    flexDirection: 'row',
    // justifyContent: 'space-between',
    // width: width * 0.6,
  },
  tableHeaderRightInner: {
    width: width * 0.28,
    justifyContent: 'center',
    alignItems: 'center',
    // backgroundColor: 'red',
  },
  tableTextHeader: {
    color: COLORS.dark_grey,
    fontFamily: Fonts.MaisonBold,
    fontSize: ms(10),
  },
  tableDataCon: {
    height: SH(55),
    borderBottomWidth: 1,
    borderColor: COLORS.solidGrey,
    justifyContent: 'center',
    paddingHorizontal: moderateScale(10),
  },
  tableTextDataFirst: {
    color: COLORS.solid_grey,
    fontFamily: Fonts.Regular,
    fontSize: ms(10),
    letterSpacing: -1,
    width: width * 0.02,
  },
  userNotFound: {
    color: COLORS.primary,
    fontFamily: Fonts.MaisonRegular,
    fontSize: ms(16),
    alignSelf: 'center',
  },
  lovingStyleData: {
    width: ms(25),
    height: ms(25),
    resizeMode: 'cover',
    borderRadius: 50,
  },
  tableTextDataName: {
    color: COLORS.solid_grey,
    fontFamily: Fonts.SemiBold,
    fontSize: ms(10),
    width: width * 0.2,
  },
  tableTextDataAdd: {
    color: COLORS.solid_grey,
    fontFamily: Fonts.Regular,
    fontSize: ms(10),
    width: width * 0.26,
  },
  tableTextData: {
    color: COLORS.solid_grey,
    fontFamily: Fonts.Regular,
    fontSize: ms(10),
  },
  editButtonCon: {
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 7,
  },
  editButtonText: {
    color: COLORS.primary,
    fontFamily: Fonts.Regular,
    fontSize: SF(12),
    paddingHorizontal: moderateScale(7),
    paddingVertical: verticalScale(2),
  },
  searchView: {
    height: ms(30),
    borderRadius: ms(15),
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 10,
    borderWidth: 1,
    borderColor: COLORS.row_grey,
  },
  searchImage: {
    width: SH(20),
    height: SH(20),
    resizeMode: 'contain',
  },
  textInputStyles: {
    width: ms(140),
    fontFamily: Fonts.Italic,
    fontSize: SF(15),
    paddingLeft: 5,
    padding: 0,
    margin: 0,
  },
  horizontalCustomerCon: {
    backgroundColor: COLORS.textInputBackground,
    borderRadius: 3,
    // width: Platform.OS === 'android' ? ms(100) : ms(75),
    height: ms(30),
    justifyContent: 'center',
    alignItems: 'center',
    // marginHorizontal: ms(10),
    paddingHorizontal: ms(20),
    paddingVertical: ms(2),
  },
  horizCustomerText: {
    color: COLORS.dark_grey,
    fontFamily: Fonts.Regular,
    fontSize: ms(10),
  },
  filterContainer: {
    height: ms(40),
    backgroundColor: COLORS.white,
    width: ms(40),
    borderRadius: ms(5),
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: ms(10),
  },
  filterIcon: {
    height: ms(16),
    width: ms(16),
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: ms(20),
    marginHorizontal: ms(16),
    // flex: 0.5,
  },
  container: {
    backgroundColor: COLORS.white,
    // flex: 1,
    height: ms(40),
    borderRadius: ms(5),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    overflow: 'hidden',
  },
  searchIcon: {
    height: ms(24),
    width: ms(24),
    tintColor: COLORS.placeholderText,
    marginRight: ms(10),
    marginLeft: ms(15),
  },

  inputStyle: {
    flex: 1,
    fontFamily: Fonts.Regular,
  },
  textInputStyle: {
    height: SH(40),
    width: '100%',
    fontFamily: Fonts.Italic,
    fontSize: SF(12),
    paddingLeft: 5,
    margin: 0,
    padding: 0,
  },
  searchTableDataHeaderCon: {
    height: SH(50),
    backgroundColor: COLORS.textInputBackground,
    textAlign: 'center',
    borderColor: COLORS.solidGrey,
    paddingHorizontal: moderateScale(10),
    justifyContent: 'center',
    width: width * 0.74,
  },

  // UserDetail

  profileCon: {
    borderWidth: 1,
    borderColor: COLORS.textInputBackground,
    borderRadius: 15,
    marginHorizontal: ms(10),
    paddingVertical: ms(10),
    paddingHorizontal: ms(10),
    flexDirection: 'row',
    backgroundColor: COLORS.white,
    // alignItems: 'center',
  },
  lovingStyle: {
    width: ms(60),
    height: ms(60),
    resizeMode: 'cover',
    borderRadius: 50,
  },
  angelaText: {
    fontFamily: Fonts.MaisonRegular,
    fontSize: ms(16),
    color: COLORS.black,
  },
  Phonelight: {
    width: ms(10),
    height: ms(10),
    resizeMode: 'contain',
  },
  adressText: {
    fontFamily: Fonts.Regular,
    fontSize: ms(12),
    color: COLORS.solid_grey,
    paddingHorizontal: moderateScale(5),
    width: width - ms(120),
  },
  pointCon: {
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 7,
    height: SH(48),
    width: SW(70),
    justifyContent: 'center',
    alignItems: 'center',
  },
  rewardStyle: {
    width: SW(8),
    height: SW(8),
    resizeMode: 'contain',
  },
  pointText: {
    fontFamily: Fonts.SemiBold,
    fontSize: SF(13),
    color: COLORS.primary,
    paddingHorizontal: moderateScale(3),
  },
  acceptCon: {
    borderColor: COLORS.solidGrey,
  },
  toggleBtnStyle: {
    width: SW(8),
    height: SW(8),
    resizeMode: 'contain',
  },
  toggleBtnCon: {
    width: SW(11),
    height: SW(8),
  },
  toggleBtnStyle2: {
    width: SW(8),
    height: SW(8),
    resizeMode: 'contain',
    tintColor: COLORS.gerySkies,
    transform: [{ rotate: '180deg' }],
  },
  acceptMarketText: {
    fontFamily: Fonts.Regular,
    fontSize: SF(13),
    color: COLORS.dark_grey,
  },
  orderTypeCon: {
    height: SH(55),
    justifyContent: 'center',
    paddingHorizontal: moderateScale(8),
    borderBottomWidth: 1,
    borderTopWidth: 1,
    borderColor: COLORS.solidGrey,
  },
  profileheaderUnderView: {
    flexDirection: 'row',
  },
  profileheaderChildView: {
    width: Platform.OS === 'android' ? ms(105) : ms(83),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: ms(3),
  },
  userNotFound: {
    color: COLORS.primary,
    fontFamily: Fonts.MaisonRegular,
    fontSize: SF(20),
    alignSelf: 'center',
  },
  saleTypeButtonCon: {
    paddingHorizontal: ms(5),
    paddingVertical: ms(1),
    borderRadius: 3,
  },
  scnStyle: {
    width: SW(13),
    height: SW(14),
    resizeMode: 'contain',
  },
  walletHomeBodyCon: {
    flex: 1,
    borderWidth: 1,
  },
  loader: {
    position: 'absolute',
    alignSelf: 'center',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
  },
  loaderView: {
    height: ms(150),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
  },
  profilDetailChildView: {
    width: Platform.OS === 'android' ? ms(125) : ms(95),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: ms(3),
  },
  calendarModalView: {
    backgroundColor: COLORS.white,
    width: width * 0.6,
    height: height - SW(30),
    alignSelf: 'center',
    paddingVertical: SH(10),
    paddingHorizontal: SW(5),
    borderRadius: SW(5),
  },
  textInputStyle: {
    height: SH(40),
    width: '100%',
    fontFamily: Fonts.Italic,
    fontSize: SF(12),
    paddingLeft: 5,
    margin: 0,
    padding: 0,
  },
  textInputView: {
    paddingHorizontal: ms(10),
    borderWidth: 0,
    alignItems: 'center',
    flexDirection: 'row',
    backgroundColor: COLORS.textInputBackground,
    borderRadius: 5,
    marginVertical: ms(8),
  },
  codeText: {
    fontSize: SF(18),
    color: COLORS.black,
    fontFamily: Fonts.Regular,
  },
  textInputContainer: {
    backgroundColor: COLORS.input_bg,
    color: COLORS.black,
    fontSize: SF(14),
    fontFamily: Fonts.Italic,
    flex: 1,
  },
  continueBtnCon: {
    flex: 1,
    padding: SH(10),
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: COLORS.gerySkies,
    borderWidth: 1,
    borderRadius: 3,
  },
  addToCartCon: {
    backgroundColor: COLORS.primary,
    padding: SH(10),
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: SH(10),
    borderRadius: 3,
    flex: 1,
  },
  addTocartText: {
    color: COLORS.white,
    fontSize: SH(13),
    fontFamily: Fonts.SemiBold,
  },
  detailBtnCon: {
    color: COLORS.gerySkies,
    fontSize: SH(13),
    fontFamily: Fonts.SemiBold,
  },
  dropDownContainerStyle: {
    borderWidth: 0,
    zIndex: 999,
  },
  dropdownStyle: {
    minHeight: ms(35),
    borderWidth: 0,
    borderRadius: ms(5),
    backgroundColor: COLORS.textInputBackground,
    // width: ms(88),
    zIndex: 999,
  },
  arrowIconStyle: {
    height: ms(16),
    width: ms(16),
    tintColor: COLORS.black,
    marginLeft: SW(-5),
  },
});

export default styles;
