import { StyleSheet, Dimensions, Platform } from 'react-native';
import { COLORS, SW, SH, SF, ShadowStyles } from '@/theme';
import { Fonts } from '@/assets';
import { moderateScale, scale, verticalScale } from 'react-native-size-matters';
import { height, width } from '@/theme/ScalerDimensions';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  displayFlex: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerMainView: {
    width: windowWidth,
    paddingHorizontal: SW(16),
    alignSelf: 'center',
    justifyContent: 'space-between',
    paddingVertical: SH(18),
    flexDirection: 'row',
  },
  truckStyle: {
    width: SH(32),
    height: SH(32),
    resizeMode: 'contain',
  },
  deliveryView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  deliveryText: {
    fontFamily: Fonts.MaisonRegular,
    color: COLORS.solid_grey,
    fontSize: SF(18),
    paddingLeft: SW(4),
  },
  searchView: {
    borderWidth: 1,
    width: SW(65),
    height: SH(43),
    borderRadius: 20,
    borderColor: COLORS.row_grey,
    flexDirection: 'row',
    alignItems: 'center',
  },
  searchImage: {
    width: SH(24),
    height: SH(24),
    resizeMode: 'contain',
    left: 3,
  },
  searchImage2: {
    width: SH(24),
    height: SH(24),
    resizeMode: 'contain',
    left: 3,
    transform: [{ rotate: '180deg' }],
  },
  textInputStyle: {
    width: SW(45),
    marginLeft: 10,
    fontFamily: Fonts.Italic,
    fontSize: SF(15),
  },
  orderView: {
    backgroundColor: COLORS.orderStatusBackground,
    borderRadius: 8,
    width: SW(80),
    height:SH(92),
    // paddingVertical: SH(35),
    flexDirection: 'row',
  },
  contentContainer: {
    justifyContent: 'space-between',
    flex: 1,
    paddingHorizontal: SW(5),
  },
  orderStatusView: {
    justifyContent: 'center',
    paddingLeft: SW(5),
  },
  orderStatusImage: {
    width: SW(10),
    height: SW(10),
    resizeMode: 'contain',
  },
  countView: {
    justifyContent: 'center',
    paddingLeft: SW(3),
  },
  countText: {
    color: COLORS.solid_grey,
    fontFamily: Fonts.MaisonRegular,
    fontSize: SF(18),
  },
  statusText: {
    color: COLORS.dark_grey,
    fontFamily: Fonts.Regular,
    fontSize: SF(13),
    textAlign: 'center',
  },
  orderNumberMainView: {
    width: windowWidth,
    borderWidth: 1,
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  orderNumberLeftView: {
    borderRadius: 5,
    ...ShadowStyles.shadow2,
    backgroundColor: COLORS.white,
    // width: SH(640),
  },
  chartView: {
    width: SW(168),
    height: SW(60),
    alignSelf: 'flex-start',
    alignItems: 'center',
  },
  chartImageStyle: {
    width: SW(168),
    height: SW(60),
    resizeMode: 'contain',
  },
  orderReviewRightView: {
    // width: windowWidth / 2.25,
    borderRadius: 5,
    ...ShadowStyles.shadow2,
    height: SW(105),
    backgroundColor: COLORS.white,
  },
  orderReviewText: {
    fontFamily: Fonts.MaisonBold,
    color: COLORS.primary,
    fontSize: SF(18),
  },
  reviewHeadingView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: SW(5),
    alignItems: 'center',
  },
  viewAllView: {
    width: SW(25),
    height: SH(30),
    backgroundColor: COLORS.bluish_green,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
  },
  viewText: {
    fontFamily: Fonts.SemiBold,
    color: COLORS.white,
    fontSize: SF(14),
    textAlign: 'center',
  },
  reviewRenderView: {
    marginHorizontal: SW(5),
    borderWidth: 1,
    flexDirection: 'row',
    marginVertical: SW(2),
    borderColor: COLORS.orderStatusBackground,
    borderRadius: 2,
    paddingVertical: 6,
    paddingLeft: SW(5),
    justifyContent: 'space-between',
  },
  timeView: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 1,
  },
  pinIcon: {
    width: SW(5),
    height: SW(8),
    resizeMode: 'contain',
  },
  rightIconStyle: {
    width: SW(10),
    justifyContent: 'center',
  },
  nameText: {
    fontFamily: Fonts.Regular,
    fontSize: SF(14),
    color: COLORS.solid_grey,
  },
  timeText: {
    fontFamily: Fonts.Regular,
    fontSize: SF(11),
    color: COLORS.dark_grey,
    textAlignVertical: 'center',
    paddingLeft: 2,
  },
  conversionRow: {
    width: windowWidth / 2.4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    alignSelf: 'center',
    paddingLeft: SW(7),
  },
  conversionBoxStyle: {
    width: SW(40),
    height: SW(40),
    resizeMode: 'contain',
  },
  orderFlatlistView: {
    width: SW(100),
    alignItems: 'center',
  },
  renderOrderView: {
    width: SW(70),
    borderRadius: 6,
    height: SW(15),
    backgroundColor: COLORS.textInputBackground,
    marginTop: 5,
    paddingLeft: SW(6),
    justifyContent: 'center',
  },
  deliveryOrders: {
    width: windowWidth / 2.25,
    backgroundColor: COLORS.orderStatusBackground,
    borderRadius: 5,
    paddingHorizontal: SW(5),
    paddingTop: SW(3),
  },
  deliveryViewStyle: {
    backgroundColor: COLORS.white,
    marginVertical: SH(15),
    marginHorizontal: SW(3),
    paddingLeft: SW(2),
    paddingRight: SW(5),
    paddingVertical: SW(2),
    width: SH(180),
    borderRadius: 5,
  },
  totalText: {
    fontFamily: Fonts.Regular,
    fontSize: SF(14),
    color: COLORS.solid_grey,
    paddingLeft: 2,
  },
  backView: {
    width: SW(25),
    height: SW(12),
    backgroundColor: COLORS.textInputBackground,
    flexDirection: 'row',
    borderRadius: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backText: {
    fontFamily: Fonts.SemiBold,
    fontSize: SF(16),
    color: COLORS.dark_grey,
  },
  orderDetailView: {
    backgroundColor: COLORS.white,
    width: windowWidth * 0.44,
    // borderWidth: 1,
    // paddingRight: SW(50)
  },
  orderDetailView2: {
    backgroundColor: COLORS.white,
    paddingRight: SW(0),
    borderWidth: 1,
    borderColor: COLORS.solidGrey,
    borderRadius: 10,
    height: SH(660),
    // width: windowWidth * 0.52,
    paddingBottom: 20,
  },
  profileDetailView: {
    marginHorizontal: SW(3),
    paddingHorizontal: SW(5),
    paddingVertical: SW(3),
    borderRadius: 6,
    backgroundColor: COLORS.textInputBackground,
    marginTop: 4,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  productImageView: {
    flexDirection: 'row',
    width: SW(50),
  },
  profileImage: {
    width: SW(12),
    height: SW(12),
    resizeMode: 'contain',
  },
  scooter: {
    width: SW(17),
    height: SW(18),
    resizeMode: 'contain',
  },
  titleText: {
    fontFamily: Fonts.Regular,
    fontSize: SF(18),
    color: COLORS.black,
  },
  boxText: {
    fontFamily: Fonts.Italic,
    fontSize: SF(11),
    color: COLORS.darkGray,
    marginBottom: 5,
  },
  productViewStyle: {
    // marginLeft: SW(5),
    marginRight: SW(4),
    flexDirection: 'row',
    top: 7,
    justifyContent: 'space-between',
  },
  priceText: {
    fontFamily: Fonts.Regular,
    fontSize: SF(18),
    color: COLORS.solid_grey,
  },
  bottomSheet: {
    // position: 'absolute',
    // bottom: 0,
    // height: SW(105),
    backgroundColor: COLORS.white,
    // width: windowWidth * 0.44,
    // ...ShadowStyles.shadow2,
    // paddingHorizontal: 30,
    paddingTop: 10,
    borderTopWidth: 1,
    borderColor: COLORS.row_grey,
  },
  bottomSheet2: {
    position: 'absolute',
    bottom: 10,
    ...ShadowStyles.shadow1,
    // width: windowWidth * 0.5,
    height: SH(200),
  },
  rowView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: SW(100),
    paddingVertical: 2,
    alignSelf: 'flex-end',
    paddingRight: 10,
    paddingVertical: verticalScale(2),
  },
  subTotal: {
    fontFamily: Fonts.MaisonRegular,
    fontSize: SF(14),
    color: COLORS.solid_grey,
  },
  subTotalValue: {
    fontFamily: Fonts.SemiBold,
    fontSize: SF(14),
    color: COLORS.solid_grey,
  },
  discount: {
    fontFamily: Fonts.SemiBold,
    fontSize: SF(14),
    color: COLORS.solid_grey,
  },
  discountValue: {
    fontFamily: Fonts.Regular,
    fontSize: SF(14),
    color: COLORS.darkGray,
  },
  totalLabel: {
    fontFamily: Fonts.MaisonBold,
    fontSize: SF(18),
    color: COLORS.solid_grey,
  },
  totalValue: {
    fontFamily: Fonts.SemiBold,
    fontSize: SF(18),
    color: COLORS.solid_grey,
  },
  button: {
    width: SW(100),
    height: SW(15),
    backgroundColor: COLORS.primary,
    alignSelf: 'flex-end',
    marginRight: 6,
    top: 8,
  },
  buttonText: {
    fontFamily: Fonts.SemiBold,
    fontSize: SF(16),
    color: COLORS.white,
  },
  buttonTextTrack: {
    fontFamily: Fonts.SemiBold,
    fontSize: SF(16),
    color: COLORS.primary,
  },
  declineButton: {
    width: SW(50),
    height: SW(15),
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.primary,
    alignSelf: 'flex-end',
    marginRight: 6,
    top: 8,
  },
  acceptButton: {
    width: SW(50),
    height: SW(15),
    backgroundColor: COLORS.primary,
    alignSelf: 'flex-end',
    marginRight: 6,
    top: 8,
  },
  printAgainCon: {
    height: SW(15),
    width: SH(700),
    backgroundColor: COLORS.primary,
    alignSelf: 'flex-end',
    // marginRight: 6,
    top: 8,
  },
  orderReviewButton: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
  },
  horizontalLine: {
    borderWidth: 0.5,
    borderColor: COLORS.solidGrey,
    marginTop: 10,
  },
  itemSeparatorView: {
    backgroundColor: COLORS.solidGrey,
    height: 1,
    width: '92%',
    alignSelf: 'center',
    marginVertical: verticalScale(2),
  },
  map: {
    width: windowWidth / 2.3,
    height: Platform.OS === 'android' ? SW(130) : SW(190),
    alignSelf: 'center',
    borderRadius: 6,
  },
  headerTab: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    alignItems: 'center',
  },
  orderModalView: {
    position: 'absolute',
    alignSelf: 'flex-end',
    bottom: Platform.OS === 'android' ? 20 : 10,
    backgroundColor: COLORS.white,
    right: SW(5),
    width: SW(100),
    paddingVertical: 8,
    borderRadius: 7,
  },
  deliveryImage: {
    width: SW(15),
    height: SH(46),
    resizeMode: 'contain',
    alignSelf: 'flex-end',
  },
  verified: {
    width: SW(6),
    height: SW(6),
    resizeMode: 'contain',
    alignSelf: 'flex-end',
    marginLeft: 15,
  },
  deliveryStatus: {
    flexDirection: 'row',
    height: SH(50),
  },
  verifyText: {
    fontFamily: Fonts.SemiBold,
    fontSize: SF(11),
    color: COLORS.solid_grey,
  },
  verifyTextLight: {
    fontFamily: Fonts.Regular,
    fontSize: SF(11),
    color: COLORS.gerySkies,
  },
  justifyContentStyle: {
    justifyContent: 'flex-end',
  },
  radioImage: {
    width: SW(8),
    height: SW(8),
    resizeMode: 'contain',
    alignSelf: 'center',
    left: 6,
  },
  selectShipingRightView: {
    borderWidth: 1,
    // width: SH(545),
    borderRadius: 10,
    borderColor: COLORS.solidGrey,
    paddingHorizontal: moderateScale(10),
  },
  selectShipingCon: {
    // width: SH(510),
    height: SH(56),
    borderWidth: 1,
    borderColor: COLORS.solidGrey,
    borderRadius: 10,
    paddingHorizontal: moderateScale(10),
    justifyContent: 'center',
  },
  radioRound: {
    width: SH(24),
    height: SH(24),
    resizeMode: 'contain',
  },
  shipingRate: {
    fontFamily: Fonts.SemiBold,
    fontSize: SF(14),
    color: COLORS.solid_grey,
  },
  ups2: {
    width: SH(36),
    height: SH(36),
    resizeMode: 'contain',
  },
  printButtonCon: {
    width: SH(510),
    height: SH(64),
    borderWidth: 1,
    borderColor: COLORS.solidGrey,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  printText: {
    fontFamily: Fonts.SemiBold,
    fontSize: SF(16),
    color: COLORS.darkGray,
  },
  orderOfReview: {
    fontFamily: Fonts.MaisonBold,
    fontSize: SF(18),
    color: COLORS.primary,
    paddingHorizontal: moderateScale(13),
  },
  printAgainButton: {
    width: SW(160),
    height: SW(15),
    backgroundColor: COLORS.primary,
    top: 8,
    alignSelf: 'center',
  },
  printAgainTack: {
    backgroundColor: COLORS.blue_shade,
  },
  fedContextCon: {
    borderWidth: 1,
    // width:SW(350),
    height: SH(60),
    borderRadius: 10,
    borderColor: COLORS.solidGrey,
    marginHorizontal: moderateScale(10),
    marginTop: SH(10),
    justifyContent: 'center',
    paddingHorizontal: moderateScale(5),
  },
  noteContainer: {
    borderWidth: 2,
    borderColor: COLORS.solidGrey,
    height: SH(126),
    borderRadius: 5,
    paddingHorizontal: moderateScale(15),
  },
  note: {
    fontFamily: Fonts.SemiBold,
    fontSize: SF(14),
    color: COLORS.black,
  },
  contactCon: {
    backgroundColor: COLORS.textInputBackground,
    width: SW(35),
    height: SW(11),
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  contact: {
    fontFamily: Fonts.SemiBold,
    fontSize: SF(14),
    color: COLORS.solid_grey,
  },
  Phonelight: {
    width: SW(5),
    height: SW(5),
    resizeMode: 'contain',
    marginHorizontal: moderateScale(5),
    tintColor: COLORS.solid_grey,
  },
  fedx: {
    width: SW(16),
    height: SW(16),
    resizeMode: 'contain',
    marginTop: 10,
  },
  fedEx: {
    fontFamily: Fonts.SemiBold,
    fontSize: SF(16),
    color: COLORS.black,
  },
  fedNumber: {
    fontFamily: Fonts.SemiBold,
    fontSize: SF(12),
    color: COLORS.primary,
  },
  verifySuccess: {
    fontFamily: Fonts.SemiBold,
    fontSize: SF(12),
    color: COLORS.bluish_green,
  },
  scrollMainCon: {
    // borderWidth: 5,
    paddingHorizontal: moderateScale(5),
  },
});
