export const STATUS = {
  ERROR: 'ERROR',
  LOADING: 'LOADING',
  NOT_STARTED: 'NOT_STARTED',
  SUCCESS: 'SUCCESS',
};

export const APPOINTMENT_STATUS = {
  REVIEWING: '0',
  ACCEPTED_BY_SELLER: '1',
  CHECKED_IN: '2',
  COMPLETED: '3',
  REJECTED_BY_SELLER: '4',
  CANCELLED_BY_CUSTOMER: '5',
};
