export const orderStatus = [
  {
    key: '1',
    status: 'Orders to Review',
    count: '49',
    image: require('@/assets/icons/ic_deliveryOrder/order.png'),
  },
  {
    key: '2',
    status: 'Order Preparing',
    count: '23',
    image: require('@/assets/icons/ic_deliveryOrder/Category.png'),
  },
  {
    key: '3',
    status: 'Ready to pickup',
    count: '15',
    image: require('@/assets/icons/ic_deliveryOrder/Category.png'),
  },
  {
    key: '4',
    status: 'Delivering',
    count: '9',
    image: require('@/assets/icons/ic_deliveryOrder/driver.png'),
  },
];

export const orderReview = [
  {
    key: '1',
    name: 'Rebecca R. Russell',
    time: '2.5 miles',
    items: '3 items',
    price: '$489.50',
    deliveryType: 'Expess delivery',
    timeSlot: 'immediately',
  },
  {
    key: '2',
    name: 'Rebecca R. Russell',
    time: '2.5 miles',
    items: '3 items',
    price: '$489.50',
    deliveryType: '1 hour delivery window',
    timeSlot: '2.00 PM - 3.00 PM',
  },
  {
    key: '3',
    name: 'Rebecca R. Russell',
    time: '2.5 miles',
    items: '3 items',
    price: '$489.50',
    deliveryType: '1 hour delivery window',
    timeSlot: '2.00 PM - 3.00 PM',
  },
  {
    key: '4',
    name: 'Rebecca R. Russell',
    time: '2.5 miles',
    items: '3 items',
    price: '$489.50',
    deliveryType: '1 hour delivery window',
    timeSlot: '2.00 PM - 3.00 PM',
  },
  {
    key: '5',
    name: 'Rebecca R. Russell',
    time: '2.5 miles',
    items: '3 items',
    price: '$489.50',
    deliveryType: '1 hour delivery window',
    timeSlot: '2.00 PM - 3.00 PM',
  },
  {
    key: '6',
    name: 'Rebecca R. Russell',
    time: '2.5 miles',
    items: '3 items',
    price: '$489.50',
    deliveryType: '1 hour delivery window',
    timeSlot: '2.00 PM - 3.00 PM',
  },
  {
    key: '7',
    name: 'Rebecca R. Russell',
    time: '2.5 miles',
    items: '3 items',
    price: '$489.50',
    deliveryType: '1 hour delivery window',
    timeSlot: '2.00 PM - 3.00 PM',
  },
  {
    key: '8',
    name: 'Rebecca R. Russell',
    time: '2.5 miles',
    items: '3 items',
    price: '$489.50',
    deliveryType: '2 hour delivery window',
    timeSlot: '2.00 PM - 3.00 PM',
  },
];

export const orderConversion = [
  {
    key: '1',
    title: 'Orders Placed',
    total: '49',
  },
  {
    key: '2',
    title: 'Orders Cancelled',
    total: '3',
  },
  {
    key: '3',
    title: 'Orders delivered',
    total: '46',
  },
];

export const deliveryOrders = [
  {
    key: '1',
    image: require('@/assets/icons/ic_deliveryOrder/parcel.png'),
    delivery: 'Expess delivery',
    total: '3',
  },
  {
    key: '2',
    image: require('@/assets/icons/ic_navigator/deliveryTruck.png'),
    delivery: 'Expess delivery',
    total: '17',
  },
  {
    key: '3',
    image: require('@/assets/icons/ic_navigator/deliveryTruck.png'),
    delivery: 'Expess delivery',
    total: '49',
  },
];

export const productList = [
  {
    key: '1',
    image: require('@/assets/icons/ic_deliveryOrder/cigar.png'),
    title: 'JFR Maduro',
    box: 'Box',
    quantity: '1',
    price: '$382.75',
  },
  {
    key: '2',
    image: require('@/assets/icons/ic_deliveryOrder/cigarrete.png'),
    title: 'Ashton Magnum',
    box: 'Box',
    quantity: '1',
    price: '$236.50',
  },
  {
    key: '3',
    image: require('@/assets/icons/ic_deliveryOrder/blueCigar.png'),
    title: 'Marlboro Touch',
    box: 'Box',
    quantity: '1',
    price: '$43.99',
  },
  {
    key: '4',
    image: require('@/assets/icons/ic_deliveryOrder/cigarBox.png'),
    title: 'Marlboro Touch',
    box: 'Box',
    quantity: '1',
    price: '$43.99',
  },
  {
    key: '5',
    image: require('@/assets/icons/ic_deliveryOrder/marlboro.png'),
    title: 'Marlboro Touch',
    box: 'Box',
    quantity: '1',
    price: '$43.99',
  },
  {
    key: '6',
    image: require('@/assets/icons/ic_deliveryOrder/marlboro.png'),
    title: 'Marlboro Touch',
    box: 'Box',
    quantity: '1',
    price: '$43.99',
  },
  {
    key: '7',
    image: require('@/assets/icons/ic_deliveryOrder/marlboro.png'),
    title: 'Marlboro Touch',
    box: 'Box',
    quantity: '1',
    price: '$43.99',
  },
  {
    key: '8',
    image: require('@/assets/icons/ic_deliveryOrder/marlboro.png'),
    title: 'Marlboro Touch',
    box: 'Box',
    quantity: '1',
    price: '$43.99',
  },
];
