import { Fonts } from '@/assets';
import { COLORS, SF, SH, SW, ShadowStyles } from '@/theme';
import { height, width } from '@/theme/ScalerDimensions';
import { monthsShort } from 'moment';
import { Dimensions, Platform, StyleSheet } from 'react-native';
import { Colors } from 'react-native-paper';
import { moderateScale, verticalScale, ms, moderateVerticalScale } from 'react-native-size-matters';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.textInputBackground,
  },
  displayflex: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    // flex: 1,
  },
  displayRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  displayflex2: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },

  // main screen css start
  searchScreenHeader: {
    height: SH(60),
    justifyContent: 'center',
  },
  cashLabelBold: {
    color: COLORS.navy_light_blue,
    fontSize: SF(12),
    fontFamily: Fonts.Medium,
  },
  crossBg: {
    width: SW(10),
    height: SW(8),
    resizeMode: 'contain',
  },
  _centerContainer: {
    backgroundColor: COLORS.white,
    // marginTop: ms(20),
    // marginHorizontal: ms(26),
    // marginBottom: ms(10),
    borderRadius: ms(3),
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  _totalAmountTitle: {
    color: COLORS.navy_blue,
    fontFamily: Fonts.Regular,
    fontSize: ms(17),
  },
  _dollarSymbol: {
    fontSize: ms(17),
    color: COLORS.navy_blue,
    fontFamily: Fonts.SemiBold,
    marginTop: ms(2),
  },
  _dollarInput: {
    fontSize: ms(10),
    color: COLORS.solid_grey,
    fontFamily: Fonts.SemiBold,
    marginBottom: ms(1),
  },
  _amount: {
    color: COLORS.navy_blue,
    fontFamily: Fonts.SemiBold,
    fontSize: ms(25),
  },
  _bottomContainer: {
    marginTop: ms(10),
    borderColor: COLORS.light_purple,
    borderWidth: 1,
    borderRadius: ms(9),
    marginTop: ms(50),
  },
  _selectTips: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(12),
    color: COLORS.navy_blue,
    alignSelf: 'center',
  },
  _boxView: {
    height: ms(110),
    // flexGrow: 1,
    width: Platform.OS === 'ios' ? ms(103) : ms(110),
    backgroundColor: COLORS.transparentBlue,
    borderRadius: ms(8),
    justifyContent: 'center',
    alignItems: 'center',
    margin: ms(5),
    borderWidth: 1,
  },
  _usdText: {
    color: COLORS.navy_blue,
    fontFamily: Fonts.SemiBold,
    fontSize: ms(11),
  },
  _tipsPercent: {
    color: COLORS.solid_grey,
    fontFamily: Fonts.SemiBold,
    fontSize: ms(7),
    marginTop: ms(2),
  },
  _innerContainer: {
    backgroundColor: COLORS.textInputBackground,
    flex: 1,
  },
  _inputMain: {
    marginTop: ms(15),
    width: ms(360),
  },
  _inputSubView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  _inputContainer: {
    height: ms(40),
    borderRadius: ms(3),
    flex: 1,
  },
  dollarInputCon: {
    borderColor: COLORS.solidGrey,
    borderWidth: 1,
    height: ms(40),
    borderRadius: ms(3),
    paddingHorizontal: ms(10),
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  _inputCashContainer: {
    height: ms(40),
    borderRadius: ms(3),
    borderWidth: 1,
    paddingHorizontal: ms(10),
    borderColor: COLORS.solidGrey,
    flexGrow: 1,
  },
  _inputOtherAmount: {
    flexGrow: 1,
    marginTop: ms(10),
    height: ms(40),
    borderRadius: ms(20),
    borderColor: COLORS.light_purple,
    borderWidth: 1,
    paddingHorizontal: ms(10),
    fontSize: ms(10),
  },
  _tipsButton: {
    height: ms(40),
    paddingHorizontal: ms(10),
    backgroundColor: COLORS.silver_solid,
    borderRadius: ms(3),
    justifyContent: 'center',
    alignContent: 'center',
    flex: 0.4,
    marginLeft: ms(10),
  },
  _tipText: {
    color: COLORS.dark_grey,
    fontFamily: Fonts.SemiBold,
    fontSize: ms(8),
    alignSelf: 'center',
  },
  _border: {
    height: ms(10),
    backgroundColor: COLORS.solidGrey,
    width: ms(1),
    marginHorizontal: ms(10),
  },
  _date: {
    color: COLORS.black,
    fontFamily: Fonts.Regular,
    fontSize: ms(8),
  },
  _topContainer: {
    // position: 'absolute',
    marginLeft: ms(25),
    width: '98%',
    alignItems: 'center',
    height: ms(30),
    flexDirection: 'row',
  },
  _cross: {
    height: ms(15),
    width: ms(15),
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    right: ms(20),
  },
  _payBYBoxContainer: (selectedPaymentIndex, index) => {
    return {
      borderColor: selectedPaymentIndex === index ? COLORS.success_green : COLORS.light_purple,
      borderWidth: 1,
      height: ms(90),
      width: Platform.OS === 'ios' ? ms(125) : ms(157),
      marginHorizontal: ms(4),
      borderRadius: ms(9),
      padding: ms(6),
      backgroundColor: selectedPaymentIndex === index ? COLORS.success_green : COLORS.sky_grey,
    };
  },
  _payBYBoxContainerEmpty: {
    height: ms(125),
    width: ms(170),
    margin: ms(3),
    alignItems: 'center',
    padding: ms(10),
  },
  _payByTitle: {
    fontFamily: Fonts.Regular,
    color: COLORS.solid_grey,
    fontSize: ms(9),
    marginBottom: ms(3),
  },
  _payByMethod: (selectedPaymentIndex, index) => {
    return {
      fontFamily: Fonts.Medium,
      color: selectedPaymentIndex === index ? COLORS.white : COLORS.torquoise,
      fontSize: ms(9),
    };
  },
  _payByAmount: (selectedPaymentIndex, index) => {
    return {
      fontFamily: Fonts.Medium,
      color: selectedPaymentIndex === index ? COLORS.white : COLORS.navy_blue,
      fontSize: ms(10),
      marginTop: ms(2),
    };
  },
  _payByIcon: (selectedPaymentIndex, index) => {
    return {
      height: ms(18),
      width: ms(18),
      resizeMode: 'contain',
      tintColor: selectedPaymentIndex === index ? COLORS.white : COLORS.navy_blue,
    };
  },
  _bottomCardView: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    backgroundColor: COLORS.primary,
    height: ms(110),
    width: ms(160),
    borderRadius: ms(10),
    justifyContent: 'center',
    alignItems: 'center',
  },
  _cardIconView: {
    height: ms(47),
    width: ms(47),
    tintColor: COLORS.solid_green,
  },
  _cardSubtitle: {
    fontFamily: Fonts.Regular,
    fontSize: ms(6),
    color: COLORS.white,
    marginTop: ms(12),
  },
  _sendRequest: {
    height: ms(40),
    paddingHorizontal: ms(10),
    backgroundColor: COLORS.dark_grey,
    borderRadius: ms(3),
    justifyContent: 'center',
    alignContent: 'center',
    // flex: 0.4,
    marginLeft: ms(10),
  },
  _orContainer: {
    flexDirection: 'row',
    // marginVertical: ms(3),
    alignItems: 'center',
  },
  _borderView: {
    backgroundColor: COLORS.solidGrey,
    height: 1,
    flex: 1,
  },
  _orText: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(6),
    marginHorizontal: ms(7),
  },
  _sendPaymentText: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(8),
    color: COLORS.solid_grey,
    marginBottom: ms(10),
    marginTop: ms(20),
  },
  itemLIistCon: {
    // width: windowWidth * 0.67,
    flex: 0.7,
    // height: windowHeight * 0.88,
    backgroundColor: COLORS.white,
    borderRadius: ms(12),
    paddingHorizontal: moderateScale(8),
    paddingTop: verticalScale(8),

    marginRight: ms(7),
  },
  rightSideCon: {
    backgroundColor: COLORS.white,
    flex: 0.3,
    // height: windowHeight * 0.87,
    padding: ms(8),
    borderRadius: ms(12),

    marginRight: ms(7),
    // marginLeft: ms(10),
  },

  categoryMenu: {
    width: SW(7),
    height: SW(7),
    resizeMode: 'contain',
    tintColor: COLORS.primary,
  },

  contentContainer: {
    flex: 1,
    justifyContent: 'space-between',
    paddingHorizontal: SW(2),
  },

  allProduct: {
    color: COLORS.navy_blue,
    fontSize: SF(13),
    fontFamily: Fonts.Medium,
  },
  allProductCount: {
    color: COLORS.darkGray,
    fontSize: SF(13),
    fontFamily: Fonts.Italic,
  },
  productBodyCon: {
    backgroundColor: COLORS.textInputBackground,
    // flex: 1,
    borderRadius: 10,
    // paddingTop: verticalScale(5),
    paddingHorizontal: moderateScale(4),
  },
  productDes: {
    color: COLORS.navy_blue,
    fontSize: ms(8),
    fontFamily: Fonts.Medium,
  },
  productDesBold: {
    fontFamily: Fonts.SemiBold,
  },

  // sideBar css start
  keyboard: {
    width: SW(12),
    height: Platform.OS === 'android' ? SH(38) : SH(45),
    resizeMode: 'contain',
  },
  holdCartCon: {
    width: windowWidth * 0.09,
    height: SH(38),
    borderRadius: 5,
    backgroundColor: COLORS.white,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
  },
  addDiscountcon: {
    width: windowWidth * 0.11,
    height: SH(38),
    borderRadius: 5,
    backgroundColor: COLORS.white,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.navy_blue,
    alignSelf: 'center',
  },
  holdCartPad: {
    width: windowWidth * 0.035,
    height: SH(38),
    borderRadius: 5,
    backgroundColor: COLORS.white,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
  },
  pause: {
    width: SW(6),
    height: SW(6),
    resizeMode: 'contain',
    tintColor: COLORS.dark_grey,
  },
  keyboardIcon: {
    width: SW(7),
    height: SW(7),
    resizeMode: 'contain',
    tintColor: COLORS.dark_grey,
  },
  holdCart: {
    color: COLORS.dark_grey,
    fontSize: SF(12),
    fontFamily: Fonts.Medium,
    paddingHorizontal: moderateScale(3),
  },

  dark_greyBg: {
    backgroundColor: COLORS.dark_grey,
  },
  addNotesBtn: {
    backgroundColor: COLORS.navy_blue,
    alignSelf: 'center',
  },
  nameAddCon: {
    height: Platform.OS === 'android' ? windowHeight * 0.38 : windowHeight * 0.37,
    borderRadius: ms(8),
    borderColor: COLORS.extraYello,
    borderWidth: 1,
  },
  availbleOfferScroll: {
    flexGrow: 1,
    paddingBottom: 20,
  },
  avaliableOfferCon: {
    height: ms(25),
    borderTopEndRadius: ms(6),
    borderTopLeftRadius: ms(6),
    backgroundColor: COLORS.extraYello,
    paddingHorizontal: moderateScale(5),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },

  addDiscountCon: (addnotes) => {
    return {
      backgroundColor: addnotes ? COLORS.textInputBackground : COLORS.extraYello,
      height: Platform.OS === 'android' ? SH(40) : SH(45),
      borderRadius: ms(8),
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: moderateScale(5),
      flex: 1,
      marginRight: ms(2),
    };
  },
  addDiscountText: (value) => {
    return {
      color: value ? COLORS.coffee : COLORS.navy_blue,
      fontSize: ms(7.5),
      fontFamily: Fonts.Medium,
    };
  },
  addDiscountPic: (value) => {
    return {
      width: ms(10),
      height: ms(10),
      resizeMode: 'contain',
      paddingHorizontal: moderateScale(7),
      tintColor: value ? COLORS.coffee : COLORS.navy_blue,
    };
  },
  totalItemCon: {
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: COLORS.solidGrey,
    paddingVertical: verticalScale(3),
  },
  totalItem: {
    fontSize: SF(16),
    color: COLORS.primary,
    fontFamily: Fonts.MaisonBold,
    paddingVertical: verticalScale(4),
  },
  paddVertical: {
    paddingVertical: verticalScale(3),
  },
  subTotal: {
    fontSize: SF(14),
    color: COLORS.lavender,
    fontFamily: Fonts.Medium,
  },
  subTotalDollar: {
    fontSize: SF(14),
    color: COLORS.navy_blue,
    fontFamily: Fonts.Regular,
  },
  itemValue: {
    fontSize: SF(16),
    color: COLORS.textBlue,
    fontFamily: Fonts.Medium,
  },

  checkoutButtonSideBar: {
    width: windowWidth * 0.22,
    height: ms(35),
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.navy_blue,
    alignSelf: 'center',
    borderRadius: ms(30),
    paddingVertical: verticalScale(1),
  },
  checkoutText: {
    color: COLORS.white,
    fontSize: SF(16),
    fontFamily: Fonts.Medium,
  },
  checkArrow: {
    width: SW(10),
    height: SW(4),
    resizeMode: 'contain',
    paddingHorizontal: moderateScale(6),
  },

  // sideBar css end

  // categoryModal css Start
  categoryModalCon: {
    backgroundColor: COLORS.white,
    width: windowWidth * 0.55,
    height: windowHeight * 0.75,
    borderRadius: 10,
    alignSelf: 'center',
    paddingHorizontal: moderateScale(10),
  },
  crossButton: {
    width: SW(9),
    height: SW(9),
    resizeMode: 'contain',
  },
  categories: {
    color: COLORS.dark_grey,
    fontSize: SF(17),
    fontFamily: Fonts.SemiBold,
  },
  categoryInputWraper: {
    borderWidth: 1,
    borderColor: COLORS.solidGrey,
    borderRadius: 7,
    height: Platform.OS === 'android' ? SH(48) : SH(45),
    justifyContent: 'center',
  },
  catProArrayCon: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.solidGrey,
    width: windowWidth * 0.12,
    justifyContent: 'center',
    paddingHorizontal: moderateScale(10),
    marginTop: verticalScale(5),
    marginRight: moderateScale(7),
    paddingVertical: SH(5),
  },
  cloth: {
    width: SW(14),
    height: SW(14),
    resizeMode: 'contain',
  },
  categories: {
    color: COLORS.black,
    fontSize: SF(16),
    fontFamily: Fonts.MaisonBold,
  },
  listed: {
    color: COLORS.darkGray,
    fontSize: SF(11),
    fontFamily: Fonts.Regular,
  },
  categoryflatlistHeight: {
    flex: 1,
  },

  // addto cart modal css start
  addCartCon: {
    backgroundColor: 'white',
    borderRadius: 10,
    width: windowWidth * 0.5,
    paddingTop: ms(5),
    paddingBottom: ms(20),
    marginVertical: ms(20),
    alignSelf: 'center',
  },

  addCartConHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: SH(70),
    paddingHorizontal: moderateScale(15),
    borderBottomWidth: 1,
    borderColor: COLORS.solidGrey,
  },
  backTocartCon: {
    backgroundColor: '#F5F6F7',
    width: SH(130),
    height: SH(44),
    padding: SH(10),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 3,
  },
  backTocartText: {
    color: COLORS.black,
    fontSize: SH(13),
    fontFamily: Fonts.SemiBold,
  },
  continueBtnCon: {
    width: SH(120),
    height: SH(44),
    padding: SH(10),
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: COLORS.primary,
    borderWidth: 1,
    marginLeft: SH(10),
    borderRadius: 3,
  },
  addToCartCon: {
    backgroundColor: COLORS.primary,
    width: SH(120),
    height: SH(44),
    padding: SH(10),
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: SH(10),
    borderRadius: 3,
  },
  newCutomersaveCon: {
    width: SH(160),
    height: SH(40),
  },
  discardBtnCon: {
    backgroundColor: COLORS.textInputBackground,
    width: SH(130),
  },
  addTocartText: {
    color: COLORS.white,
    fontSize: SH(13),
    fontFamily: Fonts.SemiBold,
  },
  colimbiaText: {
    color: COLORS.black,
    fontSize: SH(20),
    fontFamily: Fonts.Bold,
  },
  detailLeftDetail: {
    width: windowWidth * 0.35,
  },
  sizeAndColor: {
    color: COLORS.dark_grey,
    fontSize: SH(16),
    fontFamily: Fonts.Medium,
  },
  counterCon: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    marginVertical: SH(20),
  },
  minusBtnCon: {
    borderColor: '#D8D8D8',
    borderWidth: 1,
    width: windowWidth * 0.14,
    height: SH(60),
    alignItems: 'center',
    justifyContent: 'center',
  },
  counterText: {
    fontSize: SH(28),
    fontFamily: Fonts.Bold,
    color: COLORS.black,
  },
  colorText: {
    marginHorizontal: SH(10),
    fontSize: SH(18),
    fontFamily: Fonts.Regular,
    color: COLORS.gerySkies,
  },
  colorRow: {
    height: SH(2),
    // width: SH(235),
    width: windowWidth * 0.17,
    backgroundColor: '#D8D8D8',
  },
  serviceRow: {
    width: windowWidth * 0.14,
  },
  selectColorItem: {
    width: SH(142),
    height: SH(60),
    borderRadius: 5,
    // borderColor: '#E1E3E4',
    // borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    // marginHorizontal: moderateScale(3),
    // margin: ms(6),
  },

  selectSizeItem: {
    width: SH(142),
    height: SH(60),
    borderRadius: 5,
    borderColor: '#E1E3E4',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: moderateScale(3),
    margin: ms(6),
  },
  colorSelectText: {
    fontSize: SF(18),
    fontFamily: Fonts.Regular,
    color: COLORS.black,
  },
  detailBtnCon: {
    color: COLORS.primary,
    fontSize: SH(13),
    fontFamily: Fonts.SemiBold,
  },

  // addto cart modal css end

  // addto cart detail modal css start
  addCartDetailConHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: SH(70),
  },
  addCartDetailConHeader2: {
    height: SH(55),
    borderBottomWidth: 1,
    borderColor: COLORS.light_purple,
  },
  addCartDetailCon: {
    backgroundColor: 'white',
    borderRadius: 10,
    width: windowWidth * 0.6,
    height: windowHeight * 0.92,
    position: 'absolute',
    alignSelf: 'center',
    paddingHorizontal: moderateScale(13),
  },
  jacketName: {
    color: COLORS.navy_blue,
    fontSize: SH(18),
    fontFamily: Fonts.Medium,
  },
  addCartDetailBody: {
    height: windowHeight * 0.82,
  },
  discriptionWidth: {
    width: windowHeight * 0.86,
  },
  clothProfileCon: {
    // height: windowHeight * 0.20,
    flexDirection: 'row',
  },
  clothProfileDes: {
    color: COLORS.darkGray,
    fontSize: SH(11),
    fontFamily: Fonts.Regular,
  },
  clothProfileSubHead: {
    color: COLORS.darkGray,
    fontSize: SH(11),
    fontFamily: Fonts.Italic,
  },
  profileCloth: {
    width: SW(16),
    height: SW(16),
    resizeMode: 'contain',
  },
  profileClothDes: {
    flexDirection: 'column',
    justifyContent: 'space-between',
    marginLeft: 10,
    width: ms(500),
  },
  priceCon: {
    height: windowHeight * 0.07,
    backgroundColor: COLORS.washGrey,
    borderRadius: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: moderateScale(10),
    alignItems: 'center',
  },
  skuCon: {
    borderWidth: 1,
    borderColor: COLORS.solidGrey,
    borderRadius: 7,
    paddingHorizontal: moderateScale(7),
  },
  skuConBody: {
    height: windowHeight * 0.06,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderColor: COLORS.solidGrey,
  },
  reOrderBody: {
    height: windowHeight * 0.05,
    borderTopWidth: 1,
    borderBottomWidth: 0,
  },
  sku: {
    color: COLORS.solid_grey,
    fontSize: SH(14),
    fontFamily: Fonts.Regular,
  },
  inStoreBody: {
    height: windowHeight * 0.06,
    borderWidth: 1,
    borderRadius: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderColor: COLORS.solidGrey,
    paddingHorizontal: moderateScale(15),
  },
  inStoreText: {
    color: COLORS.solid_grey,
    fontSize: SH(14),
    fontFamily: Fonts.MaisonBold,
  },
  toggleSecBlue: {
    width: SW(7),
    height: SW(7),
    resizeMode: 'contain',
  },
  ScrollableMainCon: {
    width: windowWidth * 0.48,
    alignSelf: 'center',
  },
  selectColorCon: {
    flexDirection: 'row',
  },
  colorArea: {
    width: SW(6),
    height: SW(6),
    backgroundColor: COLORS.bluish_green,
    borderRadius: 5,
    marginRight: 3,
  },
  scrollableBodyCon: {
    width: windowWidth * 0.48,
    alignSelf: 'center',
    // height: windowHeight * 0.45,
    flexDirection: 'row',
    borderWidth: 1,
  },
  colorSelectArea: {
    // height: windowHeight * 0.45,
    width: windowWidth * 0.09,
    alignItems: 'center',
    borderEndWidth: 1,
    borderColor: COLORS.solidGrey,
  },
  quantitySelectArea: {
    // height: windowHeight * 0.45,
    width: windowWidth * 0.5,
    paddingHorizontal: moderateScale(10),
  },
  RemindSelectArea: {
    // height: windowHeight * 0.45,
    width: windowWidth * 0.14,
  },
  imageView: {
    borderWidth: 2,
    borderRadius: 5,
    width: ms(30),
    height: ms(30),
    marginVertical: verticalScale(3),
  },
  scrollImage: {
    width: ms(25),
    height: ms(25),
    resizeMode: 'contain',
  },
  sizeSelectItemCon: {
    width: ms(200),
    height: SW(14),
    borderWidth: 1,
    borderColor: COLORS.solidGrey,
    borderRadius: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: moderateScale(10),
    marginHorizontal: ms(15),
  },
  adminItemCon: {
    width: ms(140),
    height: SW(11),
    borderWidth: 1,
    borderColor: COLORS.solidGrey,
    borderRadius: 5,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: moderateScale(3),
    marginHorizontal: ms(5),
  },
  bell: {
    width: SW(7),
    height: SW(7),
    resizeMode: 'contain',
    marginHorizontal: moderateScale(4),
  },
  sizeSelectItemCona: {
    borderWidth: 1,
    borderColor: COLORS.solidGrey,
    borderRadius: 5,
    paddingHorizontal: moderateScale(10),
  },

  // addto cart detail modal css start

  blueListHeader: {
    // backgroundColor: COLORS.primary,
    height: SH(40),
    borderRadius: 5,
    justifyContent: 'center',
    // alignContent: 'center',
  },

  listLeft: {
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  cashLabelWhite: {
    color: COLORS.lavender,
    fontSize: SF(14),
    fontFamily: Fonts.Medium,
  },
  cashLabelWhiteHash: {
    paddingHorizontal: moderateScale(15),
  },
  tableListSide: {
    width: windowWidth * 0.22,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },

  tableListSide2: {
    width: windowWidth * 0.4,
    paddingRight: 20,
    alignItems: 'center',
  },
  blueListData: {
    borderWidth: 1,
    height: SH(70),
    borderRadius: 5,
    borderColor: COLORS.solidGrey,
    justifyContent: 'center',
    marginVertical: verticalScale(2),
  },
  blueListDataText: {
    color: COLORS.navy_blue,
    fontSize: SF(13),
    fontFamily: Fonts.Regular,
  },
  columbiaMen: {
    width: ms(18),
    height: ms(18),
    resizeMode: 'contain',
  },
  cartImageCon: {
    width: ms(25),
    height: ms(25),
    resizeMode: 'contain',
    backgroundColor: COLORS.textInputBackground,
    borderRadius: ms(5),
    justifyContent: 'center',
    alignItems: 'center',
  },
  cartItemImage: {
    width: SW(15),
    height: SW(15),
    resizeMode: 'contain',
  },
  minus: {
    width: SW(5),
    height: SW(5),
    resizeMode: 'contain',
  },
  sukNumber: {
    color: COLORS.lavender,
    fontSize: SF(10),
    fontFamily: Fonts.Regular,
  },
  listCountCon: {
    borderWidth: 1,
    width: SW(30),
    height: SH(35),
    borderRadius: ms(4),
    borderColor: COLORS.light_purple,
    // paddingVertical: verticalScale(1),
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: moderateScale(4),
    alignItems: 'center',
  },
  borderCross: {
    width: ms(13),
    height: ms(13),
    resizeMode: 'contain',
    tintColor: COLORS.red,
  },
  _subTotalContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    // width: '80%',
  },
  totalView: {
    backgroundColor: COLORS.textInputBackground,
    height: ms(25),
    paddingHorizontal: ms(10),
    justifyContent: 'center',
    borderRadius: ms(12),
  },
  _substotalTile: {
    color: COLORS.black,
    fontFamily: Fonts.Regular,
    fontSize: ms(5.5),
    marginTop: ms(3),
  },
  _subTotalPrice: {
    color: COLORS.solid_grey,
    fontFamily: Fonts.Regular,
    fontSize: ms(5.5),
    marginTop: ms(4),
  },
  _horizontalLine: {
    // height: ms(1),
    borderWidth: 0.5,
    width: '90%',
    marginTop: ms(4),
    borderColor: COLORS.light_purple,
  },

  _paymentTitleContainer: {
    marginTop: ms(5),
    flexDirection: 'row',
    alignSelf: 'flex-start',
    marginLeft: ms(15),
  },
  _payTitle: {
    fontSize: ms(7),
    fontFamily: Fonts.Medium,
    color: COLORS.navy_blue,
  },
  _paySubTitle: {
    fontSize: ms(7),
    fontFamily: Fonts.SemiBold,
    color: COLORS.navy_blue,
  },
  _commonPayTitle: {
    alignSelf: 'flex-start',
    marginLeft: ms(15),
    marginTop: ms(3),
    fontSize: ms(7),
    color: COLORS.navy_blue,
    fontFamily: Fonts.Regular,
  },
  boldInvoice: {
    alignSelf: 'center',
    fontFamily: Fonts.SemiBold,
  },
  _upperContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    width: '100%',
    flex: 1,
  },
  _kUpperContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  _kContainer: {
    height: ms(200),
    width: ms(300),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: ms(5),
    ...ShadowStyles.shadow2,
    backgroundColor: COLORS.white,
  },
  _kCenterContainer: {
    height: '100%',
    alignSelf: 'flex-end',
    flex: 0.6,
    borderLeftWidth: 1,
    borderColor: COLORS.textInputBackground,
    alignItems: 'center',
  },
  _kSubCenterContainer: {
    color: COLORS.navy_blue,
    fontFamily: Fonts.SemiBold,
    fontSize: ms(8),
    marginTop: ms(5),
  },
  _kAddress: {
    color: COLORS.navy_blue,
    fontFamily: Fonts.Medium,
    fontSize: ms(7),
    marginTop: ms(5),
    paddingHorizontal: ms(5),
    textAlign: 'center',
  },
  _kNumber: {
    color: COLORS.navy_blue,
    fontFamily: Fonts.Medium,
    fontSize: ms(7),
    marginTop: ms(3),
  },
  _flatListContainer: {
    // height: ms(100),
    width: '100%',
    marginTop: ms(5),
    flex: 1,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: COLORS.light_purple,
  },

  _barCode: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(10),
    color: COLORS.dark_grey,
  },
  _barCodeImage: { height: ms(25), width: '70%', marginTop: ms(2) },
  _thankyou: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(11),
    color: COLORS.dark_grey,
    marginTop: ms(10),
  },
  _cashRemainView: {
    marginTop: ms(15),
    height: 1,
    width: '50%',
    backgroundColor: COLORS.light_purple,
  },

  _printButton: {
    width: '30%',
    height: ms(26),
    backgroundColor: 'transparent',
    borderColor: COLORS.lineGrey,
    borderWidth: 0.2,
    borderRadius: ms(1),
    marginHorizontal: moderateScale(5),
  },
  _printBtnText: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(7),
    color: COLORS.darkGray,
    fontWeight: 'normal',
  },
  noProductText: {
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: verticalScale(50),
  },
  emptyListText: {
    fontSize: SF(16),
    color: COLORS.primary,
    fontFamily: Fonts.Regular,
  },
  productListHeight: {
    height: windowHeight * 0.7,
  },
  loader: {
    position: 'absolute',
    alignSelf: 'center',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
  },
  addNotesCon: {
    backgroundColor: 'white',
    borderRadius: 10,
    width: windowWidth * 0.35,
    height: windowHeight * 0.45,
    // position: 'absolute',
    alignSelf: 'center',
    justifyContent: 'center',
    paddingHorizontal: moderateScale(13),
  },
  addNotesCon2: {
    paddingHorizontal: moderateScale(8),
    borderRadius: ms(15),
  },
  addDiscountConPop: {
    height: windowHeight * 0.55,
  },
  addNotesInput1: {
    backgroundColor: COLORS.white,
    borderRadius: ms(10),
    height: ms(140),
    textAlignVertical: 'top',
    borderColor: COLORS.light_purple,
    borderWidth: 1,
    paddingHorizontal: moderateScale(10),
    color: COLORS.navy_blue,
    fontSize: ms(10),
  },
  addNotes: {
    fontSize: SF(14),
    color: COLORS.solid_grey,
    fontFamily: Fonts.Medium,
  },
  backProScreen: {
    flexDirection: 'row',
    justifyContent: 'center',
    // alignItems: 'center',
    marginHorizontal: ms(10),
  },
  arrowStyle: {
    width: SW(8),
    height: SW(8),
    resizeMode: 'contain',
    tintColor: COLORS.navy_blue,
  },
  fullCartText: {
    color: COLORS.navy_blue,
    fontSize: ms(12),
    fontFamily: Fonts.SemiBold,
  },
  iconStyle: {
    width: SW(8),
    height: SW(8),
    resizeMode: 'contain',
    borderRadius: 100,
    marginRight: ms(3),
  },
  _blueButton: {
    backgroundColor: COLORS.primary,
    height: ms(40),
    width: '98%',
    marginTop: ms(10),
    color: COLORS.white,
  },

  cancelCatCon: {
    width: SW(30),
    height: SW(10),
    backgroundColor: COLORS.red,
    borderRadius: 8,
    marginHorizontal: moderateScale(20),
    alignItems: 'center',
    justifyContent: 'center',
  },
  catCancelText: {
    color: COLORS.white,
    fontSize: SF(12),
    fontFamily: Fonts.SemiBold,
  },
  categoryEmptyList: {
    fontSize: SF(22),
    color: COLORS.primary,
    fontFamily: Fonts.Regular,
    alignSelf: 'center',
  },

  // ******new desgin css  start******

  container: {
    flex: 1,
    backgroundColor: COLORS.textInputBackground,
  },
  displayRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  displayflex2: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },

  homeScreenCon: {
    flex: 1,
    backgroundColor: COLORS.textInputBackground,
    // paddingHorizontal: Platform.OS === 'android' ? moderateScale(12) : moderateScale(12),
  },
  productView: {
    backgroundColor: Colors.white,
    borderRadius: ms(12),
    flex: 0.99,
    paddingTop: verticalScale(6),
    paddingHorizontal: moderateScale(10),
    marginRight: ms(7),
  },
  rightSideView: {
    backgroundColor: Colors.white,
    borderRadius: ms(30),
    flex: 0.09,
    paddingVertical: verticalScale(15),
    alignItems: 'center',
    marginRight: ms(7),
  },
  sideBarImage: {
    width: SW(9),
    height: SW(9),
    resizeMode: 'contain',
  },
  mainScreenArrow: (value) => {
    return {
      width: SW(9),
      height: SW(9),
      resizeMode: 'contain',
      transform: [{ rotate: '90deg' }],
      tintColor: value ? COLORS.sky_blue : COLORS.navy_blue,
    };
  },
  crossImage: {
    width: SW(10),
    height: SW(10),
    resizeMode: 'contain',
    tintColor: COLORS.darkGray,
  },
  crossView: {
    width: SW(10),
    height: SW(10),
    position: 'absolute',
    right: ms(5),
    top: ms(2),
    justifyContent: 'center',
    alignItems: 'center',
  },
  bucketBackgorund: {
    width: SW(17),
    height: SW(17),
    borderRadius: ms(8),
    backgroundColor: COLORS.textInputBackground,
    justifyContent: 'center',
    alignItems: 'center',
  },
  chooseCategoryCon: {
    borderWidth: 1,
    borderColor: COLORS.solidGrey,
    borderRadius: 7,
    width: windowWidth * 0.15,
    height: SH(45),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: moderateScale(7),
    marginHorizontal: moderateVerticalScale(5),
  },
  chooseCat: {
    color: COLORS.black,
    fontSize: SF(13),
    fontFamily: Fonts.Medium,
    width: windowWidth * 0.11,
  },

  barcodeInputWraper: {
    flex: 1,

    borderColor: COLORS.solidGrey,
    backgroundColor: COLORS.textInputBackground,
    borderRadius: ms(30),
    // width: Platform.OS === 'android' ? windowWidth * 0.38 : windowWidth * 0.3,
    height: SH(45),
    justifyContent: 'center',
  },
  cartSearchInputWraper: {
    width: windowWidth * 0.42,
    paddingHorizontal: ms(5),
  },

  productImageStyle: {
    width: SW(6),
    height: SW(6),
    resizeMode: 'contain',
    marginHorizontal: ms(4),
  },

  crossStyling: {
    width: SW(4),
    height: SW(4),
  },
  sideBarsearchInput: {
    flex: 0.9,
    borderRadius: 7,
    fontFamily: Fonts.Medium,
    fontSize: SF(13),
    color: COLORS.lavender,
    height: SH(40),
  },
  searchCartInput: {
    width: windowWidth * 0.35,
  },

  productCount: {
    color: COLORS.lavender,
    fontSize: SF(14),
    fontFamily: Fonts.Medium,
  },
  hr: {
    borderWidth: 0.4,
    borderColor: COLORS.solidGrey,
  },
  productCon: (qty) => {
    return {
      width: Platform.OS === 'ios' ? ms(85) : ms(95),
      backgroundColor: COLORS.white,
      borderRadius: ms(9),
      marginTop: verticalScale(7),
      marginRight: 10,
      borderWidth: 1,
      borderColor: COLORS.textInputBackground,
      ...(qty > 0 && { ...ShadowStyles.shadow }),
    };
  },
  serviceCon: (qty) => {
    return {
      width: Platform.OS === 'ios' ? ms(102) : ms(112),
      backgroundColor: COLORS.white,
      borderRadius: ms(9),
      marginTop: verticalScale(7),
      marginRight: 10,
      borderWidth: 1,
      borderColor: COLORS.textInputBackground,
      ...(qty > 0 && { ...ShadowStyles.shadow }),
    };
  },
  categoryshoes: {
    width: Platform.OS === 'ios' ? ms(75) : ms(85),
    height: windowHeight * 0.11,
    resizeMode: 'contain',
    alignSelf: 'center',
    marginTop: ms(6),
  },
  serviceImagemain: {
    // width: Platform.OS === 'ios' ? ms(75) : ms(85),
    width: '100%',
    height: ms(60),
    resizeMode: 'contain',
    borderRadius: ms(9),
  },

  productSubHead: {
    color: COLORS.lavender,
    fontSize: ms(8),
    fontFamily: Fonts.Medium,
  },
  productPrice: {
    color: COLORS.navy_blue,
    fontSize: ms(8),
    fontFamily: Fonts.SemiBold,
  },
  serviceTimeCon: {
    backgroundColor: COLORS.textInputBackground,
    height: ms(18),
    borderRadius: ms(12),
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: ms(3),
  },
  calendarStyle: {
    width: ms(10),
    height: ms(10),
    resizeMode: 'contain',
    tintColor: COLORS.light_time,
    marginHorizontal: ms(3),
  },
  serviceTimeText: {
    color: COLORS.light_time,
    fontSize: ms(6),
    fontFamily: Fonts.Medium,
  },
  addToCart: {
    width: ms(28),
    height: ms(28),
    resizeMode: 'contain',
  },
  sideAddToCart: {
    width: ms(10),
    height: ms(10),
    resizeMode: 'contain',
    tintColor: COLORS.extraYellow,
  },
  bucketBadge: {
    borderWidth: 2,
    width: Platform.OS === 'ios' ? ms(11) : ms(13),
    height: Platform.OS === 'ios' ? ms(11) : ms(13),
    borderRadius: ms(10),
    position: 'absolute',
    right: Platform.OS === 'ios' ? 7 : 8,
    bottom: Platform.OS === 'ios' ? 6 : 7,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: COLORS.dark_grey,
    backgroundColor: COLORS.solidGrey,
  },
  productBadge: {
    width: ms(10),
    height: ms(10),
    borderRadius: ms(10),
    position: 'absolute',
    right: 0,
    top: 0,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: COLORS.dark_grey,
    backgroundColor: COLORS.primary,
  },
  bucketBadgePrimary: {
    borderColor: COLORS.white,
    backgroundColor: COLORS.navy_blue,
  },
  badgetext: {
    color: COLORS.dark_grey,
    fontSize: SF(11),
    fontFamily: Fonts.SemiBold,
  },
  productBadgeText: {
    color: COLORS.white,
    fontSize: SF(11),
    fontFamily: Fonts.Regular,
  },

  holdBadge: {
    borderWidth: 2,
    width: ms(13),
    height: ms(13),
    borderRadius: ms(10),
    position: 'absolute',
    right: -9,
    bottom: -8,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: COLORS.gerySkies,
    backgroundColor: COLORS.white,
  },

  filterBadge: {
    borderWidth: 2,
    width: ms(11),
    height: ms(11),
    borderRadius: ms(10),
    position: 'absolute',
    right: -5,
    bottom: -6,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: COLORS.primary,
    backgroundColor: COLORS.white,
  },
  serviceFilterBadge: {
    borderWidth: 1,
    width: ms(10),
    height: ms(10),
    borderRadius: ms(10),
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: COLORS.navy_blue,
    backgroundColor: COLORS.white,
  },
  holdBadgePrimary: {
    backgroundColor: COLORS.navy_blue,
    borderColor: COLORS.white,
  },
  holdBadgetext: {
    color: COLORS.gerySkies,
    fontSize: SF(11),
    fontFamily: Fonts.SemiBold,
  },
  filterBadgeText: {
    color: COLORS.primary,
    fontSize: SF(10),
    fontFamily: Fonts.SemiBold,
    // textAlign: 'center',
  },

  //NEW DESIGN

  //Tip
  _payBYBoxContainerTip: (selectedTipIndex, index) => {
    return {
      borderColor: selectedTipIndex === index ? COLORS.tip_blue : COLORS.tip_border,
      borderWidth: 1,
      height: ms(60),
      width: Platform.OS === 'ios' ? ms(90) : ms(116),
      marginHorizontal: ms(3),
      borderRadius: ms(10),
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: selectedTipIndex === index ? COLORS.tip_blue : COLORS.tip_back,
    };
  },

  _payByAmountTip: (selectedTipIndex, index) => {
    return {
      fontFamily: Fonts.Regular,
      color: selectedTipIndex === index ? COLORS.white : COLORS.purple,
      fontSize: ms(8),
      marginTop: ms(4),
    };
  },
  _payByMethodTip: (selectedTipIndex, index) => {
    return {
      fontFamily: Fonts.SemiBold,
      color: selectedTipIndex === index ? COLORS.white : COLORS.purple,
      fontSize: ms(13),
      marginTop: ms(4),
    };
  },

  //Recipe

  _payBYBoxContainerReceipe: (selectedRecipeIndex, index) => {
    return {
      borderColor: COLORS.faded_yellow,
      borderWidth: 1,
      height: ms(60),
      width: Platform.OS === 'ios' ? ms(100) : ms(135),
      margin: ms(3),
      borderRadius: ms(9),
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: selectedRecipeIndex === index ? COLORS.orange_bright : COLORS.light_yellow,
    };
  },
  recipeIcon: (selectedRecipeIndex, index) => {
    return {
      height: ms(18),
      width: ms(18),
      resizeMode: 'contain',
      // tintColor: selectedRecipeIndex === index ? COLORS.white : COLORS.redish_brown,
    };
  },
  _payBYBoxContainerReceipeEmpty: {
    height: ms(50),
    width: ms(170),
    margin: ms(3),
    justifyContent: 'center',
    alignItems: 'center',
  },
  _payByAmountReceipe: {
    fontFamily: Fonts.Regular,
    color: COLORS.solid_grey,
    fontSize: ms(9),
    marginTop: ms(4),
  },
  _payByMethodReceipe: (selectedRecipeIndex, index) => {
    return {
      fontFamily: Fonts.Medium,
      color: selectedRecipeIndex === index ? COLORS.white : COLORS.redish_brown,
      fontSize: ms(10),
    };
  },
  selectTips: {
    fontSize: ms(11),
    margin: ms(10),
    fontFamily: Fonts.Medium,
    color: COLORS.navy_blue,
    alignSelf: 'center',
  },
  saveView: {
    backgroundColor: COLORS.save_yellow,
    height: ms(18),
    width: ms(60),
    margin: ms(3),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: ms(9),
  },
  saveText1: {
    fontSize: ms(8),
    fontFamily: Fonts.SemiBold,
    color: COLORS.navy_blue,
  },
  _kCenterContainer: {
    height: '100%',
    alignSelf: 'flex-end',
    flex: 0.6,
    borderLeftWidth: 1,
    borderColor: COLORS.textInputBackground,
    alignItems: 'center',
  },

  _barCode: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(10),
    color: COLORS.dark_grey,
  },
  _barCodeImage: { height: ms(25), width: '70%', marginTop: ms(5) },
  _thankyou: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(11),
    color: COLORS.dark_grey,
    marginTop: ms(10),
  },
  _cashRemainView: {
    marginTop: ms(15),
    height: 1,
    width: '50%',
    backgroundColor: COLORS.silver_solid,
  },
  _cashRemainText: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(15),
    color: COLORS.navy_blue,
    marginTop: ms(10),
  },
  _printButton: {
    width: '30%',
    height: ms(26),
    backgroundColor: 'transparent',
    borderColor: COLORS.lineGrey,
    borderWidth: 0.2,
    borderRadius: ms(1),
    marginHorizontal: moderateScale(5),
  },
  _printBtnText: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(7),
    color: COLORS.darkGray,
    fontWeight: 'normal',
  },
  noProductText: {
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: verticalScale(50),
  },
  emptyListText: {
    fontSize: SF(16),
    color: COLORS.primary,
    fontFamily: Fonts.Regular,
  },

  avaliableOferBodyCon: {
    height: ms(45),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    padding: ms(7),
  },
  offerImagebackground: {
    width: ms(20),
    height: ms(20),
    backgroundColor: COLORS.light_yellow,
    borderRadius: ms(4),
    justifyContent: 'center',
    alignItems: 'center',
  },
  offerImage: {
    width: ms(20),
    height: ms(20),
    resizeMode: 'contain',
    borderRadius: ms(4),
  },
  offerText: {
    color: COLORS.coffee,
    fontSize: ms(8),
    fontFamily: Fonts.Medium,
  },
  offerTextYellow: {
    color: COLORS.extraYellow,
  },
  offerPrice: {
    color: COLORS.extraYellow,
    fontSize: ms(8),
    fontFamily: Fonts.Medium,
  },
  lineTrought: {
    textDecorationLine: 'line-through',
  },
  offerPriceDark: {
    color: COLORS.coffee,
    fontSize: ms(8),
    fontFamily: Fonts.Medium,
    textDecorationLine: 'none',
  },
  cartListModalView: {
    width: windowWidth * 0.43,
    height: windowHeight * 0.9,
    backgroundColor: COLORS.white,
    position: 'absolute',
    bottom: -50,
    right: -50,
    borderRadius: 10,
    padding: 18,
  },
  shortestCartListBody: {
    width: windowWidth * 0.35,
  },
  cartListIconBody: {
    width: windowWidth * 0.04,
  },
  carttoAdd: {
    color: COLORS.dark_grey,
    fontSize: SF(17),
    fontFamily: Fonts.MaisonBold,
    marginLeft: 8,
  },
  shortCartListData: {
    borderWidth: 1,
    width: windowWidth * 0.35,
    height: SH(48),
    borderRadius: 5,
    borderColor: COLORS.solidGrey,
    justifyContent: 'center',
    marginVertical: verticalScale(2),
    paddingHorizontal: ms(5),
  },
  shorttableListSide: {
    width: windowWidth * 0.12,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  ShorttableListSide2: {
    width: windowWidth * 0.23,
    flexDirection: 'row',
    paddingHorizontal: ms(5),
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  shortCartListHeight: {
    height: windowHeight * 0.7,
  },

  //PHONE POPUP
  calendarSettingModalContainer: {
    width: windowWidth * 0.4,
    height: windowHeight * 0.84,
    backgroundColor: 'white',
    alignSelf: 'center',
    borderRadius: 7,
    alignItems: 'center',
    borderWidth: 1,
    paddingHorizontal: moderateVerticalScale(7),
    paddingVertical: verticalScale(15),
    position: 'absolute',
  },
  _btnContainer: {
    flexDirection: 'row',
    alignSelf: 'center',
    width: windowWidth * 0.35,
  },
  declineBtnContainer: {
    height: ms(40),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.textInputBackground,
    flex: 1,
    borderRadius: ms(3),
  },
  acceptbtnContainer: {
    height: ms(40),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.primary,
    flex: 1,
    borderRadius: ms(3),
    marginLeft: ms(8),
  },
  declineText: {
    fontFamily: Fonts.Regular,
    fontSize: ms(8),
    color: COLORS.dark_grey,
  },

  input: {
    width: '90%',
    height: 70,
    borderWidth: 1,
    borderColor: '#ccc',
    paddingHorizontal: 10,
    marginBottom: 20,
  },
  numberPad: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: windowWidth * 0.35,
    marginVertical: SW(7),
  },
  submitButton: {
    backgroundColor: COLORS.primary,
    width: windowWidth * 0.32,
    height: SH(60),
  },
  buttonText: {
    color: COLORS.darkGray,
    fontSize: SF(14),
    fontFamily: Fonts.SemiBold,
  },

  keyPadButton: {
    height: SH(110),
    width: SH(125),
    justifyContent: 'center',
    borderColor: COLORS.gerySkies,
    alignItems: 'center',
    borderWidth: 0.3,
    // borderRadius: 5,
    // overflow: 'hidden',
  },
  outerBorderRadius: {
    borderRadius: 5,
    overflow: 'hidden',
  },
  keyPadText: {
    fontSize: SH(28),
    fontFamily: Fonts.Medium,
    color: COLORS.solid_grey,
  },
  textInputView: {
    paddingHorizontal: SW(4),
    borderWidth: 0,
    alignItems: 'center',
    flexDirection: 'row',
    height: windowHeight * 0.08,
    width: windowWidth * 0.33,
    borderWidth: 1,
    borderColor: '#D8D8D8',
    borderRadius: 5,
  },
  textInputView2: {
    paddingHorizontal: SW(4),
    borderWidth: 0,
    alignItems: 'center',
    flexDirection: 'row',
    height: windowHeight * 0.08,
    width: windowWidth * 0.25,
    borderWidth: 1,
    borderColor: '#D8D8D8',
    borderRadius: 5,
  },
  dropDownIcon: {
    width: 7,
    height: 7,
    resizeMode: 'contain',
  },
  countryCodeText: {
    color: COLORS.black,
    fontSize: SF(18),
    fontFamily: Fonts.Regular,
    paddingHorizontal: moderateScale(8),
  },
  textInputContainer: {
    color: COLORS.black,
    fontSize: SF(16),
    fontFamily: Fonts.Italic,
    width: windowWidth * 0.2,
  },

  jobrSaveView: {
    borderColor: COLORS.primary,
    borderWidth: 1,
    height: ms(50),
    // width: ms(40),
    margin: ms(3),
    borderRadius: ms(6),
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: ms(25),
  },
  youSave: {
    fontFamily: Fonts.Regular,
    color: COLORS.primary,
    fontSize: ms(9),
    marginBottom: ms(5),
  },
  saveJBR: {
    fontFamily: Fonts.SemiBold,
    color: COLORS.primary,
    fontSize: ms(14),
    marginTop: ms(4),
  },

  jbrContainer: {
    flexDirection: 'row',
    alignItems: 'baseline', // To align "JBR" and the percentage value on the same baseline
  },
  jbrText: {
    fontFamily: Fonts.Bold,
    color: COLORS.primary,
    fontSize: ms(11),

    marginTop: ms(4),
    alignSelf: 'flex-start',
    marginRight: ms(3),
    // You can apply any other styles you want for "JBR"
  },
  savePercent: {
    fontFamily: Fonts.Bold,
    color: COLORS.primary,
    fontSize: ms(15),
    marginTop: ms(4), // Set your desired font size for the percentage value
    // Add any other styles you want for the percentage value here
  },

  //Email Modal

  emailModalContainer: {
    width: ms(350),
    height: ms(160),
    backgroundColor: 'white',
    // padding: ms(10),
    paddingVertical: ms(15),
    alignSelf: 'center',
    borderRadius: ms(10),
    alignItems: 'center',
  },
  modalHeaderCon: {
    height: SH(80),
    width: ms(300),
    // paddingHorizontal: moderateScale(0),
    justifyContent: 'center',
  },
  crossButton: {
    width: SW(9),
    height: SW(9),
    resizeMode: 'contain',
  },
  crossButtonCon: {
    width: SW(13),
    height: SW(13),
    // justifyContent: 'center',
    alignItems: 'center',
  },
  modalDataCon: {
    width: windowWidth * 0.38,
    alignSelf: 'center',
    flex: 1,
  },
  flexRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  twoStepText: {
    fontSize: SF(25),
    fontFamily: Fonts.MaisonBold,
    color: COLORS.black,
    textAlign: 'left',
  },

  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 5,
    width: ms(300),
    height: ms(40),
    marginTop: ms(25),
    padding: 15,
  },
  textInput: {
    flex: 1,
    height: 45,
    fontSize: ms(10),
    paddingHorizontal: 15,
  },
  payNowButton: {
    height: ms(30),
    width: ms(70),
    backgroundColor: COLORS.darkGray,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    // marginHorizontal:ms(5)
  },
  payNowButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },

  //  final payment design css start
  leftCon: {
    backgroundColor: COLORS.white,
    borderRadius: ms(12),
    flex: 0.7,
    marginRight: ms(7),
  },
  rightCon: {
    backgroundColor: COLORS.white,
    borderRadius: ms(12),
    flex: 0.3,
    marginRight: ms(7),
    paddingVertical: ms(8),
  },
  //  final payment design css end

  selectTipsHeader: {
    borderTopLeftRadius: 8,
    borderTopEndRadius: 8,
    paddingVertical: verticalScale(6),
    borderWidth: 1,
  },

  // jbrcoin modal popup
  scanPopUpCon: {
    width: ms(460),
    height: ms(460),
    backgroundColor: COLORS.white,
    alignSelf: 'center',
    borderRadius: 10,
  },
  scanPopHeader: {
    borderBottomWidth: 1,
    height: ms(35),
    paddingHorizontal: ms(15),
    justifyContent: 'center',
    alignItems: 'flex-end',
    borderColor: COLORS.solidGrey,
  },
  prouductAndServiceCon: {
    // borderWidth: 1,
    width: Platform.OS === 'ios' ? windowWidth * 0.12 : windowWidth * 0.09,
    height: SH(45),
    borderRadius: ms(30),
    borderColor: COLORS.solidGrey,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginHorizontal: ms(5),
    backgroundColor: COLORS.textInputBackground,
  },
  productText: {
    fontSize: ms(7),
    fontFamily: Fonts.SemiBold,
    color: COLORS.navy_blue,
  },
  productTextBlue: {
    fontSize: ms(7),
    fontFamily: Fonts.SemiBold,
    color: COLORS.white,
  },
  allProductSection: {
    width: windowWidth * 0.12,
  },

  avalibleServiceCon: {
    overflow: 'hidden',
    height: ms(60),
    borderRadius: ms(9),
    // borderWidth: 1,
  },
  availableTimeCon: {
    backgroundColor: COLORS.darkGray,
    width: Platform.OS === 'ios' ? windowWidth * 0.095 : windowWidth * 0.1,
    height: windowHeight * 0.035,
    borderBottomEndRadius: 5,
    borderBottomLeftRadius: 5,
    justifyContent: 'center',
    paddingHorizontal: ms(3),
  },
  availableTime: {
    fontSize: SF(7),
    fontFamily: Fonts.Italic,
    color: COLORS.white,
  },
  categoryFilterCon: {
    zIndex: 999,
    position: 'absolute',
    right: 0,
    top: 72,
    borderRadius: 5,
    width: windowWidth * 0.3,
    height: windowHeight * 0.8,
    backgroundColor: COLORS.textInputBackground,
  },
  selected: {
    fontSize: SF(16),
    fontFamily: Fonts.SemiBold,
    color: COLORS.solid_grey,
  },
  imageSelectedBorder: {
    borderWidth: 5,
    marginHorizontal: moderateScale(5),
    borderRadius: 100,
    borderColor: COLORS.primary,
  },

  cartHeaderLeftSide: {
    flexDirection: 'row',
    width: windowWidth * 0.18,
  },
  cartHeaderRightSide: {
    flexDirection: 'row',
    width: windowWidth * 0.43,
  },
  cartHeaderBodyRightSide: {
    color: COLORS.white,
    fontSize: SF(14),
    fontFamily: Fonts.Medium,
    width: windowWidth * 0.09,
  },
  ItemHeader: {
    color: COLORS.white,
    fontSize: SF(14),
    fontFamily: Fonts.Medium,
    width: windowWidth * 0.13,
  },
  cartBodyRightSide: {
    color: COLORS.solid_grey,
    fontSize: SF(13),
    fontFamily: Fonts.Regular,
    width: windowWidth * 0.09,
    textAlignVertical: 'center',
    // borderWidth: 1,
    paddingLeft: ms(10),
  },

  noProductAndService: {
    color: COLORS.red,
    fontSize: SF(20),
    fontFamily: Fonts.MaisonRegular,
  },
  noproductServiceCon: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: ms(50),
  },
  noDataText: {
    fontFamily: Fonts.Regular,
    textAlign: 'center',
    color: COLORS.primary,
    marginTop: ms(10),
  },
  shortServiceItalic: {
    fontFamily: Fonts.Italic,
    color: COLORS.solid_grey,
    fontSize: ms(6),
  },
  serviceCartImage: {
    width: ms(20),
    height: ms(20),
    resizeMode: 'contain',
    borderRadius: 5,
  },
  scnStyle: {
    width: SW(15),
    height: SW(16),
    resizeMode: 'contain',
  },
  cartEditCon: {
    marginRight: ms(18),
  },

  cartEdit: {
    width: SW(7),
    height: SW(7),
    resizeMode: 'contain',
  },

  // custom product add modal css start
  headerConCustomProduct: {
    borderBottomWidth: 1,
    height: ms(40),
    borderColor: COLORS.solidGrey,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: ms(12),
  },

  addCartbtnBodyCon: {
    marginTop: ms(15),
    borderWidth: 1,
    height: ms(55),
    borderColor: COLORS.solidGrey,
    borderRadius: ms(3),
    flexDirection: 'row',
    justifyContent: 'space-between',
  },

  customProductCon: {
    width: ms(260),
    height: ms(280),
    backgroundColor: COLORS.white,
    alignSelf: 'center',
    borderRadius: ms(15),
    // padding: ms(10),
    // marginTop: Platform.OS === 'android' ? ms(10) : ms(50),
  },
  dollarAddCon: {
    height: ms(32),
    borderRadius: 5,
    backgroundColor: COLORS.textInputBackground,
    paddingHorizontal: ms(10),
    // justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
  },
  dollar: {
    width: ms(13),
    height: ms(13),
    resizeMode: 'contain',
  },
  dollarInput: {
    flex: 1,
    paddingHorizontal: ms(5),
    fontFamily: Fonts.Medium,
    fontSize: ms(11),
  },
  productNameInput: {
    marginTop: ms(15),
    height: ms(32),
    borderRadius: 5,
    borderColor: COLORS.solidGrey,
    borderWidth: 1,
    paddingHorizontal: ms(10),
    fontSize: ms(8),
  },
  addNotesInput: {
    marginTop: ms(10),
    height: ms(55),
    borderRadius: 5,
    borderColor: COLORS.solidGrey,
    borderWidth: 1,
    paddingHorizontal: ms(10),
    fontSize: ms(8),
    textAlignVertical: 'top',
  },
  closeButtonCon: {
    height: ms(54),
    width: ms(110),
    borderColor: COLORS.gerySkies,
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomEndRadius: ms(3),
    borderTopEndRadius: ms(3),
    borderWidth: 1,
  },
  closeText: {
    fontFamily: Fonts.SemiBold,
    color: COLORS.solid_grey,
    fontSize: ms(8),
  },
  customAddQtyCon: {
    height: ms(35),
    borderWidth: 1,
    flex: 1,
    borderColor: COLORS.solidGrey,
    marginHorizontal: ms(10),
    paddingHorizontal: ms(10),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  plusButton: {
    width: ms(18),
    height: ms(18),
    resizeMode: 'contain',
  },
  zeroText: {
    fontFamily: Fonts.SemiBold,
    color: COLORS.solid_grey,
    fontSize: ms(11),
  },

  unitPriceInput: {
    backgroundColor: COLORS.solidGrey,
    width: Platform.OS === 'android' ? ms(50) : ms(38),
    height: ms(20),
    padding: 0,
    margin: 0,
    textAlign: 'center',
    color: COLORS.solid_grey,
    fontSize: SF(13),
    fontFamily: Fonts.Regular,
    borderRadius: ms(4),
    paddingHorizontal: ms(3),
  },
  unitPriceInputWidth: {
    width: Platform.OS === 'android' ? ms(44) : ms(57),
  },
  saveButtonCon: {
    width: Platform.OS === 'android' ? ms(37) : ms(30),
    height: ms(20),
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    marginRight: ms(5),
  },
  saveText: {
    fontFamily: Fonts.Regular,
    color: COLORS.white,
    fontSize: ms(7),
  },
  productCartBodyRight: {
    // borderWidth: 1,
    width: Platform.OS === 'android' ? ms(330) : ms(240),
    height: ms(20),
    flexDirection: 'row',
  },
  productCartBody: {
    // borderWidth: 1,
    width: Platform.OS === 'android' ? ms(82) : ms(60),
    height: ms(20),
    alignItems: 'center',
    justifyContent: 'center',
  },
  serviceCartRightBody: {
    width: Platform.OS === 'android' ? ms(360) : ms(280),
    height: ms(20),
    flexDirection: 'row',
  },
  serviceCartBody: {
    width: Platform.OS === 'android' ? ms(68) : ms(52),
    height: ms(20),
    alignItems: 'center',
    justifyContent: 'center',
  },
  cartHeaderBodyRighSide: {
    color: COLORS.lavender,
    fontSize: SF(14),
    fontFamily: Fonts.Medium,
  },
  counterMainCon: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  oneCon: {
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: COLORS.solidGrey,
    width: ms(160),
    justifyContent: 'center',
    alignItems: 'center',
  },
  minusCon: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoFull: {
    width: ms(90),
    height: ms(30),
    resizeMode: 'contain',
    tintColor: COLORS.navy_blue,
    alignSelf: 'center',
  },

  dropDownIcon: {
    width: 7,
    height: 7,
    resizeMode: 'contain',
  },
  countryCodeText: {
    color: COLORS.black,
    fontSize: SF(15),
    fontFamily: Fonts.Regular,
    paddingHorizontal: moderateScale(8),
  },
  textInputContainer: {
    backgroundColor: COLORS.input_bg,
    color: COLORS.black,
    fontSize: SF(16),
    fontFamily: Fonts.Italic,
    width: windowWidth * 0.2,
  },

  phoneCodeNewCustomerView: {
    paddingHorizontal: SW(4),
    borderWidth: 0,
    alignItems: 'center',
    flexDirection: 'row',
    height: windowHeight * 0.07,
    backgroundColor: COLORS.textInputBackground,
    borderRadius: 5,
    fontFamily: Fonts.Italic,
  },
  newCusAdd: {
    color: COLORS.dark_grey,
    fontSize: ms(7),
    fontFamily: Fonts.Medium,
    marginVertical: ms(4),
  },
  searchCustomerCon: {
    borderWidth: 1,
    height: windowHeight * 0.07,
    borderRadius: 10,
    borderColor: COLORS.solidGrey,
    paddingHorizontal: SW(2),
    alignItems: 'center',
    flexDirection: 'row',
  },
  sideSearchStyle: {
    width: SW(8),
    height: SW(8),
    resizeMode: 'contain',
    marginLeft: moderateScale(5),
    marginRight: moderateScale(5),
    tintColor: COLORS.navy_blue,
  },
  searchCustomerInput: {
    flex: 1,
    fontFamily: Fonts.Italic,
    fontSize: SF(12),
    color: COLORS.solid_grey,
  },

  newFirstName: {
    width: ms(140),
    height: windowHeight * 0.07,
    backgroundColor: COLORS.textInputBackground,
    borderRadius: 5,
    fontFamily: Fonts.Italic,
    paddingHorizontal: SW(4),
  },
  customerNotSystem: {
    fontFamily: Fonts.Regular,
    fontSize: ms(7),
    color: COLORS.red,
    marginVertical: ms(4),
  },
  customerDarkLabel: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(8),
    color: COLORS.solid_grey,
  },
  customerLightdata: {
    fontFamily: Fonts.Regular,
    fontSize: ms(9),
    color: COLORS.darkGray,
    marginTop: ms(3),
  },
  scnStyle: {
    width: SW(16),
    height: ms(32),
    resizeMode: 'contain',
  },
  upcInputContainer: {
    marginTop: ms(15),
    height: ms(32),
    borderRadius: 5,
    borderColor: COLORS.solidGrey,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    // paddingHorizontal: ms(10),
    // fontSize: ms(8),
  },
  upcInput: {
    flex: 1,
    height: ms(32),
    borderRadius: 5,
    borderColor: COLORS.solidGrey,
    paddingHorizontal: ms(10),
    fontSize: ms(8),
  },
  detailColorSize: {
    fontFamily: Fonts.Regular,
    fontSize: ms(8),
    color: COLORS.solid_grey,
  },
  walkinCon: {
    backgroundColor: COLORS.white,
    paddingHorizontal: ms(10),
    paddingVertical: ms(5),
    borderRadius: ms(30),
  },
  dataQty: {
    fontFamily: Fonts.Medium,
    fontSize: ms(8),
    color: COLORS.navy_blue,
  },
  dataQtyCon: {
    borderLeftWidth: 1,
    borderRightWidth: 1,
    height: SH(35),
    width: ms(20),
    borderColor: COLORS.light_purple,
    justifyContent: 'center',
    alignItems: 'center',
  },
  discountCon: {
    backgroundColor: COLORS.textInputBackground,
    flexGrow: 1,
    borderRadius: ms(12),
    padding: ms(10),
  },
  imageBackground: {
    flex: 1,
    borderRadius: ms(8),
    justifyContent: 'center',
  },
  imageInnerView: {
    flex: 1,
    borderRadius: ms(8),
    backgroundColor: COLORS.black,
    opacity: 0.7,
    position: 'absolute',
    top: 0,
    bottom: 0,
    right: 0,
    left: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
