export const en = {
  common: {
    connectionError: 'Connection error',
    today: 'Today',
    yesterday: 'Yesterday',
    day: 'day',
    days: 'days',
  },
  phoneNumber: {
    enterPhone: 'Enter your Phone Number',
    sendOtp: 'Please enter your number to phone number',
    numberText: '815-288-0329',
    button: 'Continue',
    verify: 'Verify your',
    phoneNumber: 'phone number',
    enterOtp: 'Enter passcode here',
    verifyButton: 'Verify',
    dontReceive: 'Didn’t receive Code? ',
    resend: 'Resend',
    successfullyVerified: 'Successfully verified',
    loginBack: 'Please login back to your email inbox and set your new password',
  },
  valiadtion: {
    validPhone: 'Please enter valid phone number',
    enterPhone: 'Please enter phone number',
    enterOtp: 'Please enter OTP',
    validOtp: 'Please enter valid OTP',
    enterPassCode: 'Please enter passcode',
    validPasscode: 'Please enter valid passcode',
    error: 'not found',
    phoneNotExist: 'This number does not exist',
    noData: 'No Data',
    noProduct: 'Product not found',
  },
  setPin: {
    title: 'Set up PIN',
    subTitle: 'Cancel',
    enterPin: 'Enter your PIN',
    reenterPin: 'Reenter your PIN',
    done: 'Done!',
    verified: 'You are verified!',
    pinSet: 'Your new pin is set now',
    login: 'Log in',
    setUpPin: 'Set up PIN',
    setNewPin: 'Enter your New PIN',
    reNewPin: 'Reenter your New PIN',
  },
  validation: {
    allowCameraPhoto: `Please allow camera & photo permissions for app from settings`,
    cantAccessImage: `Cannot Access Images`,
    somethingWrong: `Something went wrong.`,
    enterName: `Please enter user name`,
    enterfirstName: `Please enter first name`,
    enterlastName: `Please enter last name`,
    enterEmail: `Please enter email`,
    enterValidEmail: `Please enter valid email`,
    enterValidName: `Please enter valid name`,
    enterValidFirstName: `Please enter valid first name`,
    firstNameRegxValidation: `First name should only contains characters A-Z, a-z, - , .`,
    enterValidLastName: `Please enter valid last name`,
    lastNameRegxValidation: `Last name should only contains characters A-Z, a-z, - , .`,
    nameRegxValidation: 'Name should only contains characters A-Z, a-z, and -',
    enterValidUserName: `Please enter valid username`,
    userNameRegxValidation: 'Username should only contains alphanumeric characters',
    enterValidPhoneNumber: `Please enter valid phone number`,
    enterPassword: `Please enter password`,
    enterDob: `Please enter date of birth`,
    enterPin: `Please enter security pin`,
    enterDob: `Please enter date of birth`,
    entercPin: `Please enter confirm security pin`,
    entervalidpin: `Please confirm security pin must be same as security pin`,
    enterPhone: `Please enter phone number`,
    entercode: `Please enter phone code`,
    acceptConditions: `Please accept Terms & Conditions`,
    enterOtp: `Please enter otp`,
    alert: `Alert`,
    enterCouponCode: `Please enter coupon code`,
    passwordSame: 'New Password can not be same as old password.',
    subject: 'Please select subject',
    enterDescription: 'Please enter description',
    uploadDocuemnt: 'Please upload document',
    samePin: 'Pin does not match',

    alert: 'Alert',

    validPhone: 'Please enter valid phone number',
    phoneLength: 'Phone number must be at least 10 characters long',

    firstName: 'Please enter first name',
    validFirstName: 'Please enter valid first name',

    validlastName: 'Please enter valid last name',
    enterPin: 'Please enter pin',
    enter4digit: 'Please enter 4 digit pin',
    conformPin: 'Please enter confirm pin',
    pinNotMatch: 'Pin and Confirm Pin should be same',
    enterDate: 'Please select date of birth',
    enterSsn: 'Please enter SSN',
    invalidSSN: 'Please enter only digits in SSN field',
    selectGender: 'Please select gender',
    selectType: 'Please select type',
    enterStret: 'Please enter street address',
    enterapartment: 'Please enter apartment',
    selectCity: 'Please enter city',
    selectState: 'Please enter state',
    enterZip: 'Please enter zip code',
    selectIdentity: 'Please select identity type',
    country: 'Please enter country',
    subject: 'Please select subject',
    enterDescription: 'Please enter description',
    uploadDocuemnt: 'Please upload document',
    enterEmail: 'Please enter email',
    profileimage: 'Please select profile image',
    validEmail: 'Please enter valid email',
    enterAmount: 'Please enter amount',
    validAmount: 'Please enter a valid amount',
    emptyCardNumber: 'Please enter card number',
    emptyExpiryDate: 'Please enter expiry date',
    emptyCVV: 'Please enter CVV',
    emptyCardHolderName: 'Please enter card holder name',
    invalidCardHolderName: 'Please enter valid card holder name',
    invalidCvv: 'Please enter valid CVV',
    invalidCardNumber: 'Please enter valid card number',
    invalidDate: 'Please enter valid expiry date',
    invalidOtp: 'Please enter valid OTP',
    emptyEmail: 'Please enter email address',
    invalidEmail: 'Please enter valid email address',
    emptyPersonName: 'Please enter atleast 3 characters',
    emptyRoutingNumber: 'Please enter routing number',
    emptyAccountNumber: 'Please enter account number',
    reenterAccountNumber: 'Please re-enter account number',
    emptyAccountName: 'Please enter account name',
    selectAccount: 'Please select account',
    addBalance: 'Please add balance to your account',
    newPhoneNumber: 'Please enter new phone number',
  },
  validationMessages: {
    emptyPhoneNumber: 'Please enter phone number',
    emptyOtp: 'Please enter OTP code ',
    otpLengthError: 'Please enter valid OTP code',
    emptyPinCode: 'Please enter four digit OTP code',
    pinNotMatch: 'PIN and confirm PIN should be same',
    firstName: 'Please enter first name',
    lastNameerror: 'Please enter last name',
    phoneNotExist: 'This number does not exist',
    enterPin: 'Please enter pin',
    samePin: 'Pin not matched',
  },
  supportTicket: {
    heading: 'Open new ticket',
    subheading:
      'Our gateway is routed directly to Telstra, with Optus and Vodafone networks service.',
    uploadFile: 'Upload your files here',
    button: 'Submit',
    actionTitle: 'Choose an option',
    galleryOption: 'Gallery',
    cameraOption: 'Camera',
    cancelOption: 'Cancel',
  },
  login: {
    enterPasscode: 'Enter Passcode',
    confirmLogin: 'Confirm your log in',
    name: 'Millicent C. Edward',
    id: 'ID:256913',
    date: 'Today Wednesday 11 Aug 2022',
    time: 'Time 3:25 pm',
    logout: 'Log Out',
    noPosUsers: 'No POS users found',
  },
  more: {
    name: 'Karam Manab Attia',
    address: '4554 Adamsville Road, Mission, TX 78572',
    id: 'ID: ',
    logout: 'Logout',
    version: 'V 0000.0001',
    businessProfile: 'Business Profile',
    mySession: 'My Session',
    tagLine: 'Tag line',
    accesConfirmation: 'Access & Confirmation',
    essential: 'Essential',
    app: 'App',
    startTracking: 'Start Tracking Session',
    countCashDrawer: 'Count Cash in Drawer',
    amountCounted: 'Amount Counted',
    note: 'Note',
    startSession: 'Start Session',
  },
  profile: {
    todaySale: 'Today’s Sales',
    cashSale: 'Cash Sales Amount',
    cardSale: 'Card Sales Amount',
    jobrSale: 'JOBR Coin Sales Amount',
    cashDrawer: 'Cash Drawer',
    openingBalance: 'Opening Balance',
    closingBalance: 'Closing Balance',
    loginTime: 'Login Time :',
    session: 'Session :',
    lockScreen: 'Lock screen',
    header: 'Back',
    gallery: 'Gallery',
    camera: 'Camera',
    cancel: 'Cancel',
    title: 'Personal Information',
    nameLabel: 'Name',
    emailAddress: 'email address',
    phone: 'Registered Phone number',
    ssn: 'Social Security Number (SSN)',
    dob: 'Date of Birth',
    address: 'Address',
    emailValue: 'jobr@gmail.com',
    phoneNumber: '+1 612 717 1070',
    dobValue: '01/02/1988',
    ssnNumber: '-------5698',
    addressValue: `3706 Mulberry Lane
    Apt: 4B
    Fort Lauderdale
    Florida- 33301
    United States `,
    scanDes: 'Scan QR Code to pay or send money faster',
    shareCode: 'Share QR code',
    downloadCode: 'Download QR code',
    editName: 'Edit Name',
    Discard: 'Discard',
    save: 'Save Note',
    firstname: 'First name',
    lastname: 'Last name',
    onlySave: 'Save',
  },
  checkout: {
    placeholder: 'Search product here',
    items: 'Items',
    viewAll: 'View all',
    productTitle: 'Jacket-Nord',
    gender: 'Men',
    price: 'Price',
    subCategory: 'Coats & Jacket',
    productDescription: `${'A hoody jacket, also known as a hoodie or a hooded sweatshirt, is a type of casual garment that is designed for comfort and warmth'}`,
    sku: 'SKU',
    discount: 'Discount',
    tax: 'Taxes',
    taxValue: 'Sales (1.5%)',
    applyDiscount: 'Apply Discount',
    otherLocations: 'Other Locations',
    na: 'NA',
    stockOnHand: 'Stock on Hand',
    skuValue: '7044085C',
    stockItems: '12',
    addToCart: 'Add to Cart',
  },
  cart: {
    addToCart: 'Add to Cart',
    title: 'New Product Add to Cart',
    serviceTitle: 'New Service Add to Cart',
    productName: 'Product Name',
    amountValue: '0.00',
    addNotes: 'Add notes',
    clearCart: 'Clear Cart',
    clearCartDescription: 'Are you Sure you want to Clear the Cart?',
    keepIt: 'Keep it',
    clear: 'Clear',
    addNotesHeading: 'Add Notes',
    addDiscount: 'Add Discount',
    amountDiscount: 'Amount Discount',
    percentageDiscount: 'Percentage Discount',
    discountCode: 'Discount Code',
    discountTitle: 'Discount Title',
    availablOffer: 'Available Offer ',
    totalItem: 'Total Items:',
    payNow: 'Pay Now',
    priceChanging: 'Price Changing',
    keepit: 'Keep it',
    noDataFound: 'No Data Found',
    enterField: 'Please enter field',
    upcCode: 'UPC code',
    erecipeSms: 'e-recipe will Send to your phone number ',
    erecipeEmail: 'e-recipe will Send to your email',
    paidAmount: 'Paid  Amount:',
    primark: 'Primark',
    scanToPay: 'Scan to Pay',
    moneyfaster: 'Scan QR Code to pay or send money faster',
    requestYourWallet: 'Send payment request to your wallet',
    sendRequest: 'Send Request',
    validPhone: 'Please enter valid phone number',
  },
  homeTab: {
    placeholder: 'Search by Barcode, SKU, Name',
  },
  successMessages: {
    loginSuccess: 'Login succesfully',
    emptyList: 'No records found',
  },
  transactions: {
    numberOfOrders: 'Number of Orders',
  },

  delivery: {
    todayStatus: 'Today’s Order Status',
    deliveryOrder: 'Delivery Orders',
    orders: 'Orders',
    viewAll: 'View all',
    orderNumber: 'Number of Orders',
    incomingOrders: 'Incoming Orders',
    processingOrders: 'Order Processing',
    readyPickupOrders: 'Ready For Pickup',
    completed: 'Completed',
    ordersToReview: 'Orders to Review',
    noOrders: 'No orders found',
    totalItems: 'Total Items:',
    orderDate: 'Order Date',
    orderid: 'Order ID',
    subTotal: 'Sub Total',
    totalTax: 'Total Taxes',
    discount: 'Discount',
    total: 'Total',
    deliveryCharges: 'Delivery Charges',
    shippingCharges: 'Shipping Charges',
    decline: 'Decline',
    accept: 'Accept',
    express: 'Express delivery',
    oneHour: '1 hour delivery window',
    track: 'Track',
  },
  retail: {
    noProduct: ' No Product found',
    noService: ' No service found',
    detail: 'Details',
    addCart: 'Add to Cart',
    productDetails: 'Product Details',
    materialSupply: 'Materials & Suppliers',
    careGuide: 'Care Guide',
    back: 'Back',
    inStore: 'In store',
    onlineDelivery: 'Online - delivery',
    onlineShipping: 'Online - Shipping',
    availableForSell: 'Available for Selling',
    backToCart: 'Back to Cart',
  },
  orderStatus: {
    reviewOrders: 'Orders to review',
    acceptedOrders: 'Accepted',
    orderPrepare: 'Order Preparing',
    readyToPickup: 'Ready to pickup',
    pickedUp: 'Picked Up',
    delivered: 'Delivered',
    rejected: 'Rejected/Cancelled',
    returned: 'Returned',
    shipOrder: 'Shipped Orders',
    deliveryOrder: 'Delivered Orders',
    cancelledOrder: 'Rejected/ Cancelled Orders',
    returnedOrders: 'Returned Orders',
    orderAccepted: 'Order accepted',
    orderStatus: 'Order status',
    driverAssigned: 'Driver Assigned',
    driverOnTheWay: 'Driver on the way',
    pickup: 'Product Pickup',
    verified: 'Verified',
    ordersToAccepted: 'Orders to Accepted',
    ordersToPrepared: 'Orders to Prepared',
    assignedDriver: 'Assigned Orders to driver',
    ordersPickedUp: 'Orders Picked Up',
    ordersDelivered: 'Orders Delivered',
    ordersRejected: 'Orders Rejected/Cancelled',
    deliveryReturns: 'Delivery Returns',
    printingLabel: 'Printing Label',
    shipped: 'Shipped',
    trackOrders: 'Track Orders',
    cancelled: 'Cancelled',
  },
  buttonStatus: {
    readyForShipment: 'Ready to Ship',
    reviewButton: 'Accept',
    acceptedButton: 'Order Prepared',
    prepareButton: 'Ready to Pickup',
    preparedButton: 'Prepared',
    printlabel: 'Print Label',
    cancelledByuser: 'Cancelled by User',
    cancelledBySeller: 'Cancelled by Seller',
  },

  shipping: {
    todayShippingStatus: 'Today’s Shipping Status',
    shippingOrders: 'Shipping Orders',
    shippedOrders: 'Shipped Orders',
    usps: 'USPS',
    dhl: 'DHL',
    fedex: 'FedEX',
    ups: 'UPS',
    ordersToReview: 'Orders to Review',
  },
  deliveryOrders: {
    search: 'Search',
    orderNumber: 'Number of Orders',
    back: 'Back',
    ready: 'Ready for Pickup',
    subTotal: 'Sub Total',
    subTotalValue: '$4.00',
    discount: 'Discount',
    tax: 'Tax',
    total: 'Total',
    orderStatus: 'Order status',
    delivery: 'Delivery',
    pickup: 'Product Pickup',
    orderAccepted: 'Order accepted',
    readyToPickup: 'Ready to pickup',
    delivered: 'Delivered',
    orderPrepare: 'Order Preparing',
    cancelled: 'Cancelled',
    otherFees: 'Other fees',
    deliveryCharges: 'Delivery Charges',
    shippingCharges: 'Shipping Charges',
    paymentOption: 'Payment Option: ',
    rejected: 'Rejected/Cancelled',
    driverAssigned: 'Driver Assigned',
    tips: 'Tips',
    totalTax: 'Total Taxes',
    totalRefundItems: 'Total Refund Items:',
    returned: 'Returned',
  },
  return: {
    header: 'Return',
    delivery: 'Delivery',
    inStore: 'In-store',
    reservation: 'Reservation',
    shipping: 'Shipping',
    customer: 'Customer:',
    noOrderFound: 'No order found',
    next: 'Next',
  },
  settings: {
    settings: 'Settings',
    locations: 'Locations',
    receipts: 'Receipts',
    taxes: 'Taxes',
    wallet: 'Wallet',
    staffs: 'Staffs',
    language: 'Language',
    legal: 'Legal',
    policies: 'Policies',
    shop: 'Shop',
    deviceDetails: 'Device Details',

    security: 'Security',
    twoStepVerifiCon: '2-step verification',
    softwareUpdate: 'Software updates',
    securitysubhead:
      'An extra layer to boost your team members account security. A verification code will be required in addition to password each time you sign in.',
    memeberEnable: 'Team members must enable their own verification methods.',
    teamMemeber: '2-step verification',
    enableSecurity: 'Enable Two-Steps Security',
    firstDownloader: 'First, download Google Authenticator from the ',
    googleAuth: 'Google authenticator',
    instead:
      'Instead of waiting for text messages, get verification codes from an authenticator app. It works even if your phone is offline.',
    doLater: 'I will do it later',
    next: 'Next',
    qrCode: 'Scan QR Code to active  google authenticator',
    device: 'Devices',
    configure: 'Configure Settings on Your Device',
    manageDevice:
      'All you need to manage Basic Point of Sale is a device nickname and location to allow team members to accept payments.',
    barScan: 'Barcode Scanner ',
    oneBlueTToth: '1 bluetooth device active',
    addNew: 'Add New',
    addStaff: 'Add Staff',
    addbarcode: 'Add Barcode Scanner',
    pluginFirst: '1.  Plugin USB/C Port to  POS Monitor',
    pluginSecond: '2. Scan Barcode Below',
    codeAppear: 'Codes will appear here ',
    done: 'Done',
    addBlueToothHead: 'Add Bluetooth Barcode Scanner',
    searchForDevice: 'Searching for the devices....',
    foundOneDev: 'Found 1 device',
    location: 'Locations',
    businessLocation: 'Business locations',
    lastUpdate: 'Last Update',
    locationsubhead:
      'An extra layer to boost your team members account security. A verification code will be required in addition to password each time you sign in.',
    plans: 'Plans',
    yourPlan: 'Your Plan',
    basic: 'Basic',
    everyThingNeed: 'Everything you need to create a store, ship products, and process payments',
    chnagePlan: 'Change Plan',
    includePlan: 'Your Plan includes app',
    planFeat: 'Plan Features',
    paymentMethod: 'Payment method',
    planFit: 'Plan that fits your scale',
    simpleTra: 'Simple, Transparent pricing that grows with you',
    basicSubHead: 'Everything you need to create a store, ship products, and process payments',
    getStart: 'Get Started',
    invoice: 'Invoices',
    invoiveHeading: 'Invoices',
    // invoiveHeading: 'Taxes and duties',
    invoiveSubHeading:
      'Add a curbside, drive-through, or in-store pickup. Specify your business hours, the pickup location, and add a brief instruction on how the pickup works for customers.',
    smshead: 'Sms to phone number ',
    smsSubHead: 'It may apply charge ',
    printHead: 'Print invoice',
    printSubHead: 'Needs to connect printer for print invoice',
    emailHead: 'Email',
    emailSubHead: 'Email will Send to buyersi email address',
    invoiceTemplate: 'Invoice Template',
    publishDate: 'Publish date:',
    date: 'Sep 27, 2023 10: 00 AM',
    activate: 'Activate:',
    taxHead: 'Taxes and duties',
    taxSubHead:
      'If you haven’t already, create a shipping zone in the region(s) you’re liable in. Then, find the region in this list and select it to manage its tax settings. If you’re unsure about where you’re liable, check with a tax professional.',
    taxes: 'Taxes',
    active: 'Active',
    selectHead: 'Select your Operating Country',
    country: 'Country',
    cancel: 'Cancel',
    next: 'Next',
    selectHeadState: 'Select your Operating States',
    selectState: 'Select States',
    taxPayerHeadl: 'Tax Payer Information',
    name: 'Name',
    ssn: 'SSN or EIN',
    streetAdd: 'Street Address',
    appartement: 'Apartment/Suite',
    SSN: 'SSN',
    verified: 'Verified',
    operatingCountry: 'Operating Country',
    activateStateTax: 'Activate your State Tax',
    financialReport: 'This will show in your financial reports.',
    checkoutMore: 'Checkout for more',
    activateBtn: 'Activate',
    addState: 'Add State',
    craeteTax: 'Create tax',
    details: 'Details',
    taxName: 'Tax name',
    taxRate: 'Tax rate',
    location: 'Location',
    taxCalculation: 'Tax calculation',
    includeTax: 'Include tax in item price',
    includetaxSubhead:
      'If tax is included, the tax will appear in your reports, but your customers will not see the tax on their receipt.',
    notApplied: 'Specify when this tax should not be applied.',
    addRule: 'Add exemption rule',
    save: 'Save',
    taxexmption: 'Tax exemption name',
    exempttax: 'Exempt tax',
    amount: 'Amount',
    introduction: 'Introduction',
    notification: 'Notifications',
    addlanguage: 'Add Language',
    businessName: 'Business Name',
    staff: 'Staff',
    request: 'Request',
  },
  locations: {
    businessLocation: 'Business locations',
    subHeading:
      'All you need to manage Basic Point of Sale is a device nickname and location to allow team members to accept payments.',
  },
  receipts: {
    receipts: 'Receipts',
    invoiceSetting: 'Invoice Setting',
    subTitle: "Active in the markets they've been added to and visible to customers.",
    sms: 'Sms to phone number',
    email: 'Email',
    printInvoice: 'Print invoice',
    applyCharge: 'It may apply charge ',
    emailAdd: 'Email will Send to buyers email address',
    connectprinter: 'Needs to connect printer for print invoice',
  },
  walletSetting: {
    wallet: 'Wallet',
    payJbr: 'Pay by JBR Coin',
    payCash: 'Pay by Cash',
    payCard: 'Pay by Card Contactless',
    subTitle:
      'You need to provide some additional information about your business to start receiving payouts from Shopify Payments.',
    onlineShop: 'System: Online Shop, POS',
    pos: 'POS',
  },
  staffSetting: {
    staffs: 'Staffs',
    staffList: 'Staff List',
    subTitle: "Active in the markets they've been added to and visible to customers.",
    hourRate: 'Hour rate',
    overTime: 'Over time rate',
    paymentCycle: 'Payment Cycle',
    billing: 'Billing',
    currentBilling: 'Current Billing Cycle',
    timeTracked: 'Time Tracked',
    weeklyTrans: 'Weekly Tracking Limit',
    date: 'Date',
    duration: 'Duration',
    joinedDate: 'Joined Date',
    activeSince: 'Active Since',
    employType: 'Employment Type',
    leaveTaken: 'Leave taken',
    amount: 'Amount',
    status: 'Status',
    action: 'Action',
    viewPayment: 'View Payment',
    request: 'Request',
    unPaid: 'Unpaid',
    paid: 'Paid',
  },
  policies: {
    policies: 'Policies',
    publishDate: 'Publish date:',
    lastUpdate: 'Last update date:',
    close: 'Close',
    legal: 'Legal',
    termsConditons: 'Terms & Conditions',
    privacyPolicy: 'Privacy Policy',
  },
  security: {
    security: 'Security',
  },
  notifications: {
    notifications: 'Notifications',
    appNotifications: 'App Notifications',
    newOrder: 'New Order',
    cancelledOrder: 'Cancelled Order',
    shippingNoti: 'Shipping Notifications',
    servicesNoti: 'Services Notifications',
    walletNoti: 'Wallet Notifications',
    accountNoti: 'Account Notifications',
  },
  help: {
    helpCenter: 'Help Center',
    howCan: 'How can we help you',
    mySupportRequest: 'My Support Request',
    support: 'Support',
    mySupport: 'My support',
    subject: 'Subject',
    lastRespond: 'Last Respond',
  },
  plans: {
    plans: 'Plans',
    terms: 'Manage or change your JOBR plan. View our terms of service and privacy policy.',
    yourPlan: 'Your Plan',
    basic: 'Basic',
    standard: 'Standard',
    fitPlan: 'Plan that fits your scale',
    simple: 'Simple, Transparent pricing that grows with you',
    everything: 'Everything you need to create a store, ship products, and process payments',
    planIncludes: 'Your Plan includes app',
    planFeatures: 'Plan Features',
    onlineStore: 'Online store',
    shreable: 'Shareable product pages',
    unlimitedProducts: 'Unlimited products',
    support: '24/7 support',
    abandonedCart: 'Abandoned cart recovery',
    abandonedReport: 'Advanced report builder',
    nextBillingDate: 'Next billing date',
    paymentMethod: 'Payment Method',
    changePlan: 'Change plan',
    appsIncluded: 'Apps included :',
    perMonth: 'Per month',
  },
};
