export const en = {
  common: {
    connectionError: 'Connection error',
    today: 'Today',
    yesterday: 'Yesterday',
    day: 'day',
    days: 'days',
  },
  phoneNumber: {
    enterPhone: 'Enter your Phone Number',
    sendOtp: 'Please enter your number to phone number',
    numberText: '815-288-0329',
    button: 'Continue',
    verify: 'Verify your',
    phoneNumber: 'phone number',
    enterOtp: 'Enter passcode here',
    verifyButton: 'Verify',
    dontReceive: 'Didn’t receive Code? ',
    resend: 'Resend',
    successfullyVerified: 'Successfully verified',
    loginBack: 'Please login back to your email inbox and set your new password',
  },
  setPin: {
    title: 'Set up PIN',
    subTitle: 'Cancel',
    enterPin: 'Enter your PIN',
    reenterPin: 'Reenter your PIN',
    done: 'Done!',
    verified: 'You are verified!',
    pinSet: 'Your new pin is set now',
    login: 'Log in',
  },
  validationMessages: {
    emptyPhoneNumber: 'Please enter phone number',
    emptyOtp: 'Please enter OTP code ',
    otpLengthError: 'Please enter valid OTP code',
    emptyPinCode: 'Please enter four digit OTP code',
    pinNotMatch: 'PIN and confirm PIN should be same',
    firstName: 'Please enter first name',
    lastNameerror: 'Please enter last name',
    phoneNotExist: 'This number does not exist',
  },
  login: {
    enterPasscode: 'Enter Passcode',
    confirmLogin: 'Confirm your log in',
    name: 'Millicent C. Edward',
    id: 'ID:256913',
    date: 'Today Wednesday 11 Aug 2022',
    time: 'Time 3:25 pm',
    logout: 'Log Out',
    noPosUsers: 'No POS users found',
  },
  more: {
    name: 'Karam Manab Attia',
    address: '4554 Adamsville Road, Mission, TX 78572',
    id: 'ID: ',
    logout: 'Logout',
    version: 'V 0000.0001',
    businessProfile: 'Business Profile',
    mySession: 'My Session',
    tagLine: 'Tag line',
    accesConfirmation: 'Access & Confirmation',
    essential: 'Essential',
    app: 'App',
    startTracking: 'Start Tracking Session',
    countCashDrawer: 'Count Cash in Drawer',
    amountCounted: 'Amount Counted',
    note: 'Note',
    startSession: 'Start Session',
  },
  profile: {
    todaySale: 'Today’s Sales',
    cashSale: 'Cash Sales Amount',
    cardSale: 'Card Sales Amount',
    jobrSale: 'JOBR Coin Sales Amount',
    cashDrawer: 'Cash Drawer',
    openingBalance: 'Opening Balance',
    closingBalance: 'Closing Balance',
    loginTime: 'Login Time :',
    session: 'Session :',
    lockScreen: 'Lock screen',
    header: 'Back',
    gallery: 'Gallery',
    camera: 'Camera',
    cancel: 'Cancel',
    title: 'Personal Information',
    nameLabel: 'Name',
    emailAddress: 'email address',
    phone: 'Registered Phone number',
    ssn: 'Social Security Number (SSN)',
    dob: 'Date of Birth',
    address: 'Address',
    emailValue: 'jobr@gmail.com',
    phoneNumber: '+1 612 717 1070',
    dobValue: '01/02/1988',
    ssnNumber: '-------5698',
    addressValue: `3706 Mulberry Lane
    Apt: 4B
    Fort Lauderdale
    Florida- 33301
    United States `,
    scanDes: 'Scan QR Code to pay or send money faster',
    shareCode: 'Share QR code',
    downloadCode: 'Download QR code',
    editName: 'Edit Name',
    Discard: 'Discard',
    save: 'Save Note',
    firstname: 'First name',
    lastname: 'Last name',
    onlySave: 'Save',
  },
  checkout: {
    placeholder: 'Search product here',
    items: 'Items',
    viewAll: 'View all',
    productTitle: 'Jacket-Nord',
    gender: 'Men',
    price: 'Price',
    subCategory: 'Coats & Jacket',
    productDescription: `${'A hoody jacket, also known as a hoodie or a hooded sweatshirt, is a type of casual garment that is designed for comfort and warmth'}`,
    sku: 'SKU',
    discount: 'Discount',
    tax: 'Taxes',
    taxValue: 'Sales (1.5%)',
    applyDiscount: 'Apply Discount',
    otherLocations: 'Other Locations',
    na: 'NA',
    stockOnHand: 'Stock on Hand',
    skuValue: '7044085C',
    stockItems: '12',
    addToCart: 'Add to Cart',
  },
  cart: {
    addToCart: 'Add to Cart',
    title: 'New Product Add to Cart',
    productName: 'Product Name',
    amountValue: '0.00',
    addNotes: 'Add notes',
    clearCart: 'Clear Cart',
    clearCartDescription: 'Are you Sure you want to Clear the Cart?',
    keepIt: 'Keep it',
    clear: 'Clear',
    addNotesHeading: 'Add Notes',
    addDiscount: 'Add Discount',
    amountDiscount: 'Amount Discount',
    percentageDiscount: 'Percentage Discount',
    discountCode: 'Discount Code',
    discountTitle: 'Discount Title',
    availablOffer: 'Available Offer ',
    totalItem: 'Total Items:',
    payNow: 'Pay Now',
    priceChanging: 'Price Changing',
    keepit: 'Keep it',
    noDataFound: 'No Data Found',
    enterField: 'Please enter field',
    upcCode: 'UPC code',
    erecipeSms: 'e-recipe will Send to your phone number ',
    erecipeEmail: 'e-recipe will Send to your email',
    paidAmount: 'Paid  Amount:',
    primark: 'Primark',
    scanToPay: 'Scan to Pay',
    moneyfaster: 'Scan QR Code to pay or send money faster',
    requestYourWallet: 'Send payment request to your wallet',
    sendRequest: 'Send Request',
    validPhone: 'Please enter valid phone number',
  },
  homeTab: {
    placeholder: 'Search by Barcode, SKU, Name',
  },
  successMessages: {
    loginSuccess: 'Login succesfully',
  },
  transactions: {
    numberOfOrders: 'Number of Orders',
  },

  delivery: {
    todayStatus: 'Today’s Order Status',
    deliveryOrder: 'Delivery Orders',
    orders: 'Orders',
    viewAll: 'View all',
    orderNumber: 'Number of Orders',
    incomingOrders: 'Incoming Orders',
    processingOrders: 'Order Processing',
    readyPickupOrders: 'Ready For Pickup',
    completed: 'Completed',
    ordersToReview: 'Orders to Review',
    noOrders: 'No orders found',
    totalItems: 'Total Items:',
    orderDate: 'Order Date',
    orderid: 'Order ID',
    subTotal: 'Sub Total',
    totalTax: 'Total Taxes',
    discount: 'Discount',
    total: 'Total',
    deliveryCharges: 'Delivery Charges',
    shippingCharges: 'Shipping Charges',
    decline: 'Decline',
    accept: 'Accept',
    express: 'Express delivery',
    oneHour: '1 hour delivery window',
    track: 'Track',
  },
  retail: {
    noProduct: ' No Product found',
    noService: ' No service found',
    detail: 'Details',
    addCart: 'Add to Cart',
    productDetails: 'Product Details',
    materialSupply: 'Materials & Suppliers',
    careGuide: 'Care Guide',
    back: 'Back',
    inStore: 'In store',
    onlineDelivery: 'Online - delivery',
    onlineShipping: 'Online - Shipping',
    availableForSell: 'Available for Selling',
    backToCart: 'Back to Cart',
  },
  orderStatus: {
    reviewOrders: 'Orders to review',
    acceptedOrders: 'Accepted',
    orderPrepare: 'Order Preparing',
    readyToPickup: 'Ready to pickup',
    pickedUp: 'Picked Up',
    delivered: 'Delivered',
    rejected: 'Rejected/Cancelled',
    returned: 'Returned',
    shipOrder: 'Shipped Orders',
    deliveryOrder: 'Delivered Orders',
    cancelledOrder: 'Rejected/ Cancelled Orders',
    returnedOrders: 'Returned Orders',
    orderAccepted: 'Order accepted',
    orderStatus: 'Order status',
    driverAssigned: 'Driver Assigned',
    driverOnTheWay: 'Driver on the way',
    pickup: 'Product Pickup',
    verified: 'Verified',
    ordersToAccepted: 'Orders to Accepted',
    ordersToPrepared: 'Orders to Prepared',
    assignedDriver: 'Assigned Orders to driver',
    ordersPickedUp: 'Orders Picked Up',
    ordersDelivered: 'Orders Delivered',
    ordersRejected: 'Orders Rejected/Cancelled',
    deliveryReturns: 'Delivery Returns',
    printingLabel: 'Printing Label',
    shipped: 'Shipped',
    trackOrders: 'Track Orders',
    cancelled: 'Cancelled',
  },
  buttonStatus: {
    readyForShipment: 'Ready to Ship',
    reviewButton: 'Accept',
    acceptedButton: 'Order Prepared',
    prepareButton: 'Ready to Pickup',
    preparedButton: 'Prepared',
    printlabel: 'Print Label',
    cancelledByuser: 'Cancelled by User',
    cancelledBySeller: 'Cancelled by Seller',
  },

  shipping: {
    todayShippingStatus: 'Today’s Shipping Status',
    shippingOrders: 'Shipping Orders',
    shippedOrders: 'Shipped Orders',
    usps: 'USPS',
    dhl: 'DHL',
    fedex: 'FedEX',
    ups: 'UPS',
    ordersToReview: 'Orders to Review',
  },
  deliveryOrders: {
    search: 'Search',
    orderNumber: 'Number of Orders',
    back: 'Back',
    ready: 'Ready for Pickup',
    subTotal: 'Sub Total',
    subTotalValue: '$4.00',
    discount: 'Discount',
    tax: 'Tax',
    total: 'Total',
    orderStatus: 'Order status',
    delivery: 'Delivery',
    pickup: 'Product Pickup',
    orderAccepted: 'Order accepted',
    readyToPickup: 'Ready to pickup',
    delivered: 'Delivered',
    orderPrepare: 'Order Preparing',
    cancelled: 'Cancelled',
    otherFees: 'Other fees',
    deliveryCharges: 'Delivery Charges',
    shippingCharges: 'Shipping Charges',
    paymentOption: 'Payment Option: ',
    rejected: 'Rejected/Cancelled',
    driverAssigned: 'Driver Assigned',
    tips: 'Tips',
    totalTax: 'Total Taxes',
    totalRefundItems: 'Total Refund Items:',
    returned: 'Returned',
  },
  return: {
    header: 'Return',
    delivery: 'Delivery',
    inStore: 'In-store',
    reservation: 'Reservation',
    shipping: 'Shipping',
    customer: 'Customer:',
    noOrderFound: 'No order found',
    next: 'Next',
  },
  settings: {
    settings: 'Settings',
    locations: 'Locations',
    receipts: 'Receipts',
    taxes: 'Taxes',
    wallet: 'Wallet',
    staffs: 'Staffs',
    language: 'Language',
    legal: 'Legal',
    policies: 'Policies',
    shop: 'Shop',
    deviceDetails: 'Device Details',
  },
  locations: {
    businessLocation: 'Business locations',
    subHeading:
      'All you need to manage Basic Point of Sale is a device nickname and location to allow team members to accept payments.',
  },
  receipts: {
    receipts: 'Receipts',
    invoiceSetting: 'Invoice Setting',
    subTitle: "Active in the markets they've been added to and visible to customers.",
    sms: 'Sms to phone number',
    email: 'Email',
    printInvoice: 'Print invoice',
    applyCharge: 'It may apply charge ',
    emailAdd: 'Email will Send to buyers email address',
    connectprinter: 'Needs to connect printer for print invoice',
  },
  walletSetting: {
    wallet: 'Wallet',
    payJbr: 'Pay by JBR Coin',
    payCash: 'Pay by Cash',
    payCard: 'Pay by Card Contactless',
    subTitle:
      'You need to provide some additional information about your business to start receiving payouts from Shopify Payments.',
    onlineShop: 'System: Online Shop, POS',
    pos: 'POS',
  },
  staffSetting: {
    staffs: 'Staffs',
    staffList: 'Staff List',
    subTitle: "Active in the markets they've been added to and visible to customers.",
    hourRate: 'Hour rate',
    overTime: 'Over time rate',
    paymentCycle: 'Payment Cycle',
    billing: 'Billing',
    currentBilling: 'Current Billing Cycle',
    timeTracked: 'Time Tracked',
    weeklyTrans: 'Weekly Tracking Limit',
    date: 'Date',
    duration: 'Duration',
    joinedDate: 'Joined Date',
    activeSince: 'Active Since',
    employType: 'Employment Type',
    leaveTaken: 'Leave taken',
    amount: 'Amount',
    status: 'Status',
    action: 'Action',
    viewPayment: 'View Payment',
    request: 'Request',
    unPaid: 'Unpaid',
    paid: 'Paid',
  },
  policies: {
    policies: 'Policies',
    publishDate: 'Publish date:',
    lastUpdate: 'Last update date:',
    close: 'Close',
    legal: 'Legal',
  },
  notifications: {
    notifications: 'Notifications',
  },
};
