export const TYPES = {
    GET_TOTAL_GRAPH_REQUEST :'GET_TOTAL_GRAPH_REQUEST',
    GET_TOTAL_GRAPH_SUCCESS:'GET_TOTAL_GRAPH_SUCCESS',
    GET_TOTAL_GRAPH_ERROR:'GET_TOTAL_GRAPH_ERROR',
    GET_TOTAL_GRAPH :'GET_TOTAL_GRAPH',
    GET_ORDER_GRAPH_REQUEST:'GET_ORDER_GRAPH_REQUEST',
    GET_ORDER_GRAPH_SUCCESS:'GET_ORDER_GRAPH_SUCCESS',
    GET_ORDER_GRAPH_ERROR:'GET_ORDER_GRAPH_ERROR',
    GET_ORDER_GRAPH:'GET_ORDER_GRAPH',
    GET_INVENTERY_GRAPH_REQUEST:'GET_INVENTERY_GRAPH_REQUEST',
    GET_INVENTERY_GRAPH_SUCCESS:'GET_INVENTERY_GRAPH_SUCCESS',
    GET_INVENTERY_GRAPH_ERROR:'GET_INVENTERY_GRAPH_ERROR',
    GET_INVENTERY_GRAPH:'GET_INVENTERY_GRAPH',
    GET_REVENUE_GRAPH_REQUEST:'GET_REVENUE_GRAPH_REQUEST',
    GET_REVENUE_GRAPH_SUCCESS:'GET_REVENUE_GRAPH_SUCCESS',
    GET_REVENUE_GRAPH_ERROR:'GET_REVENUE_GRAPH_ERROR',
    GET_REVENUE_GRAPH:'GET_REVENUE_GRAPH',
    GET_TOTALPRO_DETAIL_REQUEST:'GET_TOTALPRO_DETAIL_REQUEST',
    GET_TOTALPRO_DETAIL_SUCCESS:'GET_TOTALPRO_DETAIL_SUCCESS',
    GET_TOTALPRO_DETAIL_ERROR:'GET_TOTALPRO_DETAIL_ERROR',
    GET_TOTALPRO_DETAIL:'GET_TOTALPRO_DETAIL'

  
    


};