export const TYPES = {
  // Get All Appointments
  GET_APPOINTMENTS_REQUEST: 'GET_APPOINTMENTS_REQUEST',
  GET_APPOINTMENTS_SUCCESS: 'GET_APPOINTMENTS_SUCCESS',
  GET_APPOINTMENTS_ERROR: 'GET_APPOINTMENTS_ERROR',
  GET_APPOINTMENTS_RESET: 'GET_APPOINTMENTS_RESET',
  GET_APPOINTMENTS: 'GET_APPOINTMENTS',

  // Get Staff users
  GET_STAFF_USERS_REQUEST: 'GET_STAFF_USERS_REQUEST',
  GET_STAFF_USERS_SUCCESS: 'GET_STAFF_USERS_SUCCESS',
  GET_STAFF_USERS_ERROR: 'GET_STAFF_USERS_ERROR',
  GET_STAFF_USERS_RESET: 'GET_STAFF_USERS_RESET',
  GET_STAFF_USERS: 'GET_STAFF_USERS',

  //Change Appointment Status
  CHANGE_APPOINTMENT_STATUS_REQUEST: 'CHANGE_APPOINTMENT_STATUS_REQUEST',
  CHANGE_APPOINTMENT_STATUS_SUCCESS: 'CHANGE_APPOINTMENT_STATUS_SUCCESS',
  CHANGE_APPOINTMENT_STATUS_ERROR: 'CHANGE_APPOINTMENT_STATUS_ERROR',
  CHANGE_APPOINTMENT_STATUS_RESET: 'CHANGE_APPOINTMENT_STATUS_RESET',
  CHANGE_APPOINTMENT_STATUS: 'CHANGE_APPOINTMENT_STATUS_RESET',
};
