export const TYPES = {
  // Get All Appointments
  GET_APPOINTMENTS_REQUEST: 'GET_APPOINTMENTS_REQUEST',
  GET_APPOINTMENTS_SUCCESS: 'GET_APPOINTMENTS_SUCCESS',
  GET_APPOINTMENTS_ERROR: 'GET_APPOINTMENTS_ERROR',
  GET_APPOINTMENTS_RESET: 'GET_APPOINTMENTS_RESET',
  GET_APPOINTMENTS: 'GET_APPOINTMENTS_RESET',

  CREATE_ORDER_REQUEST: 'CREATE_ORDER_REQUEST',
  CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
  CREATE_ORDER_ERROR: 'CREATE_ORDER_ERROR',
  CREATE_ORDER_RESET: 'CREATE_ORDER_RESET',
  CREATE_ORDER: 'CREATE_ORDER',
};
