export const TYPES = {
    GET_DRAWER_SESSION_REQUEST:'GET_DRAWER_SESSION_REQUEST',
    GET_DRAWER_SESSION_SUCCESS:'GET_DRAWER_SESSION_SUCCESS',
    GET_DRAWER_SESSION_ERROR:'GET_DRAWER_SESSION_ERROR',
    GET_DRAWER_SESSION:'GET_DRAWER_SESSION',
    TRACK_SESSION_SAVE_REQUEST:'TRACK_SESSION_SAVE_REQUEST',
    TRACK_SESSION_SAVE_SUCCESS:'TRACK_SESSION_SAVE_SUCCESS',
    TRACK_SESSION_SAVE_ERROR:'TRACK_SESSION_SAVE_ERROR',
    TRACK_SESSION_SAVE:'TRACK_SESSION_SAVE'

  
    


};