export const TYPES = {
  GET_ORDER_DELIVERIES_REQUEST: 'GET_ORDER_DELIVERIES_REQUEST',
  GET_ORDER_DELIVERIES_SUCCESS: 'GET_ORDER_DELIVERIES_SUCCESS',
  GET_ORDER_DELIVERIES_ERROR: 'GET_ORDER_DELIVERIES_ERROR',
  GET_ORDER_DELIVERIES_RESET: 'GET_ORDER_DELIVERIES_RESET',
  GET_ORDER_DELIVERIES: 'GET_ORDER_DELIVERIES',
};
