export const TYPES = {
  GET_SETTING_REQUEST: 'GET_SETTING_REQUEST',
  GET_SETTING_SUCCESS: 'GET_SETTING_SUCCESS',
  GET_SETTING_ERROR: 'GET_SETTING_ERROR',
  GET_SETTING: 'GET_SETTING',

  UPDATE_API_REQUEST: 'UPDATE_API_REQUEST',
  UPDATE_API_SUCCESS: 'UPDATE_API_SUCCESS',
  UPDATE_API_ERROR: 'UPDATE_API_ERROR',
  UPDATE_API: 'UPDATE_API',

  GET_SHIPPICK_REQUEST: 'GET_SHIPPICK_REQUEST',
  GET_SHIPPICK_SUCCESS: 'GET_SHIPPICK_SUCCESS',
  GET_SHIPPICK_ERROR: 'GET_SHIPPICK_ERROR',
  GET_SHIPPICK: 'GET_SHIPPICK',

  ADDRESS_UPDATE_REQUEST: 'ADDRESS_UPDATE_REQUEST',
  ADDRESS_UPDATE_SUCCESS: 'ADDRESS_UPDATE_SUCCESS',
  ADDRESS_UPDATE_ERROR: 'ADDRESS_UPDATE_ERROR',
  ADDRESS_UPDATE: 'ADDRESS_UPDATE',

  GET_USER_ADD_REQUEST: 'GET_USER_ADD_REQUEST',
  GET_USER_ADD_SUCCESS: 'GET_USER_ADD_SUCCESS',
  GET_USER_ADD_ERROR: 'GET_USER_ADD_ERROR',
  GET_USER_ADD_RESET: 'GET_USER_ADD_RESET',
  GET_USER_ADD: 'GET_USER_ADD',

  GET_COUNTRIES_REQUEST: 'GET_COUNTRIES_REQUEST',
  GET_COUNTRIES_SUCCESS: 'GET_COUNTRIES_SUCCESS',
  GET_COUNTRIES_ERROR: 'GET_COUNTRIES_ERROR',
  GET_COUNTRIES_RESET: 'GET_COUNTRIES_RESET',
  GET_COUNTRIES: 'GET_COUNTRIES',

  GET_STATE_REQUEST: 'GET_STATE_REQUEST',
  GET_STATE_SUCCESS: 'GET_STATE_SUCCESS',
  GET_STATE_ERROR: 'GET_STATE_ERROR',
  GET_STATE_RESET: 'GET_STATE_RESET',
  GET_STATE: 'GET_STATE',

  STAFF_DETAIL_REQUEST: 'STAFF_DETAIL_REQUEST',
  STAFF_DETAIL_SUCCESS: 'STAFF_DETAIL_SUCCESS',
  STAFF_DETAIL_ERROR: 'STAFF_DETAIL_ERROR',
  STAFF_DETAIL_RESET: 'STAFF_DETAIL_RESET',
  STAFF_DETAIL: 'STAFF_DETAIL',

  GET_TAX_REQUEST: 'GET_TAX_REQUEST',
  GET_TAX_SUCCESS: 'GET_TAX_SUCCESS',
  GET_TAX_ERROR: 'GET_TAX_ERROR',
  GET_TAX_RESET: 'GET_TAX_RESET',
  GET_TAX: 'GET_TAX',

  GET_TAX_TRUE_REQUEST: 'GET_TAX_TRUE_REQUEST',
  GET_TAX_TRUE_SUCCESS: 'GET_TAX_TRUE_SUCCESS',
  GET_TAX_TRUE_ERROR: 'GET_TAX_TRUE_ERROR',
  GET_TAX_TRUE_RESET: 'GET_TAX_TRUE_RESET',
  GET_TAX_TRUE: 'GET_TAX_TRUE',
};
