export const TYPES = {
  GET_SETTING_REQUEST: 'GET_SETTING_REQUEST',
  GET_SETTING_SUCCESS: 'GET_SETTING_SUCCESS',
  GET_SETTING_ERROR: 'GET_SETTING_ERROR',
  GET_SETTING: 'GET_SETTING',

  UPDATE_API_REQUEST: 'UPDATE_API_REQUEST',
  UPDATE_API_SUCCESS: 'UPDATE_API_SUCCESS',
  UPDATE_API_ERROR: 'UPDATE_API_ERROR',
  UPDATE_API: 'UPDATE_API',

  GET_SHIPPICK_REQUEST: 'GET_SHIPPICK_REQUEST',
  GET_SHIPPICK_SUCCESS: 'GET_SHIPPICK_SUCCESS',
  GET_SHIPPICK_ERROR: 'GET_SHIPPICK_ERROR',
  GET_SHIPPICK: 'GET_SHIPPICK',
};
