export const TYPES = {
  CLEAR_STORE: 'CLEAR_STORE',

  BUY_SUBSCRIPTION: 'BUY_SUBSCRIPTION',
  BUY_SUBSCRIPTION_REQUEST: 'BUY_SUBSCRIPTION_REQUEST',
  BUY_SUBSCRIPTION_ERROR: 'BUY_SUBSCRIPTION_ERROR',
  BUY_SUBSCRIPTION_SUCCESS: 'BUY_SUBSCRIPTION_SUCCESS',

  GET_ACTIVE_SUBSCRIPTION: 'GET_ACTIVE_SUBSCRIPTION',
  GET_ACTIVE_SUBSCRIPTION_REQUEST: 'GET_ACTIVE_SUBSCRIPTION_REQUEST',
  GET_ACTIVE_SUBSCRIPTION_ERROR: 'GET_ACTIVE_SUBSCRIPTION_ERROR',
  GET_ACTIVE_SUBSCRIPTION_SUCCESS: 'GET_ACTIVE_SUBSCRIPTION_SUCCESS',

  GET_ALL_PLANS: 'GET_ALL_PLANS',
  GET_ALL_PLANS_REQUEST: 'GET_ALL_PLANS_REQUEST',
  GET_ALL_PLANS_ERROR: 'GET_ALL_PLANS_ERROR',
  GET_ALL_PLANS_SUCCESS: 'GET_ALL_PLANS_SUCCESS',

  GET_PLAN_BY_ID: 'GET_PLAN_BY_ID',
  GET_PLAN_BY_ID_REQUEST: 'GET_PLAN_BY_ID_REQUEST',
  GET_PLAN_BY_ID_ERROR: 'GET_PLAN_BY_ID_ERROR',
  GET_PLAN_BY_ID_SUCCESS: 'GET_PLAN_BY_ID_SUCCESS',

  CREATE_PLAN: 'CREATE_PLAN',
  CREATE_PLAN_REQUEST: 'CREATE_PLAN_REQUEST',
  CREATE_PLAN_ERROR: 'CREATE_PLAN_ERROR',
  CREATE_PLAN_SUCCESS: 'CREATE_PLAN_SUCCESS',

  UPDATE_PLAN: 'UPDATE_PLAN',
  UPDATE_PLAN_REQUEST: 'UPDATE_PLAN_REQUEST',
  UPDATE_PLAN_ERROR: 'UPDATE_PLAN_ERROR',
  UPDATE_PLAN_SUCCESS: 'UPDATE_PLAN_SUCCESS',

  DELETE_PLAN: 'DELETE_PLAN',
  DELETE_PLAN_REQUEST: 'DELETE_PLAN_REQUEST',
  DELETE_PLAN_ERROR: 'DELETE_PLAN_ERROR',
  DELETE_PLAN_SUCCESS: 'DELETE_PLAN_SUCCESS',
};
