export const TYPES = {
  GET_SUPPORTLIST: 'GET_SUPPORTLIST',
  GET_SUPPORTLIST_REQUEST: 'GET_SUPPORTLIST_REQUEST',
  GET_SUPPORTLIST_SUCCESS: 'GET_SUPPORTLIST_SUCCESS',
  GET_SUPPORTLIST_ERROR: 'GET_SUPPORTLIST_ERROR',

  GET_FAQlIST: 'GET_FAQlIST',
  GET_FAQlIST_REQUEST: 'GET_FAQlIST_REQUEST',
  GET_FAQlIST_SUCCESS: 'GET_FAQlIST_SUCCESS',
  GET_FAQlIST_ERROR: 'GET_FAQlIST_ERROR',

  ADD_NEW_TICKET: 'ADD_NEW_TICKET',
  ADD_NEW_TICKET_REQUEST: 'ADD_NEW_TICKET_REQUEST',
  ADD_NEW_TICKET_SUCCESS: 'ADD_NEW_TICKET_SUCCESS',
  ADD_NEW_TICKET_ERROR: 'ADD_NEW_TICKET_ERROR',

  GET_SUBJECT: 'GET_SUBJECT',
  GET_SUBJECT_REQUEST: 'GET_SUBJECT_REQUEST',
  GET_SUBJECT_SUCCESS: 'GET_SUBJECT_SUCCESS',
  GET_SUBJECT_ERROR: 'GET_SUBJECT_ERROR',

  GET_DEPARTMENTS: 'GET_DEPARTMENTS',
  GET_DEPARTMENTS_REQUEST: 'GET_DEPARTMENTS_REQUEST',
  GET_DEPARTMENTS_SUCCESS: 'GET_DEPARTMENTS_SUCCESS',
  GET_DEPARTMENTS_ERROR: 'GET_DEPARTMENTS_ERROR',
};
