export const TYPES = {
    CLEAR_STORE:'CLEAR_STORE',
    GET_CATEGORY_SUCCESS :'GET_CATEGORY_SUCCESS',
    GET_CATEGORY_REQUEST:'GET_CATEGORY_REQUEST',
    GET_CATEGORY_ERROR:'GET_CATEGORY_ERROR',
    GET_CATEGORY :'GET_CATEGORY',
    GET_SUB_CATEGORY_REQUEST:'GET_SUB_CATEGORY_REQUEST',
    GET_SUB_CATEGORY_SUCCESS:'GET_SUB_CATEGORY_SUCCESS',
    GET_SUB_CATEGORY_ERROR:'GET_SUB_CATEGORY_ERROR',
    GET_SUB_CATEGORY:'GET_SUB_CATEGORY',
    GET_BRAND_REQUEST:'GET_BRAND_REQUEST',
    GET_BRAND_SUCCESS:'GET_BRAND_SUCCESS',
    GET_BRAND_ERROR:'GET_BRAND_ERROR',
    GET_BRAND:'GET_BRAND',
    SAVE_PHONE:'SAVE_PHONE',
    VERIFY_PHONE:'VERIFY_PHONE',
    VERIFY_PHONE_REQUEST:'VERIFY_PHONE_REQUEST',
    VERIFY_PHONE_ERROR:'VERIFY_PHONE_ERROR',
    VERIFY_PHONE_SUCCESS:'VERIFY_PHONE_SUCCESS',
    LOGIN:'LOGIN',
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_ERROR:'LOGIN_ERROR',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    GET_PROFILE:'GET_PROFILE',
    GET_PROFILE_REQUEST:'GET_PROFILE_REQUEST',
    GET_PROFILE_ERROR:'GET_PROFILE_ERROR',
    GET_PROFILE_SUCCESS:'GET_PROFILE_SUCCESS'

    


};