export const TYPES = {
    GET_CATEGORY_SUCCESS :'GET_CATEGORY_SUCCESS',
    GET_CATEGORY_REQUEST:'GET_CATEGORY_REQUEST',
    GET_CATEGORY_ERROR:'GET_CATEGORY_ERROR',
    GET_CATEGORY :'GET_CATEGORY',
    GET_BRAND_REQUEST:'GET_BRAND_REQUEST',
    GET_BRAND_SUCCESS:'GET_BRAND_SUCCESS',
    GET_BRAND_ERROR:'GET_BRAND_ERROR',
    GET_BRAND:'GET_BRAND'

    


};