export const TYPES = {
  GET_TOTAL_TRA_REQUEST:'GET_TOTAL_TRA_REQUEST',
  GET_TOTAL_TRA_SUCCESS:'GET_TOTAL_TRA_SUCCESS',
  GET_TOTAL_TRA_ERROR:'GET_TOTAL_TRA_ERROR',
  GET_TOTAL_TRA_RESET:'GET_TOTAL_TRA_RESET',
  GET_TOTAL_TRA:'GET_TOTAL_TRA'
  };