export const en = {
  common: {
    loading: 'Loading',
    connectionError: 'Connection error',
  },
  home: {
    header: 'Home',
    message: 'Welcome',
    variant: 'App variant: ',
  },
  login: {
    username: 'Username',
    usernameHint: 'Enter your username',
    button: 'Login',
    password: 'Password',
    passwordHint: 'Enter your password',
    invalidCredentials: 'Invalid Username/Password',
  },
  profile: {
    header: 'Profile',
    logout: 'Logout',
    message: 'This screen has the iOS native large header.',
  },
  verifyPhone: {
    heading: 'Verify your phone number',
    subHeading: 'Please enter your number to phone number',
    placeHolderText: '815-288-0329',
    button: 'Continue',
  },
  verifyOtp: {
    heading: 'Verify your phone number',
    subHeading: 'Enter OTP code here',
    placeHolderText: '815-288-0329',
    button: 'Continue',
  },
  passcode: {
    heading: 'Enter Passcode',
    success: 'Successfully verified',
    loginBack:
      'Please login back to your email inbox and set your new password',
  },
  loginIntial: {
    heading: 'CONFIRM YOUR LOG IN',
    name: 'Millicent C. Edward',
    id: 'ID:256913',
    date: 'Today Wednesday 11 Aug 2022',
    time: 'Time 3:25 pm',
  },
  deliveryOrders: {
    heading: 'Delivery orders',
    search: 'Search',
    orderNumber: 'Number of Orders',
    orderReview: 'Orders to review',
    viewAll: 'View all',
    orderConversion: 'Order conversion',
    deliveryOrders: 'Delivering Orders',
    back: 'Back',
    orderId: 'Order#WXCOO1256',
    orderDate: 'August 30, 2022',
    name: 'Rebecca R. Russell',
    address: '1480 Bassel Street, New Orleans, LA 70113',
    deliveryType: 'Express Delivery',
    time: 'Immediately',
    ordersPreparing:'Orders Preparing',
    ready:'Ready for Pickup'
  },
  verifyPhone: {
    heading: 'Verify your phone number',
    subHeading: 'Please enter your number to phone number',
    placeHolderText: '815-288-0329',
    button: 'Continue',
  },
  verifyOtp: {
    heading: 'Verify your phone number',
    subHeading: 'Enter OTP code here',
    placeHolderText: '815-288-0329',
    button: 'Continue',
  },
  passcode: {
    heading: 'Enter Passcode',
    success: 'Successfully verified',
    loginBack:
      'Please login back to your email inbox and set your new password',
  },
  loginIntial: {
    heading: 'CONFIRM YOUR LOG IN',
    name: 'Millicent C. Edward',
    id: 'ID:256913',
    date: 'Today Wednesday 11 Aug 2022',
    time: 'Time 3:25 pm',
  },
  posSale: {
    paymentHeader: 'Customer & Payment',
    walletId: 'Wallet Id',
    scanText: 'or Scan',
    rederecting: 'Redirecting',
    listOfItem: 'List of items',
    rewardpoint: 'Reward Points : 500',
    onex: '1',
    price: '$382.75',
    onlyx: 'x',
    notes: 'Notes:',
    itMynday: 'Its for my birthday!',
    paymentdetail: 'Payment Details',
    paymenttdone: 'Payment Done!',
    Customer: 'Customer',
    customerNo: 'Customer phone number',
    customerName: 'Terry Moore',
    customerMobileNo: '803-238-2630',
    customerEmail: 'harryrady@jourrapide.com',
    customerAddr: '4849 Owagner Lane',
    customerAddr2: 'Seattle, WA 98101',
    customerTotalAmountHeader: 'Total amount: $254.60',
    tips: 'Tips',
    noTips: 'No Tips',
    cashRecive: 'Cash amount received',
    otherAmount: 'Other amount',
    changeDue: 'Change Due: $3.40',
    firstName: 'First name',
  },
};
