export const en = {
  common: {
    connectionError: 'Connection error',
    today: 'Today',
    yesterday: 'Yesterday',
    day: 'day',
    days: 'days',
  },
  home: {
    message: 'Welcome',
    variant: 'App variant: ',
  },
  login: {
    username: 'Username',
    usernameHint: 'Enter your username',
    button: 'Login',
    password: 'Password',
    passwordHint: 'Enter your password',
  },
  verifyOtp: {
    heading: 'Verify your phone number',
    subHeading: 'Enter OTP code here',
    button: 'Continue',
  },
  passcode: {
    heading: 'Enter Passcode',
    success: 'Successfully verified',
    loginBack: 'Please login back to your email inbox and set your new password',
  },
  loginIntial: {
    heading: 'CONFIRM YOUR LOG IN',
  },
  notifications: {
    header: 'Notifications',
    noData: 'No notifications yet',
  },
  deliveryOrders: {
    search: 'Search',
    orderNumber: 'Number of Orders',
    back: 'Back',
    ready: 'Ready for Pickup',
    subTotal: 'Sub Total',
    subTotalValue: '$4.00',
    discount: 'Discount',
    tax: 'Tax',
    total: 'Total',
    orderStatus: 'Order status',
    delivery: 'Delivery',
    pickup: 'Product Pickup',
    orderAccepted: 'Order accepted',
    readyToPickup: 'Ready to pickup',
    delivered: 'Delivered',
    orderPrepare: 'Order Preparing',
    cancelled: 'Cancelled',
    otherFees: 'Other fees',
    deliveryCharges: 'Delivery Charges',
    paymentOption: 'Payment Option: ',
    rejected: 'Rejected/Cancelled',
    driverAssigned: 'Driver Assigned',
  },
  verifyPhone: {
    heading: 'Verify your phone number',
    subHeading: 'Please enter your number to phone number',
    placeHolderText: '815-288-0329',
    button: 'Continue',
  },
  posUsersList: {
    heading: 'To use the POS Login',
    logOut: 'Log Out',
  },
  retail: {
    price: 'Price',
    bundleOffer: 'Bundle offer',
    addNotes: 'Add Notes',
    addTocart: 'Add to cart',
    amountDis: 'Amount',
    perDis: 'Percent',
    DisCode: 'Discount Code',
    DisTitle: 'Discount Title',
    eRecipeEmail: `e-recipe will Send\nto your email`,
  },
  posSale: {
    onlyx: 'x',
    paymenttdone: 'Payment Done!',
    category: 'Category',
    discount: 'Discount',
    updateprice: 'Update price',
    addNewProduct: 'Add new product',
    barcode: 'Barcode',
    scanBarcode: 'Scanned Barcode',
    productName: 'Product Name',
    selectCat: 'Select Category',
    selectSubCat: 'Select Sub-category',
    selectBrand: 'Select Brand',
    removeCart: 'Remove from cart',
    updateCart: 'Update to cart',
    sellingPrice: 'Selling Price',
    inventryItem: 'Track Inventory for this item',
    inventryOpen: 'Inventory-Opening',
    inventryRenderPoint: 'Inventory-Reorder Point',
    pack: 'Pack',
    stock: ' in stock',
    location: 'Available in another location',
    addToCart: 'Add to cart',
    back: 'Back',
    details: 'Details',
    saveDiscount: 'Save Discount',
    pleaseAddNotes: 'Please add notes',
    discountType: 'Please select discount type',
    enterfield: 'Please enter field',
    addItemCart: 'Please item add in the cart',
    selectDisTitle: 'Please select discount title',
    availableStock: 'Available in stock: ',
    viewDetail: 'View details',
  },
  management: {
    cashTracking: 'Cash Tracking',
    cashDrawer: 'Cash Drawer',
    drawerID: 'Drawer ID:',
    drawerID2: 'Drawer ID: 2',
    session: 'Start tracking session',
    sessionHistory: 'Session history',
    countCash: 'Count cash in drawer',
    amountCounted: 'Amount counted (USD)',
    amount: '$ 0.00',
    note: 'Note',
    save: 'Save',
    viewSession: 'View session',
    date: 'Today Friday Auguest 26, 2022   | 11.04 AM',
    usd: 'USD $',
    expected: 'Expected cash balance',
    addCash: 'Add Cash',
    removeCash: 'Remove Cash',
    cashPayments: 'All Cash Payments',
    totalCashOut: 'Total Cash Out',
    netPayment: 'Net Payment',
    endSession: 'End Session',
    amountAdded: 'Enter amount added',
    amountRemoved: 'Enter amount removed',
    cashAmount: 'Cash amount (USD)',
    enterAmount: 'Enter Amount',
    confirm: 'Confirm',
    endTrackingSession: 'End tracking session',
    endCashTrackingSession: 'End Cash Tracking Session',
    next: 'Next',
    summary: 'Summary',
    allCash: 'All Cash Payments',
    totalCashIn: 'Total Cash In',
    totalCash: 'USD $',
    netPayment: 'Net Payment',
    cashActivity: 'Cash activity',
    leftDrawer: 'Amount left in drawer : USD $0.00',
    dateTime: 'Today Friday Auguest 26, 2022   | 11.04 AM',
    allein: 'Allein',
    removeCash: 'Removed cash',
    discrepancy: 'Discrepancy',
    breakFast: 'Note: breakfast',
    startTrackingSession: 'Stared tracking session',
    amountCount: 'Amount counted : USD $0.00',
    sendEmailButton: 'Send to email',
    removeusd: '-USD $',
    sessionHistory: 'Session history',
    cashSummary: 'Cash summary',
    amountexpect: 'Amount expected',
    selectAmountDra: 'Select amount to leave in drawer',
    otherAmount: 'Other amount',
    transactionType: 'Transaction type',
    startSession: 'Start Session',
  },
  customers: {
    totalCustomer: 'Total Customers',
    users: 'Users',
    userprofile: 'User Profile',
    Edit: 'Edit',
    point: 'Points: 2',
    acceptMarket: 'Accept Marketing',
    costo: 'Costco Wholesale',
    costoAdd: '1189 Main Street, Seattle, WA 98161',
    detail: 'Details',
    orderStatus: 'Order status',
    assignDriver: 'Assigning driver',
    waitMinute: 'with in 10 minutes',
    delivery: 'Delivery',
    productPick: 'Product Pickup',
    readyPickup: 'Ready to pickup',
    orderPrepare: 'Order prepare',
    orderAccepted: 'Order accepted',
    carriar: 'Carriar:',
    geredo: 'Gerardo K. Jennings',
    contact: 'Contact',
    customer: 'Customers',
    showResult: 'Showing Results',
    userdetail: 'User details',
    orderReview: 'Order review',
  },
  trackingNumber: {
    trackingNo: 'Tracking Number# 7409309398BCEE',
  },
  calender: {
    calender: 'Calender',
    day: 'Day',
    week: 'Week',
    month: 'Month',
    decline: 'Decline',
    approve: 'Approve',
    approved: 'Accepted',
    cancel: 'Cancel',
    cancelAppointment: 'Do you want to cancel this appointment',
  },
  valiadtion: {
    validPhone: 'Please enter valid phone number',
    enterPhone: 'Please enter phone number',
    enterOtp: 'Please enter OTP',
    validOtp: 'Please enter valid OTP',
    enterPassCode: 'Please enter passcode',
    validPasscode: 'Please enter valid passcode',
    error: 'not found',
    phoneNotExist: 'This number does not exist',
    noData: 'No Data',
    noProduct: 'Product not found',
  },
  successMessages: {
    loginSuccess: 'Login succesfully',
  },
  reward: {
    totalReward: 'Total Rewards',
    jobrCountLabel: 'JOBR',
    first: '1',
    st: 'st',
    second: '2',
    nd: 'nd',
    third: '3',
    rd: 'rd',
    viewAll: 'View all',
    rewards: 'Rewards',
  },
  settings: {
    security: 'Security',
    twoStepVerifiCon: '2-step verification',
    securitysubhead:
      'An extra layer to boost your team members account security. A verification code will be required in addition to password each time you sign in.',
    memeberEnable: 'Team members must enable their own verification methods.',
    teamMemeber: '2-step verification for team members',
    enableSecurity: 'Enable Two-Steps Security',
    firstDownloader: 'First, download Google Authenticator from the ',
    googleAuth: 'Google authenticator',
    instead:
      'Instead of waiting for text messages, get verification codes from an authenticator app. It works even if your phone is offline.',
    doLater: 'I will do it later',
    next: 'Next',
    qrCode: 'Scan QR Code to active  google authenticator',
    device: 'Devices',
    configure: 'Configure Settings on Your Device',
    manageDevice:
      'All you need to manage Basic Point of Sale is a device nickname and location to allow team members to accept payments.',
    barScan: 'Barcode Scanner ',
    oneBlueTToth: '1 bluetooth device active',
    addNew: 'Add New',
    addbarcode: 'Add Barcode Scanner',
    pluginFirst: '1.  Plugin USB/C Port to  POS Monitor',
    pluginSecond: '2. Scan Barcode Below',
    codeAppear: 'Codes will appear here ',
    done: 'Done',
    addBlueToothHead: 'Add Bluetooth Barcode Scanner',
    searchForDevice: 'Searching for the devices....',
    foundOneDev: 'Found 1 device',
    location: 'Locations',
    businessLocation: 'Business locations',
    locationsubhead:
      'An extra layer to boost your team members account security. A verification code will be required in addition to password each time you sign in.',
    plans: 'Plans',
    yourPlan: 'Your Plan',
    basic: 'Basic',
    everyThingNeed: 'Everything you need to create a store, ship products, and process payments',
    chnagePlan: 'Change Plan',
    includePlan: 'Your Plan includes app',
    planFeat: 'Plan Features',
    paymentMethod: 'Payment method',
    planFit: 'Plan that fits your scale',
    simpleTra: 'Simple, Transparent pricing that grows with you',
    basicSubHead: 'Everything you need to create a store, ship products, and process payments',
    getStart: 'Get Started',
    invoice: 'Invoices',
    invoiveHeading: 'Taxes and duties',
    invoiveSubHeading:
      'Add a curbside, drive-through, or in-store pickup. Specify your business hours, the pickup location, and add a brief instruction on how the pickup works for customers.',
    smshead: 'Sms to phone number ',
    smsSubHead: 'It may apply charge ',
    printHead: 'Print invoice',
    printSubHead: 'Needs to connect printer for print invoice',
    emailHead: 'Email',
    emailSubHead: 'Email will Send to buyersi email address',
    invoiceTemplate: 'Invoice Template',
    publishDate: 'Publish date:',
    date: 'Sep 27, 2023 10: 00 AM',
    activate: 'Activate:',
    taxHead: 'Taxes and duties',
    taxSubHead:
      'If you haven’t already, create a shipping zone in the region(s) you’re liable in. Then, find the region in this list and select it to manage its tax settings. If you’re unsure about where you’re liable, check with a tax professional.',
    taxes: 'Taxes',
    active: 'Active',
    selectHead: 'Select your Operating Country',
    country: 'Country',
    cancel: 'Cancel',
    next: 'Next',
    selectHeadState: 'Select your Operating States',
    selectState: 'Select States',
    taxPayerHeadl: 'Tax Payer Information',
    name: 'Name',
    ssn: 'SSN or EIN',
    streetAdd: 'Street Address',
    appartement: 'Apartment/Suite',
    SSN: 'SSN',
    verified: 'Verified',
    operatingCountry: 'Operating Country',
    activateStateTax: 'Activate your State Tax',
    financialReport: 'This will show in your financial reports.',
    checkoutMore: 'Checkout for more',
    activateBtn: 'Activate',
    addState: 'Add State',
    craeteTax: 'Create tax',
    details: 'Details',
    taxName: 'Tax name',
    taxRate: 'Tax rate',
    location: 'Location',
    taxCalculation: 'Tax calculation',
    includeTax: 'Include tax in item price',
    includetaxSubhead:
      'If tax is included, the tax will appear in your reports, but your customers will not see the tax on their receipt.',
    notApplied: 'Specify when this tax should not be applied.',
    addRule: 'Add exemption rule',
    save: 'Save',
    taxexmption: 'Tax exemption name',
    exempttax: 'Exempt tax',
    amount: 'Amount',
    introduction: 'Introduction',
    notification: 'Notifications',
    addlanguage: 'Add Language',
    businessName: 'Business Name',
  },
  dashboard: {
    todaySale: "Today's Sales",
    cashSaleAmount: 'Cash sales amount',
    cardSaleAmount: 'Card sales amount',
    jobrCoinSaleAmount: 'JOBR Coin sales amount',
    cashDrawer: 'Cash Drawer',
    openBal: 'Opening Balance',
    closeBal: 'Closing Balance',
    logTime: 'Login Time',
    session: 'Session',
    lockScreen: 'Lock screen',
    deliveries: 'Order Deliveries',
    holdCart: 'Hold Cart',
    clearcart: 'Clear cart',
    ok: 'OK',
    totalItem: 'Total Items:',
    yourSessionEnd: 'Your Session Ends',
    expandOneHour: 'Expand 1 hour',
    expandTwoHour: 'Expand 2 hour',
    productReturn: 'Product Return',
  },
  wallet: {
    config: 'Wallet Config',
    payJBR: 'Pay by JBR Coin',
    system: 'System: Online Shop, POS',
    dafaultPayment: 'Dafault Payment',
    shopifyPayments:
      'You need to proivde some additional information about your business to start receiving payouts from Shopify Payments',
    payCash: 'Pay by Cash',
    systemPOS: 'System: POS',
    sila: 'Sila',
    setupSila: 'Setup Sila',
    cards: 'Cards,Bank tranfer and all',
    silaProtection:
      'Sila is a powerful processor that provides a sealess checkout experience, various payments options, and fraud protection.',
    payBusinesses:
      '.  Pay 2.9% + $0.30 per transaction. Custom rates are available for qualified businesses',
    sellChanges:
      ".  Sell subscription: collect your customers' card  details and charge automatically at a later time, with no additional fees for subscription charges",
    alwaysPayments:
      '.  Always feel secure with advanced fraud protection that automatically blocks high-risk payments',
    byAccount:
      'By enabling payments through Sila, you will be accepting Stripe Services Agreement. Please refer to the list of Prohibited Businesses before registering for and opening a Stripe account',
    silaButton: 'Setup Sila',
    transactions: 'Transactions:',
    totalTransections: 'Total Transactions:',
    transactionHistory: 'Transaction History',
    transationPrice: '$',
    paginationCount: '1-20 of 10,000',
    orderNo: 'Order# ',
    PaymentDetails: 'Payment Details',
    buyer: 'Buyer',
    angela: 'Angela K. Loving',
    angelaAddress1: '4156 College View Belleville, IL 62220',
    angelaAddress2: 'Phone:',
    invoiceDetails: 'Invoice details',
    invoiceIdLabel: 'Invoice Id: ',
    createDateLabel: 'Created Date: ',
    dueDateLabel: 'Due Date: ',
    deliveryDate: 'Delivery date: ',
    dueDate: '05-04-2022',
    subtotal: 'Sub-Total',
    serviceCharge: 'Service Charge',
    discount: 'Discount ( MIDApril100)',
    shippingCharge: 'Shipping Charge',
    total: 'Total',
    paid: 'Paid',
    shippingDetail: 'Shipping Details',
    trackingNo: 'Tracking number#  6533284651BC12',
    willis: 'Willis V Burleson',
    delivered: 'Delivered',
    tracking: 'Tracking',
    listOfItem: 'List of Items',
    item: 'items',
    point: 'Points:',
  },
  shipping: {
    shipping: 'Shipping & Pickups',
    local: 'Local Pickup',
    businessName: 'Business Name',
    address: '1899 Rollins Road , Grand Island Nebraska 68801, United States',
    jobrDelivery: 'JOBR Delivery',
    localOff: 'Local Drop-off',
    shippingText: 'Shipping',
  },
  Languages: {
    languages: 'Languages',
    Publishedlanguages: 'Published languages',
    active: "Active in the markets they've been added to and visible to customers.",
    addLanguage: 'Add language',
    languagesName: 'Language (7)',
    add: 'Add',
    cancel: 'Cancel',
  },
  posRetail: {
    categories: 'Categories',
    subCategories: 'Sub Categories',
    brand: 'Brands',
    payNow: 'Pay Now ',
    backProdscreen: 'Back to Product Screen',
    backServicescreen: 'Back to Service Screen',
    allProduct: 'All Products',
    searchCategory: 'Search Categories',
    searchSubCategory: 'Search Sub-catgories',
    searchBrand: 'Search Brands',
    searchStaff: 'Search Staffs',
  },
  Staff: {
    Staff: 'Staff',
    staffList: 'Staff List',
    staffDes: "Active in the markets they've been added to and visible to customers.",
    addStaff: 'Add Staff',
  },
  legal: {
    LegalText: 'Legal',
  },
  Policies: {
    PoliciesText: 'Policies',
  },
  deviceDetails: {
    deviceDetailsText: 'Device Details',
  },
  shippingOrder: {
    shippingStatus: `Today’s Shipping Status`,
    shippingOrders: 'Shipping Order',
    currentStatus: 'Current Status',
    orderConvertion: 'Order convertion',
    incomingOrders: 'Incoming Orders',
    processingOrders: 'Order Processing',
    readyPickupOrders: 'Ready For Pickup',
    totalItem: 'Total Item',
    orderDate: 'Order Date',
    orderId: 'Order ID#',
    completed: 'Completed',
    reviewOrders: 'Shipping Orders to Review',
    acceptedOrders: 'Shipping Orders Accepted',
    prepareOrders: 'Shipping Orders to Be Prepared',
  },
  deliveryOrders2: {
    orderStatus: 'Today’s Order Status',
    pickupOrders: 'Pickup Orders',
    noOrdersFound: 'No orders found',
    close: 'Close',
    jobr: 'JOBR',
    thanks: 'Thank You',
    pickedUp: 'Picked Up',
    returned: 'Returned',
    deliveryOrders: 'Delivery Order',
  },
  orderStatus: {
    reviewOrders: 'Orders to review',
    shipOrder: 'Shipped Orders',
    deliveryOrder: 'Delivered Orders',
    cancelledOrder: 'Rejected/ Cancelled Orders',
    returnedOrders: 'Returned Orders',
  },
  buttonStatus: {
    reviewButton: 'Accept',
    acceptedButton: 'Order Prepared',
    prepareButton: 'Ready to Pickup',
    preparedButton: 'Prepared',
    printlabel: 'Print Label',
  },
  returnOrder: {
    heading: 'Confirm the Return',
    returnConfirmed: 'Return Confirmed',
    customer: 'Customer:',
    driver: 'Driver:',
    userName: 'Karam Manab',
    address: 'Florida, USA',
    number: '23786587',
    totalItems: 'Total Items',
    totalItemsValue: '9',
    checkLater: 'Check later',
    recheck: 'Re-check',
    recheckConfirmed: 'Recheck confirmed!',
    description: 'All Returned item will be adjusted with inventory',
    scanbarCode: 'Scan barcode of each item returned',
    returnCart: 'Add to Return Cart',
    dollar: '$',
    percentage: '%',
    applyRefund: 'Apply Refund',
    applyEachItem: 'Apply for Each Item',
    applicable: 'Applicable for All Items',
    dollarLabel: 'dollar',
    percentageLabel: 'percentage',
  },
};
