export const en = {
  common: {
    loading: 'Loading',
    connectionError: 'Connection error',
  },
  home: {
    header: 'Home',
    message: 'Welcome',
    variant: 'App variant: ',
  },
  login: {
    username: 'Username',
    usernameHint: 'Enter your username',
    button: 'Login',
    password: 'Password',
    passwordHint: 'Enter your password',
    invalidCredentials: 'Invalid Username/Password',
  },
  profile: {
    header: 'Profile',
    logout: 'Logout',
    message: 'This screen has the iOS native large header.',
  },
  verifyPhone: {
    heading: 'Verify your phone number',
    subHeading: 'Please enter your number to phone number',
    placeHolderText: '815-288-0329',
    button: 'Continue',
  },
  verifyOtp: {
    heading: 'Verify your phone number',
    subHeading: 'Enter OTP code here',
    placeHolderText: '815-288-0329',
    
    button: 'Continue',
  },
  passcode: {
    heading: 'Enter Passcode',
    success: 'Successfully verified',
    loginBack:
      'Please login back to your email inbox and set your new password',
  },
  loginIntial: {
    heading: 'CONFIRM YOUR LOG IN',
    name: 'Millicent C. Edward',
    id: 'ID:256913',
    date: 'Today Wednesday 11 Aug 2022',
    time: 'Time 3:25 pm',
  },
  deliveryOrders: {
    heading: 'Delivery orders',
    search: 'Search',
    orderNumber: 'Number of Orders',
    orderReview: 'Orders to review',
    viewAll: 'View all',
    orderConversion: 'Order conversion',
    deliveryOrders: 'Delivering Orders',
    back: 'Back',
    orderId: 'Order#WXCOO1256',
    orderDate: 'August 30, 2022',
    name: 'Rebecca R. Russell',
    address: '1480 Bassel Street, New Orleans, LA 70113',
    deliveryType: 'Express Delivery',
    time: 'Immediately',
    ordersPreparing: 'Orders Preparing',
    ready: 'Ready for Pickup',
    subTotal: 'Sub Total',
    subTotalValue: '$4.00',
    discount: 'Discount',
    discountValue: '-$2.00',
    tax: 'Tax',
    total: 'Total',
    totalValue: '$254.60',
    items: '4 Items',
    readyButton: 'Ready for Pickup',
    decline: 'Decline',
    accept: 'Accept Order',
    profileName: 'John Mike',
    distance: '5.69 miles away',
    orderStatus: 'Order status',
    assignedDriver: 'Assigned driver',
    delivery: 'Delivery',
    pickup: 'Product Pickup',
    nextTo: 'Next to your block',
    assign: 'Assign Driver',
    orderAccepted: 'Order accepted',
    readyToPickup: 'Ready to pickup',
    within: 'with in 10 minutes',
    dateTime: '21 Jun, 2022  |   10:30 am',
    verifyCode: 'Verify code',
    verifyCode: 'Verify code',
    selectShip:'Select shipping',
    shippingOrder:'Shipping orders',
    shipPtr:'Pickup by SHIP PTNR SITE USPS AWAITS ITEM',
    imperialAdd:'IMPERIAL, PA, 15126, US • Aug 5, 2:39am',
    delivered:'Delivered',
    verifySuccess:'Verifiered successfull'
  },
  verifyPhone: {
    heading: 'Verify your phone number',
    subHeading: 'Please enter your number to phone number',
    placeHolderText: '815-288-0329',
    button: 'Continue',
  },
  verifyOtp: {
    heading: 'Verify your phone number',
    subHeading: 'Enter OTP code here',
    placeHolderText: '815-288-0329',
    button: 'Continue',
  },
  passcode: {
    heading: 'Enter Passcode',
    success: 'Successfully verified',
    loginBack:
      'Please login back to your email inbox and set your new password',
  },
  loginIntial: {
    heading: 'CONFIRM YOUR LOG IN',
    name: 'Millicent C. Edward',
    id: 'ID:256913',
    date: 'Today Wednesday 11 Aug 2022',
    time: 'Time 3:25 pm',
  },
  posSale: {
    paymentHeader: 'Customer & Payment',
    walletId: 'Wallet Id',
    scanText: 'or Scan',
    rederecting: 'Redirecting',
    listOfItem: 'List of items',
    rewardpoint: 'Reward Points : 500',
    onex: '1',
    price: '$382.75',
    onlyx: 'x',
    notes: 'Notes:',
    itMynday: 'Its for my birthday!',
    paymentdetail: 'Payment Details',
    paymenttdone: 'Payment Done!',
    Customer: 'Customer',
    customerNo: 'Customer phone number',
    customerName: 'Terry Moore',
    customerMobileNo: '803-238-2630',
    customerEmail: 'harryrady@jourrapide.com',
    customerAddr: '4849 Owagner Lane',
    customerAddr2: 'Seattle, WA 98101',
    customerTotalAmountHeader: 'Total amount: $254.60',
    tips: 'Tips',
    noTips: 'No Tips',
    cashRecive: 'Cash amount received',
    otherAmount: 'Other amount',
    changeDue: 'Change Due: $3.40',
    firstName: 'First name',
  },
  posSale: {
    paymentHeader: 'Customer & Payment',
    walletId: 'Wallet Id',
    scanText: 'or Scan',
    rederecting: 'Redirecting',
    listOfItem: 'List of items',
    rewardpoint: 'Reward Points : 500',
    onex: '1',
    price: '$382.75',
    onlyx: 'x',
    notes: 'Notes:',
    itMynday: 'Its for my birthday!',
    paymentdetail: 'Payment Details',
    paymenttdone: 'Payment Done!',
    Customer: 'Customer',
    customerNo: 'Customer phone number',
    customerName: 'Terry Moore',
    customerMobileNo: '803-238-2630',
    customerEmail: 'harryrady@jourrapide.com',
    customerAddr: '4849 Owagner Lane',
    customerAddr2: 'Seattle, WA 98101',
    customerTotalAmountHeader: 'Total amount: $254.60',
    tips: 'Tips',
    noTips: 'No Tips',
    cashRecive: 'Cash amount received',
    otherAmount: 'Other amount',
    changeDue: 'Change Due: $3.40',
    firstName: 'First name',
    availableStock: 'Available in stock: 206',
    addToCart: 'Add to cart',
    back: 'Back',
    marboloRed: 'Marlboro Red-Pack',
    details: 'Details',
    productDes:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam elementum, ligula quis ultricies iaculis, odio augue venenatis eros, interdum suscipit ipsum turpis nec velit. Vivamus cursus, dui vitae auctor finibus, felis ex malesuada nunc, eget fringilla ante dui in diam. Integer non dapibus nulla.',
    },
  wallet: {
    wallet: 'Wallet',
    totalTransections: 'Total Transactions:',
    today: 'Today',
    weekly: 'Weekly',
    monthly: 'Monthly',
    quaterly: 'Quaterly',
    yearly: 'Yearly',
    transationPrice: '$8,426,590',
    transectionsPrice: '$8,458,041',
    paginationCount: '1-20 of 10,000',
    orderNo: 'Order# 25659165659165',
    completed: 'Completed',
    PaymentDetails:'Payment Details',
    buyer:'Buyer',
    angela:'Angela K. Loving',
    angelaAddress1:'4156 College View Belleville, IL 62220',
    angelaAddress2:'Phone: 890-941-8897 44780',
    invoiceDetails:'Invoice details',
    invoiceIdLabel:'Invoice Id:',
    createDateLabel:'Created Date:',
    dueDateLabel:'Due Date:',
    deliveryDate:'Delivery date:',
    invoiceId:'025659165659165',
    createDate:'05-04-2022',
    dueDate:'05-04-2022',
    point:'Points: 20',
    subtotal:'Sub-Total',
    serviceCharge:'Service Charge (5%)',
    discount:'Discount ( MIDApril100)',
    shippingCharge:'Shipping Charge',
    total:'Total',
    subtotalPrice:'$7,363.20',
    paid:'Paid',
    shippingDetail:'Shipping Details',
    trackingNo:'Tracking number#  6533284651BC12',
    willis:'Willis V Burleson',
    delivered:'Delivered',
    tracking:'Tracking'
  },
  management: {
    cashTracking: 'Cash Tracking',
    cashDrawer: 'Cash Drawer',
    drawerID: 'Drawer ID: 1',
    drawerID2: 'Drawer ID: 2',
    session: 'Start tracking session',
    sessionHistory: 'Session history',
    countCash: 'Count cash in drawer',
    amountCounted: 'Amount counted (USD)',
    amount: '$ 0.00',
    note: 'Note',
    save: 'Save',
    viewSession: 'View session',
    date: 'Today Friday Auguest 26, 2022   | 11.04 AM',
    usd: 'USD $0.00',
    expected: 'Expected cash balance',
    addCash: 'Add Cash',
    removeCash: "Remove Cash",
    cashPayments: 'All Cash Payments',
    totalCashIn: 'Total Cash In',
    totalCashOut: 'Total Cash Out',
    netPayment: 'Net Payment',
    endSession: 'End Session',
    amountAdded: 'Enter amount added',
    amountRemoved: 'Enter amount removed',
    cashAmount: 'Cash amount (USD)',
    confirm: 'Confirm',
    endTrackingSession: 'End tracking session',
    next: 'Next',
    summary:'Summary',
    date:'Jun 21, 2022',
    allCash:'All Cash Payments',
    totalCashIn:'Total Cash In',
    totalCash:'USD $6,590.00',
    netPayment:'Net Payment',
    cashActivity:'Cash activity',
    endTrackingSession:'Ended tracking session',
    leftDrawer:'Amount left in drawer : USD $0.00',
    dateTime:'Today Friday Auguest 26, 2022   | 11.04 AM',
    allein:'Allein',
    removeCash:'Removed cash',
    countCash:'Counted Cash',
    discrepancy:'Discrepancy',
    breakFast:'Note: breakfast',
    startTrackingSession:'Stared tracking session',
    amountCount:'Amount counted : USD $0.00',
    sendEmailButton:'Send to email',
    sale:'sales',
    manual:'Manual',
    deliveryCharge:'Delivery Charge',
    shippingCharge:'Shipping Charge',
    refund:'Refund',
    manual:'Manual',
    removeusd:'-USD $25.10',
    sessionHistory:'Session history',
  },
  customers:{
    sales:'Sales',
    customerCount:'2,590',
    totalCustomer:'Total Customers',
    users:'Users',
    userprofile:'User Profile',
    Edit:'Edit',
    angela:'Angela K. Loving',
    phoneNumber:'4703-515-1193',
    email:'vidal.webe2@gmail.com',
    address:'4318 Daffodil Lane, Savage, Virginia(VA), 20763',
    point:'Points: 2',
    acceptMarket:'Accept Marketing',
    costo:'Costco Wholesale',
    costoAdd:'1189 Main Street, Seattle, WA 98161',
    detail:'Details',
    orderStatus:'Order status',
    assignDriver:'Assinging driver',
    verifyCode:'Verify code',
    waitMinute:'with in 10 minutes',
    delivery:'Delivery',
    yourBlock:'Next to your block',
    productPick:'Product Pickup',
    assignDriver:'Assinging driver',
    readyPickup:'Ready to pickup',
    orderAccepted:'Order accepted',
    dateTime:'21 Jun, 2022  |   10:30 am',
    carriar:'Carriar:',
    geredo:'Gerardo K. Jennings',
    contact:'Contact',
    customer:'Customers'

  },
  trackingNumber:{
    trackingNo:'Tracking Number# 7409309398BCEE'
  },
  calender:{
    calender:'Calender',
    requestFor:'Request for',
    hairCut:'Haircut',
    timeLabel:'Time:',
    time:'10.00 AM- 11.00 PM',
    dateLabel:'Date:',
    date:'Sunday, Oct 29, 2022',
    approve:'Approve',
    no:'No',
    name:'Charlene Reed',
    addr:'1189 Main Street, Seattle, WA 98161',
    mobileNo:'+1 923 782 4575',
    email:'richard@example.com',
    scheduledetails:'Schedule details',
    appointment:'Appointment Details',
    service:'Service',
    apt:'#APT0001',
    upcoming:'Upcoming',
    aptDate:'21 Oct 2019 10:00 AM',
    conform:'Confirm Date:',
    conformDate:'20 Oct 2019 10:00 AM',
    paidAmount:'Paid Amount',
    jbr:'JBR 300.00',
    day:'Day',
    week:'Week',
    month:'Month',
    accept:'Accept',
    decline:'Decline',
  },
  analytics:{
     header:'Analytics',
     totalProducts:'Total Products',
     totalProductsCount:'20,590',
     productDetails:'Product details',
     totalActiveProduct:'Total active Products ',
     totalInvetry:'Total Inventory  Cost',
     activeItem:'Active Items',
     invetryDetail :'Inventory Details',
     category:'Category:',
     tobacco:'Tobacco',
     edit:'Edit',
     marboloRed:'Marlboro Red-Pack',
     detail:'Details',
     description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam elementum, ligula quis ultricies iaculis, odio augue venenatis eros, interdum suscipit ipsum turpis nec velit. Vivamus cursus, dui vitae auctor finibus, felis ex malesuada nunc, eget fringilla ante dui in diam. Integer non dapibus nulla.',
     save:'Save',
     invoiveId:'Invoice id: 12154NBG',
     print:'Print',
     supplierDetails:'Supplier details:',
     supplierAdd:'623 Dorian Row Suite 435',
     supplierNewAdd:'New Olliehaven',
     streetNo:'Delaware 747-463',
     city:'Singapore',
     supplierPhoneNumber:'Phone: 890-941-8897 x44780',
     trackId:'Track Id', 
     dueDate:'Due Date',
     date:'Date',
     taxNumberLabel:'Tax Number:',
     taxNumber:'215698494946545131',
     FedEx:'FedEx',
     subtotal:'Sub Total',
     discount:'Discount',
     shippingCharge:'Shipping Charge',
     commision:'Commission (10%)',
     discountPrice:'$25.00',
     comisionCharge:'$100.00',
     orderHeaader:'Order# 25659165659165',
     complete:'Completed',
     walletId:'509 236 2365',
     walletIdLabel:'Wallet Id',
     returnShipingDetail:'Return Shipping Details',
     ups:'UPS',
     share:'Share',
     refund:'$255.00',
     sales:'Sales',
     totalRevenue:'Total Revenue',
     totalRevenueCount:'$6,920,590',
     totalOrder:'Total Order',
     totalRevenue:'Total Revenue',
     totalPrice:'$458,041',
     all:'All',
     onlineSale:'Online sales',
     storeSale:'Store sales',
     jbr:'JBR',
     cash:'Cash',
     card:'Card',
     totalOrder:'Total Order',
     totalOrderCount:'906',
     storeOrder:'Store Order',
     deliveryOrder:'Delivery Order',
     shipingOrder:"Shipping Order"
    },
    shipingOrder:{
      shipingRate:'$11.50',
      priorityMalling:'Priority Mailing services',
      dayShiping:'1-3 days shipping',
      printText:'Select & Continue to print',
      orderOfReview:'Orders to review',
      readyToShip:'Ready to ship',
      printAgain:'Print Again',
      outStock:'Out of stock',
      note:'Note',
      track:'Track',
      contact:'Contact',
      fedEx:'FedEx',
      fedNumber:'936128'
    },
    valiadtion:{
      validPhone :'Please enter valid phone number',
      enterPhone:'Please enter phone number',
      enterOtp:'Please enter OTP',
      fiveDigitOtp:'Please enter five digit OTP',
      validOtp:'Please enter valid OTP',
      enterPassCode:'Please enter passcode',
      validPasscode:'Please enter valid passcode'
    }
  
};
