import { StyleSheet, Dimensions, Platform } from 'react-native';
import { COLORS, SW, SH, SF, ShadowStyles } from '@/theme';
import { Fonts } from '@/assets';
import { moderateScale, verticalScale, scale, ms } from 'react-native-size-matters';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
    marginVertical: ms(15),
    borderRadius: ms(10),
    marginRight: ms(10),
    // paddingHorizontal: ms(10),
  },
  containerWhite: {
    flex: 1,
    backgroundColor: COLORS.red,
  },
  displayFlex: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  flexAlign: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  flexAlignNew: {
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: 'rgba(0, 0, 0, 0.1)', // Shadow color
    shadowOffset: { width: 1, height: 1 }, // Shadow offset
    shadowOpacity: 0.8, // Shadow opacity
    shadowRadius: 4, // Shadow radius
    elevation: 2,
    margin: 5,
  },
  headerMainView: {
    // width: windowWidth,
    paddingHorizontal: ms(16),
    // alignSelf: 'center',
    justifyContent: 'space-between',
    paddingVertical: SH(18),
    flexDirection: 'row',
    // backgroundColor: 'red',
  },
  headerMianViewbottomRow: {
    borderBottomWidth: 1,
    borderColor: COLORS.solidGrey,
  },
  deliveryView: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  leftBackStyle: {
    width: SW(9),
    height: SW(9),
    resizeMode: 'contain',
  },
  truckStyle: {
    width: ms(28),
    height: ms(28),
    resizeMode: 'contain',
  },
  deliveryText: {
    fontFamily: Fonts.SemiBold,
    color: COLORS.navy_blue,
    fontSize: ms(14),
    paddingLeft: SW(2),
  },
  searchView: {
    // height: SH(45),
    // borderRadius: ms(15),
    // flexDirection: 'row',
    // alignItems: 'center',
    // paddingLeft: 10,
    // borderWidth: 1,
    // borderColor: COLORS.row_grey,
    marginRight: ms(5),
  },
  searchImage: {
    width: ms(14),
    height: ms(14),
    resizeMode: 'contain',
  },
  textInputStyles: {
    width: ms(140),
    fontFamily: Fonts.Italic,
    fontSize: SF(15),
    paddingLeft: 5,
    padding: 0,
    margin: 0,
  },
  homeBodyCon: {
    marginHorizontal: ms(20),
  },
  totalCustomerCon: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: ms(10),
  },
  totalCustomerFirst: {
    fontFamily: Fonts.SemiBold,
    color: COLORS.solid_grey,
    fontSize: ms(10),
  },
  custometrCon: {
    width: Platform.OS === 'android' ? ms(160) : ms(135),
    // height: ms(94),
    borderRadius: 10,
    backgroundColor: COLORS.white,
    // justifyContent: 'center',
    // alignItems: 'center',
    marginHorizontal: ms(5),
    paddingHorizontal: ms(15),
    paddingVertical: ms(10),
    // flex: 1,
  },
  newCustomer: {
    width: SH(36),
    height: SH(36),
    resizeMode: 'contain',
  },
  customerCount: {
    fontFamily: Fonts.MaisonRegular,
    color: COLORS.solid_grey,
    fontSize: SF(24),
  },
  newCustomerHeading: {
    fontFamily: Fonts.Regular,
    color: COLORS.dark_grey,
    fontSize: SF(14),
  },
  contentContainerStyle: {
    // flex: 1,
    // justifyContent: 'space-between',
  },
  totalCusPrimary: {
    fontFamily: Fonts.SemiBold,
    color: COLORS.navy_blue,
    fontSize: ms(11),
    marginHorizontal: ms(15),
  },
  totalCustomer: {
    fontFamily: Fonts.SemiBold,
    color: COLORS.navy_blue,
    fontSize: ms(14),
  },
  viewButtonCon: {
    backgroundColor: COLORS.navy_blue,
    alignItems: 'center',
    borderRadius: ms(15),
    paddingHorizontal: ms(10),
    paddingVertical: ms(3),
    marginHorizontal: ms(15),
  },
  viewAll: {
    fontFamily: Fonts.Regular,
    color: COLORS.sky_blue,
    fontSize: SF(14),
  },

  // all Users css start
  backTitle: {
    color: COLORS.dark_grey,
    fontFamily: Fonts.SemiBold,
    fontSize: ms(8),
  },
  backIcon: {
    height: ms(10),
    width: ms(10),
    resizeMode: 'contain',
    marginRight: ms(3),
  },
  backIconProfile: {
    height: ms(15),
    width: ms(15),
    resizeMode: 'contain',
    marginRight: ms(3),
    tintColor: COLORS.navy_blue,
  },
  horizontalCustomerCon: {
    // backgroundColor: COLORS.textInputBackground,
    borderRadius: ms(15),
    // width: Platform.OS === 'android' ? ms(100) : ms(75),
    // height: ms(20),
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: ms(7),
    paddingVertical: ms(5),
    paddingHorizontal: ms(10),
  },
  horizCustomerText: {
    color: COLORS.navy_blue,
    fontFamily: Fonts.Regular,
    fontSize: ms(8),
  },
  orderTypeCon: {
    height: SH(22),
    justifyContent: 'center',
    paddingHorizontal: moderateScale(8),
    marginTop: ms(10),
  },
  datePickerCon: {
    borderWidth: 1,
    height: SH(35),
    width: ms(70),
    borderRadius: ms(5),
    borderColor: COLORS.solidGrey,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: ms(4),
    marginHorizontal: ms(10),
  },
  calendarStyle: {
    width: SW(5),
    height: SW(5),
    resizeMode: 'contain',
    marginRight: SW(1),
  },
  txtInput: {
    flex: 1,
    justifyContent: 'center',
    fontSize: SF(11),
    top: Platform.OS === 'android' ? 0 : 2,
    color: COLORS.navy_blue,
  },
  jbrTypeCon: {
    // backgroundColor: COLORS.textInputBackground,
    // height: SH(55),
    justifyContent: 'center',
    paddingHorizontal: moderateScale(8),
    position: 'absolute',
    top: 0,
    right: 0,
  },
  paginationEnd: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  columnSpace: {
    flexDirection: 'column',
    justifyContent: 'space-between',
    paddingHorizontal: moderateScale(5),
  },
  paginationCount: {
    fontSize: SF(14),
    fontFamily: Fonts.Regular,
    color: COLORS.black,
    paddingHorizontal: moderateScale(12),
  },
  dropDownIconPagination: {
    width: SW(4),
    height: SW(4),
    resizeMode: 'contain',
    tintColor: COLORS.navy_blue,
  },
  dropdown: {
    alignSelf: 'center',
    backgroundColor: 'transparent',
    borderColor: COLORS.transparent,
    zIndex: Platform.OS === 'ios' ? 100 : 0,
  },
  containerStylePagination: {
    width: ms(40),
    height: SH(35),
    justifyContent: 'center',
    borderWidth: 1,
    borderRadius: ms(5),
    borderColor: COLORS.light_purple,
    backgroundColor: COLORS.white,
    color: COLORS.solidGrey,
  },
  dropDownContainerStyle: {
    borderWidth: 1,
    borderColor: COLORS.transparent,
    borderRadius: 7,
    ...ShadowStyles.shadow,
    backgroundColor: COLORS.white,
    top: Platform.OS === 'android' ? 30 : 35,
    zIndex: Platform.OS === 'ios' ? 100 : 1,
  },
  listItemLabelStyle: {
    fontSize: SF(12),
    fontFamily: Fonts.Regular,
    color: COLORS.navy_blue,
  },
  labelStyle: {
    fontSize: SF(14),
    fontFamily: Fonts.Medium,
    color: COLORS.navy_blue,
  },
  selectedItemLabelStyle: {
    fontSize: SF(12),
    fontFamily: Fonts.Regular,
    color: COLORS.navy_blue,
  },
  placeholderStylePagination: {
    fontSize: SF(12),
    fontFamily: Fonts.Regular,
    color: COLORS.navy_blue,
  },
  unionCon: {
    backgroundColor: COLORS.sky_grey,
    height: SH(40),
    justifyContent: 'center',
    borderRadius: ms(5),
    marginRight: ms(7),
  },
  unionStyle: {
    width: SW(5),
    height: SW(5),
    resizeMode: 'contain',
    paddingHorizontal: moderateScale(12),
  },
  paginationCount: {
    fontSize: ms(10),
    fontFamily: Fonts.Regular,
    color: COLORS.navy_blue,
    paddingHorizontal: ms(3),
  },
  tableDataHeaderCon: {
    height: SH(50),
    // backgroundColor: COLORS.textInputBackground,
    textAlign: 'center',
    borderColor: COLORS.solidGrey,
    paddingHorizontal: moderateScale(20),
    justifyContent: 'center',
  },
  tableHeaderLeft: {
    flexDirection: 'row',
    width: windowWidth * 0.35,
    alignItems: 'center',
  },
  tableTextHeaFirst: {
    color: COLORS.lavender,
    fontFamily: Fonts.MaisonBold,
    fontSize: SF(14),
    letterSpacing: -1,
    width: windowWidth * 0.01,
    marginLeft: ms(5),
  },
  tableTextHea: {
    color: COLORS.lavender,
    fontFamily: Fonts.MaisonBold,
    fontSize: SF(14),
    letterSpacing: -1,
    width: windowWidth * 0.15,
  },
  tableHeaderRight: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: Platform.OS === 'android' ? windowWidth * 0.5 : windowWidth * 0.45,
  },
  tableHeaderRightInner: {
    width: Platform.OS === 'android' ? windowWidth * 0.17 : windowWidth * 0.14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tableTextHeader: {
    color: COLORS.lavender,
    fontFamily: Fonts.MaisonBold,
    fontSize: SF(14),
  },
  tableDataCon: {
    // height: SH(55),
    borderWidth: ms(1),
    borderColor: COLORS.light_purple,
    justifyContent: 'center',
    paddingHorizontal: ms(12),
    marginVertical: ms(5),
    borderRadius: ms(25),
    marginHorizontal: ms(12),
    paddingVertical: ms(5),
  },
  tableTextDataFirst: {
    color: COLORS.solid_grey,
    fontFamily: Fonts.Regular,
    fontSize: SF(14),
    letterSpacing: -1,
    width: windowWidth * 0.02,
  },
  lovingStyleData: {
    width: ms(22),
    height: ms(22),
    resizeMode: 'contain',
    borderRadius: 50,
  },
  tableTextDataName: {
    color: COLORS.black,
    fontFamily: Fonts.SemiBold,
    fontSize: SF(14),
    width: windowWidth * 0.2,
  },
  tableTextDataAdd: {
    color: COLORS.solid_grey,
    fontFamily: Fonts.Regular,
    fontSize: SF(12),
    width: windowWidth * 0.3,
  },
  tableTextData: {
    color: COLORS.black,
    fontFamily: Fonts.Regular,
    fontSize: SF(14),
    paddingLeft: ms(5),
  },
  editButtonCon: {
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 7,
  },
  editButtonText: {
    color: COLORS.primary,
    fontFamily: Fonts.Regular,
    fontSize: SF(12),
    paddingHorizontal: moderateScale(7),
    paddingVertical: verticalScale(2),
  },

  // userprofile module css start

  profileCon: {
    // borderWidth: 1,
    // borderColor: COLORS.solidGrey,
    borderRadius: 15,
    // height: SH(130),
    // justifyContent: 'center',
    marginHorizontal: ms(10),
    // marginTop: ms(7),
    backgroundColor: COLORS.sky_grey,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: ms(10),
    paddingVertical: ms(10),
    alignItems: 'center',
  },
  lovingStyle: {
    width: ms(30),
    height: ms(30),
    resizeMode: 'contain',
    borderRadius: 50,
  },
  angelaText: {
    fontFamily: Fonts.Medium,
    fontSize: SF(25),
    color: COLORS.navy_blue,
  },
  Phonelight: {
    width: ms(12),
    height: ms(12),
    resizeMode: 'contain',
    tintColor: COLORS.navy_blue,
  },
  adressText: {
    fontFamily: Fonts.Regular,
    fontSize: SF(14),
    color: COLORS.navy_blue,
    paddingHorizontal: ms(2),
    // width: windowWidth * 0.4,
  },
  pointCon: {
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 7,
    height: ms(28),
    width: SW(70),
    justifyContent: 'center',
    alignItems: 'center',
    // position: 'absolute',
    // right: ms(0),
  },
  rewardStyle: {
    width: ms(14),
    height: ms(14),
    resizeMode: 'contain',
    tintColor: COLORS.orange,
  },
  pointText: {
    fontFamily: Fonts.SemiBold,
    fontSize: SF(13),
    color: COLORS.orange,
    paddingHorizontal: moderateScale(3),
  },
  acceptCon: {
    // position: 'absolute',
    // right: ms(0),
    // bottom: ms(-5),
  },
  toggleBtnStyle: {
    width: SW(8),
    height: SW(8),
    resizeMode: 'contain',
    tintColor: COLORS.navy_blue,
  },
  toggleBtnCon: {
    width: SW(11),
    height: SW(8),
  },
  toggleBtnStyle2: {
    width: SW(8),
    height: SW(8),
    resizeMode: 'contain',
    tintColor: COLORS.gerySkies,
    transform: [{ rotate: '180deg' }],
  },
  acceptMarketText: {
    fontFamily: Fonts.Regular,
    fontSize: SF(13),
    color: COLORS.navy_blue,
  },
  orderTypeCon: {
    height: SH(55),
    justifyContent: 'center',
    paddingHorizontal: moderateScale(8),
  },
  profileheaderUnderView: {
    flexDirection: 'row',
  },
  profileheaderChildView: {
    width: Platform.OS === 'android' ? ms(100) : ms(83),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: ms(3),
  },
  userNotFound: {
    color: COLORS.navy_blue,
    fontFamily: Fonts.MaisonRegular,
    fontSize: SF(20),
    alignSelf: 'center',
  },
  saleTypeButtonCon: {
    paddingHorizontal: ms(5),
    paddingVertical: ms(1),
    borderRadius: ms(10),
    paddingVertical: ms(1),
  },
  scnStyle: {
    width: SW(13),
    height: SW(14),
    resizeMode: 'contain',
  },
  walletHomeBodyCon: {
    flex: 1,
    borderWidth: 1,
  },
  loader: {
    position: 'absolute',
    alignSelf: 'center',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
  },
  loaderView: {
    height: ms(150),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
  },
  profilDetailChildView: {
    width: Platform.OS === 'android' ? ms(115) : ms(95),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: ms(3),
  },
  calendarModalView: {
    backgroundColor: COLORS.white,
    width: windowWidth * 0.6,
    height: windowHeight - SW(30),
    alignSelf: 'center',
    paddingVertical: SH(10),
    paddingHorizontal: SW(5),
    borderRadius: SW(5),
  },
  textInputStyle: {
    height: SH(40),
    width: '100%',
    fontFamily: Fonts.Italic,
    fontSize: SF(12),
    paddingLeft: 5,
    margin: 0,
    padding: 0,
  },
  varientTextStyle: {
    fontSize: SF(11),
    color: COLORS.darkGray,
    fontFamily: Fonts.Regular,
  },
  checkboxIconStyle: {
    width: SH(24),
    height: SH(24),
    resizeMode: 'contain',
  },
  checkboxViewStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: ms(10),
  },
  flexRow: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'absolute',
    right: ms(2),
  },
});
