import { COLORS, Fonts, SF, SH, SW } from '@/theme';
import { Dimensions, Platform, StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.inputBorder,
  },
  subCategoryImageStyle: {
    width: SW(24),
    height: SW(24),
    resizeMode: 'contain',
  },
  subCategoryTitleText: {
    fontFamily: Fonts.SemiBold,
    fontSize: SF(13),
    color: COLORS.text,
  },
  subCategoryMainView: {
    borderWidth: 1,
    height: SH(52),
    // width: SW(160),
    borderRadius: 30,
    alignItems: 'center',
    flexDirection: 'row',
    paddingHorizontal: 10,
    marginHorizontal: 3,
    borderColor: COLORS.light_border,
    backgroundColor: COLORS.white,
  },
  backIconView: {
    borderRadius: 30,
    height: SH(49),
    width: SW(55),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.text,
  },
  backIconstyle: {
    width: SW(14),
    height: SH(14),
    resizeMode: 'contain',
    tintColor: COLORS.skyBlue,
  },
  contentContainerStyle: {
    marginHorizontal: 10,
    marginTop: 10,
    paddingBottom: 30,
    paddingRight: 20,
  },
  productDetailMainView: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    paddingVertical: 5,
    marginVertical: 5,
    marginHorizontal: 10,
    borderRadius: 5,
    paddingHorizontal: 10,
    justifyContent: 'space-between',
  },
  productNameText: {
    fontFamily: Fonts.Regular,
    fontSize: SF(14),
    color: COLORS.black,
  },
  genderTextStyle: {
    fontFamily: Fonts.Regular,
    fontSize: SF(11),
    color: COLORS.grayShade,
    paddingTop: 2,
  },
  priceTextStyle: {
    textAlign: 'right',
    fontFamily: Fonts.SemiBold,
    fontSize: SF(14),
    color: COLORS.dark_gray,
  },
  stockTextStyle: {
    fontFamily: Fonts.Regular,
    fontSize: SF(11),
    color: COLORS.text,
    paddingTop: 2,
  },
  productImageStyle: {
    width: SW(48),
    height: SW(48),
    borderRadius: 5,
    resizeMode: 'contain',
  },
  imageDetailView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headingView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.light_border,
    paddingVertical: 20,
  },
  crossImageStyle: {
    width: SW(16),
    height: SW(16),
    resizeMode: 'contain',
  },
  amountTextStyle: {
    fontFamily: Fonts.SemiBold,
    fontSize: SF(16),
    color: COLORS.dark_gray,
  },
  productDetailView: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 12,
    backgroundColor: COLORS.white,
  },
  detailImageStyle: {
    width: SW(80),
    height: SW(80),
    borderRadius: 7,
    resizeMode: 'contain',
  },
  productDescription: {
    fontFamily: Fonts.Regular,
    fontSize: SF(9),
    color: COLORS.text,
    paddingTop: 3,
  },
  priceViewStyle: {
    flexDirection: 'row',
    marginHorizontal: 10,
    height: SH(53),
    alignItems: 'center',
    paddingHorizontal: 10,
    borderRadius: 5,
    justifyContent: 'space-between',
    backgroundColor: COLORS.inputBorder,
  },
  descriptionView: {
    borderWidth: 1,
    borderColor: COLORS.light_border,
    borderRadius: 5,
    marginHorizontal: 10,
  },
  descriptionItemView: {
    flexDirection: 'row',
    height: SH(53),
    alignItems: 'center',
    paddingHorizontal: 10,
    borderRadius: 5,
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: COLORS.light_border,
    marginTop: 5,
  },
  descriptionText: {
    fontFamily: Fonts.Regular,
    fontSize: SF(12),
    color: COLORS.dark_gray,
  },
  discardButtonStyle: {
    height: SH(53),
    backgroundColor: COLORS.inputBorder,
    borderRadius: 5,
    width: SH(180),
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 5,
  },
  addToCartButton: {
    height: SH(53),
    backgroundColor: COLORS.darkBlue,
    borderRadius: 5,
    width: SH(180),
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 5,
  },
  bottomButtonView: {
    flexDirection: 'row',
    // position: 'absolute',
    alignSelf: 'center',
    // bottom: Platform.OS === 'android' ? 0 : 30,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
  },
  quantityTextStyle: {
    fontFamily: Fonts.MaisonBold,
    fontSize: SF(24),
    color: COLORS.dark_gray,
  },
  quantityViewStyle: {
    width: Dimensions.get('window').width - 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    // position: 'absolute',
    // bottom: 80,
    alignSelf: 'center',
    borderRadius: 5,
    height: SH(60),
    backgroundColor: COLORS.blueShade,
    paddingHorizontal: 30,
  },
});

export default styles;
